from .state_block import StateBlock

headerLineRe = ...
enclosingPipesRe = ...
MAX_AUTOCOMPLETED_CELLS = ...

def getLine(state: StateBlock, line: int) -> str: ...
def escapedSplit(string: str) -> list[str]: ...
def table(state: StateBlock, startLine: int, endLine: int, silent: bool) -> bool: ...
