"""This type stub file was generated by pyright.
"""

from tomlkit.api import (
    TOMLDocument,
    aot,
    array,
    boolean,
    comment,
    date,
    datetime,
    document,
    dump,
    dumps,
    float_,
    inline_table,
    integer,
    item,
    key,
    key_value,
    load,
    loads,
    nl,
    parse,
    register_encoder,
    string,
    table,
    time,
    unregister_encoder,
    value,
    ws,
)

__version__ = ...
__all__ = ["TOMLDocument", "aot", "array", "boolean", "comment", "date", "datetime", "document", "dump", "dumps", "float_", "inline_table", "integer", "item", "key", "key_value", "load", "loads", "nl", "parse", "register_encoder", "string", "table", "time", "unregister_encoder", "value", "ws"]
