"""This type stub file was generated by pyright.
Enhanced with proper MutableMapping/MutableSequence inheritance.
"""

from collections.abc import Callable, MutableMapping, MutableSequence
from typing import (
    TYPE_CHECKING,
    Any,
    Concatenate,
    ParamSpec,
    Protocol,
    Self,
    TypeVar,
)

WT = TypeVar("WT", bound=WrapperType)

if TYPE_CHECKING:
    P = ParamSpec("P")
    class WrapperType(Protocol):
        def _new(self, value: Any) -> Self: ...

    # For type checking, use builtins to avoid MutableMapping/MutableSequence issues
    _CustomDict = dict
    _CustomList = list
    _CustomInt = int
    _CustomFloat = float
else:
    # Runtime definitions
    class _CustomList(MutableSequence, list):
        """Adds MutableSequence mixin while pretending to be a builtin list"""

        def __add__(self, other: Any) -> _CustomList: ...
        def __iadd__(self, other: Any) -> _CustomList: ...

    class _CustomDict(MutableMapping, dict):
        """Adds MutableMapping mixin while pretending to be a builtin dict"""

        def __or__(self, other: dict[str, Any]) -> _CustomDict: ...
        def __ior__(self, other: dict[str, Any]) -> _CustomDict: ...

    class _CustomInt(int):
        """Adds Integral mixin while pretending to be a builtin int"""

    class _CustomFloat(float):
        """Adds Real mixin while pretending to be a builtin float"""

def wrap_method(
    original_method: Callable[Concatenate[WT, P], Any],
) -> Callable[Concatenate[WT, P], Any]: ...
