"""This type stub file was generated by pyright.
"""

from collections.abc import Iterable, Mapping
from typing import IO, TYPE_CHECKING, TypeVar

from tomlkit.items import (
    AoT,
    Array,
    Bool,
    Comment,
    Date,
    DateTime,
    Encoder,
    Float,
    InlineTable,
    Integer,
    Item as _Item,
    Key,
    String,
    Table,
    Time,
    Whitespace,
)
from tomlkit.toml_document import TOMLDocument

if TYPE_CHECKING:
    E = TypeVar("E", bound=Encoder)

def loads(string: str | bytes) -> TOMLDocument:
    """Parses a string into a TOMLDocument.

    Alias for parse().
    """
    ...

def dumps(data: Mapping[str, object], sort_keys: bool = ...) -> str:
    """Dumps a TOMLDocument into a string.
    """
    ...

def load(fp: IO[str] | IO[bytes]) -> TOMLDocument:
    """Load toml document from a file-like object.
    """
    ...

def dump(data: Mapping[str, object], fp: IO[str], *, sort_keys: bool = ...) -> None:
    """Dump a TOMLDocument into a writable file stream.

    :param data: a dict-like object to dump
    :param sort_keys: if true, sort the keys in alphabetic order

    :Example:

    >>> with open("output.toml", "w") as fp:
    ...     tomlkit.dump(data, fp)
    """
    ...

def parse(string: str | bytes) -> TOMLDocument:
    """Parses a string or bytes into a TOMLDocument.
    """
    ...

def document() -> TOMLDocument:
    """Returns a new TOMLDocument instance.
    """
    ...

def integer(raw: str | int) -> Integer:
    """Create an integer item from a number or string."""
    ...

def float_(raw: str | float) -> Float:
    """Create an float item from a number or string."""
    ...

def boolean(raw: str | bool) -> Bool:
    """Turn `true` or `false` into a boolean item."""
    ...

def string(
    raw: str, *, literal: bool = ..., multiline: bool = ..., escape: bool = ...
) -> String:
    """Create a string item.

    By default, this function will create *single line basic* strings, but
    boolean flags (e.g. ``literal=True`` and/or ``multiline=True``)
    can be used for personalization.

    For more information, please check the spec: `<https://toml.io/en/v1.0.0#string>`__.

    Common escaping rules will be applied for basic strings.
    This can be controlled by explicitly setting ``escape=False``.
    Please note that, if you disable escaping, you will have to make sure that
    the given strings don't contain any forbidden character or sequence.
    """
    ...

def date(raw: str) -> Date:
    """Create a TOML date."""
    ...

def time(raw: str) -> Time:
    """Create a TOML time."""
    ...

def datetime(raw: str) -> DateTime:
    """Create a TOML datetime."""
    ...

def array(raw: str = ...) -> Array:
    """Create an array item for its string representation.

    :Example:

    >>> array("[1, 2, 3]")  # Create from a string
    [1, 2, 3]
    >>> a = array()
    >>> a.extend([1, 2, 3])  # Create from a list
    >>> a
    [1, 2, 3]
    """
    ...

def table(is_super_table: bool | None = ...) -> Table:
    """Create an empty table.

    :param is_super_table: if true, the table is a super table

    :Example:

    >>> doc = document()
    >>> foo = table(True)
    >>> bar = table()
    >>> bar.update({"x": 1})
    >>> foo.append("bar", bar)
    >>> doc.append("foo", foo)
    >>> print(doc.as_string())
    [foo.bar]
    x = 1
    """
    ...

def inline_table() -> InlineTable:
    """Create an inline table.

    :Example:

    >>> table = inline_table()
    >>> table.update({"x": 1, "y": 2})
    >>> print(table.as_string())
    {x = 1, y = 2}
    """
    ...

def aot() -> AoT:
    """Create an array of table.

    :Example:

    >>> doc = document()
    >>> aot = aot()
    >>> aot.append(item({"x": 1}))
    >>> doc.append("foo", aot)
    >>> print(doc.as_string())
    [[foo]]
    x = 1
    """
    ...

def key(k: str | Iterable[str]) -> Key:
    """Create a key from a string. When a list of string is given,
    it will create a dotted key.

    :Example:

    >>> doc = document()
    >>> doc.append(key("foo"), 1)
    >>> doc.append(key(["bar", "baz"]), 2)
    >>> print(doc.as_string())
    foo = 1
    bar.baz = 2
    """
    ...

def value(raw: str) -> _Item:
    """Parse a simple value from a string.

    :Example:

    >>> value("1")
    1
    >>> value("true")
    True
    >>> value("[1, 2, 3]")
    [1, 2, 3]
    """
    ...

def key_value(src: str) -> tuple[Key, _Item]:
    """Parse a key-value pair from a string.

    :Example:

    >>> key_value("foo = 1")
    (Key('foo'), 1)
    """
    ...

def ws(src: str) -> Whitespace:
    """Create a whitespace from a string."""
    ...

def nl() -> Whitespace:
    """Create a newline item."""
    ...

def comment(string: str) -> Comment:
    """Create a comment item."""
    ...

def register_encoder(encoder: E) -> E:
    """Add a custom encoder, which should be a function that will be called
    if the value can't otherwise be converted.

    The encoder should return a TOMLKit item or raise a ``ConvertError``.

    Example:
        @register_encoder
        def encode_custom_dict(obj, _parent=None, _sort_keys=False):
            if isinstance(obj, CustomDict):
                tbl = table()
                for key, value in obj.items():
                    # Pass along parameters when encoding nested values
                    tbl[key] = item(value, _parent=tbl, _sort_keys=_sort_keys)
                return tbl
            raise ConvertError("Not a CustomDict")

    """
    ...

def unregister_encoder(encoder: Encoder) -> None:
    """Unregister a custom encoder."""
    ...
