"""This type stub file was generated by pyright.
"""

from collections.abc import Collection

class TOMLKitError(Exception):
    ...

class ParseError(ValueError, TOMLKitError):
    """This error occurs when the parser encounters a syntax error
    in the TOML being parsed. The error references the line and
    location within the line where the error was encountered.
    """

    def __init__(self, line: int, col: int, message: str | None = ...) -> None:
        ...
    
    @property
    def line(self):  # -> int:
        ...
    
    @property
    def col(self):  # -> int:
        ...
    
class MixedArrayTypesError(ParseError):
    """An array was found that had two or more element types.
    """

    def __init__(self, line: int, col: int) -> None:
        ...
    
class InvalidNumberError(ParseError):
    """A numeric field was improperly specified.
    """

    def __init__(self, line: int, col: int) -> None:
        ...
    
class InvalidDateTimeError(ParseError):
    """A datetime field was improperly specified.
    """

    def __init__(self, line: int, col: int) -> None:
        ...
    
class InvalidDateError(ParseError):
    """A date field was improperly specified.
    """

    def __init__(self, line: int, col: int) -> None:
        ...
    
class InvalidTimeError(ParseError):
    """A date field was improperly specified.
    """

    def __init__(self, line: int, col: int) -> None:
        ...
    
class InvalidNumberOrDateError(ParseError):
    """A numeric or date field was improperly specified.
    """

    def __init__(self, line: int, col: int) -> None:
        ...
    
class InvalidUnicodeValueError(ParseError):
    """A unicode code was improperly specified.
    """

    def __init__(self, line: int, col: int) -> None:
        ...
    
class UnexpectedCharError(ParseError):
    """An unexpected character was found during parsing.
    """

    def __init__(self, line: int, col: int, char: str) -> None:
        ...
    
class EmptyKeyError(ParseError):
    """An empty key was found during parsing.
    """

    def __init__(self, line: int, col: int) -> None:
        ...
    
class EmptyTableNameError(ParseError):
    """An empty table name was found during parsing.
    """

    def __init__(self, line: int, col: int) -> None:
        ...
    
class InvalidCharInStringError(ParseError):
    """The string being parsed contains an invalid character.
    """

    def __init__(self, line: int, col: int, char: str) -> None:
        ...
    
class UnexpectedEofError(ParseError):
    """The TOML being parsed ended before the end of a statement.
    """

    def __init__(self, line: int, col: int) -> None:
        ...
    
class InternalParserError(ParseError):
    """An error that indicates a bug in the parser.
    """

    def __init__(self, line: int, col: int, message: str | None = ...) -> None:
        ...
    
class NonExistentKey(KeyError, TOMLKitError):
    """A non-existent key was used.
    """

    def __init__(self, key) -> None:
        ...
    
class KeyAlreadyPresent(TOMLKitError):
    """An already present key was used.
    """

    def __init__(self, key) -> None:
        ...
    
class InvalidControlChar(ParseError):
    def __init__(self, line: int, col: int, char: int, type: str) -> None:
        ...
    
class InvalidStringError(ValueError, TOMLKitError):
    def __init__(self, value: str, invalid_sequences: Collection[str], delimiter: str) -> None:
        ...
    
class ConvertError(TypeError, ValueError, TOMLKitError):
    """Raised when item() fails to convert a value.
    It should be a TypeError, but due to historical reasons
    it needs to subclass ValueError as well.
    """
