"""This type stub file was generated by pyright.
"""

from tomlkit.exceptions import ParseError
from tomlkit.toml_document import TOMLDocument

CTRL_I = ...
CTRL_J = ...
CTRL_M = ...
CTRL_CHAR_LIMIT = ...
CHR_DEL = ...
class Parser:
    """Parser for TOML documents.
    """

    def __init__(self, string: str | bytes) -> None:
        ...
    
    def extract(self) -> str:
        """Extracts the value between marker and index
        """
        ...
    
    def inc(self, exception: type[ParseError] | None = ...) -> bool:
        """Increments the parser if the end of the input has not been reached.
        Returns whether or not it was able to advance.
        """
        ...
    
    def inc_n(self, n: int, exception: type[ParseError] | None = ...) -> bool:
        """Increments the parser by n characters
        if the end of the input has not been reached.
        """
        ...
    
    def consume(self, chars, min=..., max=...):  # -> None:
        """Consume chars until min/max is satisfied is valid.
        """
        ...
    
    def end(self) -> bool:
        """Returns True if the parser has reached the end of the input.
        """
        ...
    
    def mark(self) -> None:
        """Sets the marker to the index's current position
        """
        ...
    
    def parse_error(self, exception=..., *args, **kwargs):  # -> ParseError:
        """Creates a generic "parse error" at the current position.
        """
        ...
    
    def parse(self) -> TOMLDocument:
        ...
