"""This type stub file was generated by pyright.
"""

from typing import Any

from tomlkit.exceptions import ParseError
from tomlkit.toml_char import TOMLChar

class _State:
    def __init__(self, source: Source, save_marker: bool | None = ..., restore: bool | None = ...) -> None:
        ...
    
    def __enter__(self) -> _State:
        ...
    
    def __exit__(self, exception_type, exception_val, trace):  # -> None:
        ...
    
class _StateHandler:
    """State preserver for the Parser.
    """

    def __init__(self, source: Source) -> None:
        ...
    
    def __call__(self, *args, **kwargs):  # -> _State:
        ...
    
    def __enter__(self) -> _State:
        ...
    
    def __exit__(self, exception_type, exception_val, trace):
        ...
    
class Source(str):
    EOF = ...
    def __init__(self, _: str) -> None:
        ...
    
    def reset(self):  # -> None:
        ...
    
    @property
    def state(self) -> _StateHandler:
        ...
    
    @property
    def idx(self) -> int:
        ...
    
    @property
    def current(self) -> TOMLChar:
        ...
    
    @property
    def marker(self) -> int:
        ...
    
    def extract(self) -> str:
        """Extracts the value between marker and index
        """
        ...
    
    def inc(self, exception: type[ParseError] | None = ...) -> bool:
        """Increments the parser if the end of the input has not been reached.
        Returns whether or not it was able to advance.
        """
        ...
    
    def inc_n(self, n: int, exception: type[ParseError] | None = ...) -> bool:
        """Increments the parser by n characters
        if the end of the input has not been reached.
        """
        ...
    
    def consume(self, chars, min=..., max=...):  # -> None:
        """Consume chars until min/max is satisfied is valid.
        """
        ...
    
    def end(self) -> bool:
        """Returns True if the parser has reached the end of the input.
        """
        ...
    
    def mark(self) -> None:
        """Sets the marker to the index's current position
        """
        ...
    
    def parse_error(self, exception: type[ParseError] = ..., *args: Any, **kwargs: Any) -> ParseError:
        """Creates a generic "parse error" at the current position.
        """
        ...
