"""This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from _typeshed import StrPath as _StrPath
from tomlkit.toml_document import TOMLDocument

if TYPE_CHECKING:
    ...
class TOMLFile:
    """Represents a TOML file.

    :param path: path to the TOML file
    """

    def __init__(self, path: _StrPath) -> None:
        ...
    
    def read(self) -> TOMLDocument:
        """Read the file content as a :class:`tomlkit.toml_document.TOMLDocument`."""
        ...
    
    def write(self, data: TOMLDocument) -> None:
        """Write the TOMLDocument to the file."""
        ...
