"""This type stub file was generated by pyright.
"""

"""
This module handles retrieval of configuration values from either the
command-line arguments or the pyproject.toml file.
"""
DEFAULTS = ...
class InputError(Exception):
    def __init__(self, message) -> None:
        ...
    
def make_config(argv=..., tomlfile=...):  # -> Any | dict[Any, Any]:
    """Returns a config object for vulture, merging both ``pyproject.toml`` and
    CLI arguments (CLI arguments have precedence).

    :param argv: The CLI arguments to be parsed. This value is transparently
        passed through to :py:meth:`argparse.ArgumentParser.parse_args`.
    :param tomlfile: An IO instance containing TOML data. By default this will
        auto-detect an existing ``pyproject.toml`` file and exists solely for
        unit-testing.
    """
