"""This type stub file was generated by pyright.
"""

import ast

DEFAULT_CONFIDENCE = ...
IGNORED_VARIABLE_NAMES = ...
PYTEST_FUNCTION_NAMES = ...
PYTEST_METHOD_NAMES = ...
ERROR_CODES = ...
class Item:
    """Hold the name, type and location of defined code.
    """

    __slots__ = ...
    def __init__(self, name, typ, filename, first_lineno, last_lineno, message=..., confidence=...) -> None:
        ...
    
    @property
    def size(self):  # -> int:
        ...
    
    def get_report(self, add_size=...):  # -> str:
        ...
    
    def get_whitelist_string(self):  # -> str:
        ...
    
    def __repr__(self):  # -> str:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    
class Vulture(ast.NodeVisitor):
    """Find dead code."""

    def __init__(self, verbose=..., ignore_names=..., ignore_decorators=...) -> None:
        ...
    
    def scan(self, code, filename=...):  # -> None:
        ...
    
    def scavenge(self, paths, exclude=...):  # -> None:
        ...
    
    def get_unused_code(self, min_confidence=..., sort_by_size=...) -> list[Item]:
        """Return ordered list of unused Item objects.
        """
    
    def report(self, min_confidence=..., sort_by_size=..., make_whitelist=...):  # -> ExitCode:
        """Print ordered list of Item objects to stdout.
        """
    
    @property
    def unused_classes(self):  # -> list[Any]:
        ...
    
    @property
    def unused_funcs(self):  # -> list[Any]:
        ...
    
    @property
    def unused_imports(self):  # -> list[Any]:
        ...
    
    @property
    def unused_methods(self):  # -> list[Any]:
        ...
    
    @property
    def unused_props(self):  # -> list[Any]:
        ...
    
    @property
    def unused_vars(self):  # -> list[Any]:
        ...
    
    @property
    def unused_attrs(self):  # -> list[Any]:
        ...
    
    def visit_arg(self, node):  # -> None:
        """Function argument"""
    
    def visit_AsyncFunctionDef(self, node):  # -> None:
        ...
    
    def visit_Attribute(self, node):  # -> None:
        ...
    
    def visit_BinOp(self, node):  # -> None:
        """Parse variable names in old format strings:

        "%(my_var)s" % locals()
        """
    
    def visit_Call(self, node):  # -> None:
        ...
    
    def visit_ClassDef(self, node):  # -> None:
        ...
    
    def visit_FunctionDef(self, node):  # -> None:
        ...
    
    def visit_Import(self, node):  # -> None:
        ...
    
    def visit_ImportFrom(self, node):  # -> None:
        ...
    
    def visit_Name(self, node):  # -> None:
        ...
    
    def visit_Assign(self, node):  # -> None:
        ...
    
    def visit_MatchClass(self, node):  # -> None:
        ...
    
    def visit(self, node):  # -> None:
        ...
    
    def generic_visit(self, node):  # -> None:
        """Called if no explicit visitor function exists for a node."""
    
def main():
    ...
