

import ast
from collections.abc import Callable

class Reachability:
    def __init__(self, report: Callable[..., None]) -> None: ...
    def visit(self, node: ast.AST) -> None: ...
    def reset(self) -> None: ...
