"""This type stub file was generated by pyright.
"""

class Reachability:
    def __init__(self, report) -> None:
        ...
    
    def visit(self, node):  # -> None:
        """When called, all children of this node have already been visited."""
    
    def reset(self):  # -> None:
        ...
