
import ast
from enum import IntEnum
from pathlib import Path

class VultureInputException(Exception): ...

class ExitCode(IntEnum):
    NoDeadCode = 0
    InvalidInput = 1
    InvalidCmdlineArguments = 2
    DeadCode = 3

def condition_is_always_false(condition: ast.expr) -> bool: ...
def condition_is_always_true(condition: ast.expr) -> bool: ...
def is_ast_string(node: ast.expr) -> bool: ...
def format_path(path: Path) -> Path: ...
def get_decorator_name(decorator: ast.expr) -> str: ...
def get_modules(paths: list[str] | list[Path]) -> list[Path]: ...
def read_file(filename: str | Path) -> str: ...

class LoggingList(list[object]):
    typ: str
    def __init__(self, typ: str, verbose: bool) -> None: ...
    def append(self, item: object) -> None: ...

class LoggingSet(set[str]):
    typ: str
    def __init__(self, typ: str, verbose: bool) -> None: ...
    def add(self, name: str) -> None: ...
