"""This type stub file was generated by pyright.
"""

from enum import IntEnum

class VultureInputException(Exception):
    ...

class ExitCode(IntEnum):
    NoDeadCode = ...
    InvalidInput = ...
    InvalidCmdlineArguments = ...
    DeadCode = ...

def condition_is_always_false(condition):  # -> bool:
    ...

def condition_is_always_true(condition):  # -> bool | Any:
    ...

def is_ast_string(node):  # -> bool:
    ...

def format_path(path):
    ...

def get_decorator_name(decorator):  # -> LiteralString:
    ...

def get_modules(paths):  # -> list[Any]:
    """Retrieve Python files to check.

    Loop over all given paths, abort if any ends with .pyc, add the other given
    files (even those not ending with .py) and collect all .py files under the
    given directories.

    """

def read_file(filename):  # -> str:
    ...

class LoggingList(list):
    def __init__(self, typ, verbose) -> None:
        ...
    
    def append(self, item):  # -> None:
        ...
    
class LoggingSet(set):
    def __init__(self, typ, verbose) -> None:
        ...
    
    def add(self, name):  # -> None:
        ...
