from typing import TYPE_CHECKING, Any

from pydantic.v1.typing import CallableGenerator, ReprArgs
from pydantic.v1.utils import Representation

"""
Color definitions are  used as per CSS3 specification:
http://www.w3.org/TR/css3-color/#svg-color

A few colors have multiple names referring to the sames colors, eg. `grey` and `gray` or `aqua` and `cyan`.

In these cases the LAST color when sorted alphabetically takes preferences,
eg. Color((0, 255, 255)).as_named() == 'cyan' because "cyan" comes after "aqua".
"""
if TYPE_CHECKING: ...
type ColorTuple = tuple[int, int, int] | tuple[int, int, int, float]
type ColorType = ColorTuple | str
type HslColorTuple = tuple[float, float, float] | tuple[float, float, float, float]

class RGBA:
    __slots__ = ...
    def __init__(self, r: float, g: float, b: float, alpha: float | None) -> None: ...
    def __getitem__(self, item: Any) -> Any: ...

r_hex_short = ...
r_hex_long = ...
_r_255 = ...
_r_comma = ...
r_rgb = ...
_r_alpha = ...
r_rgba = ...
_r_h = ...
_r_sl = ...
r_hsl = ...
r_hsla = ...
repeat_colors = ...
rads = ...

class Color(Representation):
    __slots__ = ...
    def __init__(self, value: ColorType) -> None: ...
    @classmethod
    def __modify_schema__(cls, field_schema: dict[str, Any]) -> None: ...
    def original(self) -> ColorType: ...
    def as_named(self, *, fallback: bool = ...) -> str: ...
    def as_hex(self) -> str: ...
    def as_rgb(self) -> str: ...
    def as_rgb_tuple(self, *, alpha: bool | None = ...) -> ColorTuple: ...
    def as_hsl(self) -> str: ...
    def as_hsl_tuple(self, *, alpha: bool | None = ...) -> HslColorTuple: ...
    @classmethod
    def __get_validators__(cls) -> CallableGenerator: ...
    def __repr_args__(self) -> ReprArgs: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

def parse_tuple(value: tuple[Any, ...]) -> RGBA: ...
def parse_str(value: str) -> RGBA: ...
def ints_to_rgba(
    r: int | str, g: int | str, b: int | str, alpha: float | None
) -> RGBA: ...
def parse_color_value(value: int | str, max_val: int = ...) -> float: ...
def parse_float_alpha(value: None | str | float) -> float | None: ...
def parse_hsl(
    h: str, h_units: str, sat: str, light: str, alpha: float | None = ...
) -> RGBA: ...
def float_to_255(c: float) -> int: ...

COLORS_BY_NAME = ...
COLORS_BY_VALUE = ...
