import ast
import dataclasses
import enum
import types
from collections.abc import Iterator, Mapping, Sequence
from typing import Literal, NoReturn, Protocol, overload

r"""Evaluate match expressions, as used by `-k` and `-m`.

The grammar is:

expression: expr? EOF
expr:       and_expr ('or' and_expr)*
and_expr:   not_expr ('and' not_expr)*
not_expr:   'not' not_expr | '(' expr ')' | ident kwargs?

ident:      (\w|:|\+|-|\.|\[|\]|\\|/)+
kwargs:     ('(' name '=' value ( ', ' name '=' value )*  ')')
name:       a valid ident, but not a reserved keyword
value:      (unescaped) string literal | (-)?[0-9]+ | 'False' | 'True' | 'None'

The semantics are:

- Empty expression evaluates to False.
- ident evaluates to True or False according to a provided matcher function.
- or/and/not evaluate according to the usual boolean semantics.
- ident with parentheses and keyword arguments evaluates to True or False according to a provided matcher function.
"""
__all__ = ["Expression", "ParseError"]

class TokenType(enum.Enum):
    LPAREN = ...
    RPAREN = ...
    OR = ...
    AND = ...
    NOT = ...
    IDENT = ...
    EOF = ...
    EQUAL = ...
    STRING = ...
    COMMA = ...

@dataclasses.dataclass(frozen=True)
class Token:
    __slots__ = ...
    type: TokenType
    value: str
    pos: int

class ParseError(Exception):
    def __init__(self, column: int, message: str) -> None: ...

class Scanner:
    __slots__ = ...
    def __init__(self, input: str) -> None: ...
    def lex(self, input: str) -> Iterator[Token]: ...
    @overload
    def accept(self, type: TokenType, *, reject: Literal[True]) -> Token: ...
    @overload
    def accept(
        self, type: TokenType, *, reject: Literal[False] = ...
    ) -> Token | None: ...
    def accept(self, type: TokenType, *, reject: bool = ...) -> Token | None: ...
    def reject(self, expected: Sequence[TokenType]) -> NoReturn: ...

IDENT_PREFIX = ...

def expression(s: Scanner) -> ast.Expression: ...
def expr(s: Scanner) -> ast.expr: ...
def and_expr(s: Scanner) -> ast.expr: ...
def not_expr(s: Scanner) -> ast.expr: ...

BUILTIN_MATCHERS = ...

def single_kwarg(s: Scanner) -> ast.keyword: ...
def all_kwargs(s: Scanner) -> list[ast.keyword]: ...

class MatcherCall(Protocol):
    def __call__(self, name: str, /, **kwargs: str | int | bool | None) -> bool: ...

@dataclasses.dataclass
class MatcherNameAdapter:
    matcher: MatcherCall
    name: str
    def __bool__(self) -> bool: ...
    def __call__(self, **kwargs: str | int | bool | None) -> bool: ...

class MatcherAdapter(Mapping[str, MatcherNameAdapter]):
    def __init__(self, matcher: MatcherCall) -> None: ...
    def __getitem__(self, key: str) -> MatcherNameAdapter: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...

class Expression:
    __slots__ = ...
    def __init__(self, code: types.CodeType) -> None: ...
    @classmethod
    def compile(cls, input: str) -> Expression: ...
    def evaluate(self, matcher: MatcherCall) -> bool: ...
