exclude = [
    "__pycache__",
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "build",
    "dist",
    "htmlcov",
    "venv",
]
fix = true
format.docstring-code-format = true
format.indent-style = "space"
format.line-ending = "lf"
format.quote-style = "double"
line-length = 88
lint.ignore = ["D203", "D213"]
lint.isort.force-single-line = false
lint.isort.split-on-trailing-comma = true
lint.isort.combine-as-imports = true
lint.per-file-ignores."**/__init__.py" = ["F401"]
lint.per-file-ignores."**/*_pb2_grpc.py" = ["ALL"]
lint.per-file-ignores."**/*_pb2.py" = ["ALL"]
lint.per-file-ignores."**/generated/**/*.py" = ["ALL"]
lint.per-file-ignores."**/proto/*_pb2_grpc.py" = ["ALL"]
lint.per-file-ignores."**/proto/*_pb2.py" = ["ALL"]
lint.per-file-ignores."**/scripts/**" = ["EXE001", "S603", "S607", "T201"]
lint.per-file-ignores."**/tests/**" = [
    "ARG",
    "PLC0415",
    "PLR2004",
    "S101",
    "S103",
    "S104",
    "S105",
    "S106",
    "S107",
    "S112",
    "SLF001",
]
lint.select = ["ALL"]
respect-gitignore = true
show-fixes = true
src = ["exemples", "scripts", "src", "tests"]
target-version = "py313"
