exclude = [
    "__pycache__",
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "archive",
    "backup",
    "build",
    "dist",
    "htmlcov",
    "temp-backup",
    "venv",
]
fix = true
format.docstring-code-format = true
format.indent-style = "space"
format.line-ending = "lf"
format.quote-style = "double"
line-length = 88
lint.ignore = [
    "BLE001", 
    "B017",
    "COM812",
    "D107",
    "D203",
    "D213",
    "D400",
    "D401",
    "ERA001",  # False positives on legitimate comments
    "G004",
    "RUF100",
    "SLF001",
    "TRY300",
]
lint.isort.force-single-line = false
lint.isort.split-on-trailing-comma = true
lint.isort.combine-as-imports = true
# lint.per-file-ignores."**/__init__.py" = ["F401"]
lint.per-file-ignores."**/*_pb2_grpc.py" = ["ALL"]
lint.per-file-ignores."**/*_pb2.py" = ["ALL"]
lint.per-file-ignores."**/generated/**/*.py" = ["ALL"]
lint.per-file-ignores."**/proto/*_pb2_grpc.py" = ["ALL"]
lint.per-file-ignores."**/proto/*_pb2.py" = ["ALL"]
lint.per-file-ignores."**/examples/**" = [
    "BLE001", 
    "COM812",
    "D203",
    "D213",
    "D400",
    "D401",
    "G004",
    "SLF001",
    "TRY300",
    "C901",
    "D107",
    "EXE001",
    "G004",
    "N999",
    "SLF001",
    "T201",
    "TRY300",
]
lint.per-file-ignores."**/scripts/**" = [
    "BLE001", 
    "COM812",
    "D203",
    "D213",
    "D400",
    "D401",
    "G004",
    "SLF001",
    "TRY300",
    "C901",
    "D",
    "EXE001",
    "G004",
    "N999",
    "PLR0911",
    "PLR0912",
    "PLR0915",
    "PLR2004",
    "S107",
    "SLF001",
    "T201",
    "TRY300",
]
lint.per-file-ignores."**/tests/**" = [
    "ARG",
    "BLE001", 
    "COM812",
    "D",
    "D203",
    "D213",
    "D400",
    "D401",
    "E501",
    "EM102",
    "G004",
    "G004",
    "PLC0415",
    "PLR0912",
    "PLR2004",
    "S101",
    "S103",
    "S104",
    "S105",
    "S106",
    "S107",
    "S112",
    "SLF001",
    "SLF001",
    "TRY003",
    "TRY300",
    
]
lint.select = ["ALL"]
respect-gitignore = true
show-fixes = true
src = ["exemples", "scripts", "src", "tests"]
target-version = "py313"
