[ldap-core-shared-cACBB_Ip]
minor = "3.13"
patch = "3.13.3"

[flext-target-oracle-Y3PGgkda]
minor = "3.13"
patch = "3.13.3"

[gruponos-meltano-native-aU1PHgta]
minor = "3.12"
patch = "3.12.10"

[flext-OX9jaBUq]
minor = "3.13"
patch = "3.13.5"
