[mypy]
check_untyped_defs = true
disable_error_code = no-any-return, unused-ignore, truthy-function, misc
disallow_any_generics = false
disallow_incomplete_defs = true
disallow_untyped_decorators = false
disallow_untyped_defs = true
no_implicit_optional = true
no_implicit_reexport = true
python_version = 3.13
strict_equality = true
strict_optional = true
warn_redundant_casts = true
warn_return_any = false
warn_unused_ignores = false
namespace_packages = true

[mypy.plugins.pydantic.*]
init_forbid_extra = True
init_typed = True
warn_required_dynamic_aliases = True
warn_untyped_fields = True

[mypy-ldap3.*]
ignore_missing_imports = True

[mypy-responses.*,pluggy.*,typer.*,rich.*,structlog.*,opentelemetry.*,psutil.*,setuptools.*,pytest_benchmark.*]
ignore_missing_imports = True

[mypy-src.dc_api_x.ext.auth.ldap]
disallow_untyped_calls = False

# Configurações mais permissivas para arquivos de teste
[mypy-*/tests/*]
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = false

[mypy-*/temp/*]
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = false 
