from typing import Any

"""
greenlet-specific code that pretends to be a `internal.invalid`.

Fails to import if not running under greenlet.
"""

class GreenThreadLocal:
    def __init__(self) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, val: Any) -> None: ...
    def __delattr__(self, name: str) -> None: ...
