from collections.abc import Iterable
from typing import TYPE_CHECKING, Final

from . import PydanticPluginProtocol

if TYPE_CHECKING: ...
PYDANTIC_ENTRY_POINT_GROUP: Final[str] = ...
_plugins: dict[str, PydanticPluginProtocol] | None = ...
_loading_plugins: bool = ...

def get_plugins() -> Iterable[PydanticPluginProtocol]: ...
