import ast
import types
from collections.abc import Iterable, Iterator
from typing import overload

class Source:
    def __init__(self, obj: object = ...) -> None: ...
    def __eq__(self, other: object) -> bool: ...

    __hash__ = ...
    @overload
    def __getitem__(self, key: int) -> str: ...
    @overload
    def __getitem__(self, key: slice) -> Source: ...
    def __getitem__(self, key: int | slice) -> str | Source: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def strip(self) -> Source: ...
    def indent(self, indent: str = ...) -> Source: ...
    def getstatement(self, lineno: int) -> Source: ...
    def getstatementrange(self, lineno: int) -> tuple[int, int]: ...
    def deindent(self) -> Source: ...

def findsource(obj) -> tuple[Source | None, int]: ...
def getrawcode(obj: object, trycall: bool = ...) -> types.CodeType: ...
def deindent(lines: Iterable[str]) -> list[str]: ...
def get_statement_startend2(lineno: int, node: ast.AST) -> tuple[int, int | None]: ...
def getstatementrange_ast(
    lineno: int, source: Source, assertion: bool = ..., astnode: ast.AST | None = ...
) -> tuple[ast.AST, int, int]: ...
