from collections.abc import Callable, Mapping
from typing import Any, TypeVar, final, overload

T_Attr = TypeVar("T_Attr")
T_Default = TypeVar("T_Default")
undefined = ...

def typed_attribute() -> Any: ...

class TypedAttributeSet:
    def __init_subclass__(cls) -> None: ...

class TypedAttributeProvider:
    @property
    def extra_attributes(self) -> Mapping[T_Attr, Callable[[], T_Attr]]: ...
    @overload
    def extra(self, attribute: T_Attr) -> T_Attr: ...
    @overload
    def extra(self, attribute: T_Attr, default: T_Default) -> T_Attr | T_Default: ...
    @final
    def extra(self, attribute: Any, default: object = ...) -> object: ...
