from abc import ABC, abstractmethod
from typing import Any, ClassVar, TypeVar

"""Resources module."""
T = TypeVar("T")

class Resource[T](ABC):
    __slots__: ClassVar[tuple[str, ...]] = ...
    obj: T | None
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @abstractmethod
    def init(self, *args: Any, **kwargs: Any) -> T | None: ...
    def shutdown(self, resource: T | None) -> None: ...
    def __enter__(self) -> T | None: ...
    def __exit__(self, *exc_info: object) -> None: ...

class AsyncResource[T](ABC):
    __slots__: ClassVar[tuple[str, ...]] = ...
    obj: T | None
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @abstractmethod
    async def init(self, *args: Any, **kwargs: Any) -> T | None: ...
    async def shutdown(self, resource: T | None) -> None: ...
    async def __aenter__(self) -> T | None: ...
    async def __aexit__(self, *exc_info: object) -> None: ...
