"""
This type stub file was generated by pyright.
"""

'''This module contains the main() function, which is the entry point for the
command line interface.'''
__version__ = ...
def main(): # -> None:
    '''The entry point for Setuptools.'''
    ...

if __name__ == '__main__':
    ...
