"""This type stub file was generated by pyright.
"""

import ast

"""This module contains the ComplexityVisitor class which is where all the
analysis concerning Cyclomatic Complexity is done. There is also the class
HalsteadVisitor, that counts Halstead metrics."""
GET_COMPLEXITY = ...
GET_REAL_COMPLEXITY = ...
NAMES_GETTER = ...
GET_ENDLINE = ...
BaseFunc = ...
BaseClass = ...
def code2ast(source):  # -> Module:
    """Convert a string object into an AST object.

    This function is retained for backwards compatibility, but it no longer
    attemps any conversions. It's equivalent to a call to ``ast.parse``.
    """

class Function(BaseFunc):
    """Object represeting a function block."""

    @property
    def letter(self):  # -> Literal['M', 'F']:
        """The letter representing the function. It is `M` if the function is
        actually a method, `F` otherwise.
        """
    
    @property
    def fullname(self):  # -> str:
        """The full name of the function. If it is a method, then the full name
        is:
                {class name}.{method name}
        Otherwise it is just the function name.
        """
    
class Class(BaseClass):
    """Object representing a class block."""

    letter = ...
    @property
    def fullname(self):
        """The full name of the class. It is just its name. This attribute
        exists for consistency (see :data:`Function.fullname`).
        """
    
    @property
    def complexity(self):  # -> int:
        """The average complexity of the class. It corresponds to the average
        complexity of its methods plus one.
        """
    
class CodeVisitor(ast.NodeVisitor):
    """Base class for every NodeVisitors in `radon.visitors`. It implements a
    couple utility class methods and a static method.
    """

    @staticmethod
    def get_name(obj):
        """Shorthand for ``obj.__class__.__name__``."""
    
    @classmethod
    def from_code(cls, code, **kwargs):  # -> Self:
        """Instanciate the class from source code (string object). The
        `**kwargs` are directly passed to the `ast.NodeVisitor` constructor.
        """
    
    @classmethod
    def from_ast(cls, ast_node, **kwargs):  # -> Self:
        """Instantiate the class from an AST node. The `**kwargs` are
        directly passed to the `ast.NodeVisitor` constructor.
        """
    
class ComplexityVisitor(CodeVisitor):
    """A visitor that keeps track of the cyclomatic complexity of
    the elements.

    :param to_method: If True, every function is treated as a method. In this
        case the *classname* parameter is used as class name.
    :param classname: Name of parent class.
    :param off: If True, the starting value for the complexity is set to 1,
        otherwise to 0.
    """

    def __init__(self, to_method=..., classname=..., off=..., no_assert=...) -> None:
        ...
    
    @property
    def functions_complexity(self):  # -> int:
        """The total complexity from all functions (i.e. the total number of
        decision points + 1).

        This is *not* the sum of all the complexity from the functions. Rather,
        it's the complexity of the code *inside* all the functions.
        """
    
    @property
    def classes_complexity(self):  # -> int:
        """The total complexity from all classes (i.e. the total number of
        decision points + 1).
        """
    
    @property
    def total_complexity(self):  # -> int:
        """The total complexity. Computed adding up the visitor complexity, the
        functions complexity, and the classes complexity.
        """
    
    @property
    def blocks(self):  # -> list[Any]:
        """All the blocks visited. These include: all the functions, the
        classes and their methods. The returned list is not sorted.
        """
    
    @property
    def max_line(self):  # -> float:
        """The maximum line number among the analyzed lines."""
    
    @max_line.setter
    def max_line(self, value):  # -> None:
        """The maximum line number among the analyzed lines."""
    
    def generic_visit(self, node):  # -> None:
        """Main entry point for the visitor."""
    
    def visit_Assert(self, node):  # -> None:
        """When visiting `assert` statements, the complexity is increased only
        if the `no_assert` attribute is `False`.
        """
    
    def visit_AsyncFunctionDef(self, node):  # -> None:
        """Async function definition is the same thing as the synchronous
        one.
        """
    
    def visit_FunctionDef(self, node):  # -> None:
        """When visiting functions a new visitor is created to recursively
        analyze the function's body.
        """
    
    def visit_ClassDef(self, node):  # -> None:
        """When visiting classes a new visitor is created to recursively
        analyze the class' body and methods.
        """
    
class HalsteadVisitor(CodeVisitor):
    """Visitor that keeps track of operators and operands, in order to compute
    Halstead metrics (see :func:`radon.metrics.h_visit`).
    """

    types = ...
    def __init__(self, context=...) -> None:
        """*context* is a string used to keep track the analysis' context."""
    
    @property
    def distinct_operators(self):  # -> int:
        """The number of distinct operators."""
    
    @property
    def distinct_operands(self):  # -> int:
        """The number of distinct operands."""
    
    def dispatch(meth):  # -> Callable[..., None]:
        """This decorator does all the hard work needed for every node.

        The decorated method must return a tuple of 4 elements:

            * the number of operators
            * the number of operands
            * the operators seen (a sequence)
            * the operands seen (a sequence)
        """
    
    @dispatch
    def visit_BinOp(self, node):  # -> tuple[Literal[1], Literal[2], tuple[Any], tuple[expr, expr]]:
        """A binary operator."""
    
    @dispatch
    def visit_UnaryOp(self, node):  # -> tuple[Literal[1], Literal[1], tuple[Any], tuple[expr]]:
        """A unary operator."""
    
    @dispatch
    def visit_BoolOp(self, node):  # -> tuple[Literal[1], int, tuple[Any], list[expr]]:
        """A boolean operator."""
    
    @dispatch
    def visit_AugAssign(self, node):  # -> tuple[Literal[1], Literal[2], tuple[Any], tuple[Name | Attribute | Subscript, expr]]:
        """An augmented assign (contains an operator)."""
    
    @dispatch
    def visit_Compare(self, node):  # -> tuple[int, int, map[Any], list[expr]]:
        """A comparison."""
    
    def visit_FunctionDef(self, node):  # -> None:
        """When visiting functions, another visitor is created to recursively
        analyze the function's body. We also track information on the function
        itself.
        """
    
    def visit_AsyncFunctionDef(self, node):  # -> None:
        """Async functions are similar to standard functions, so treat them as
        such.
        """
