from contextvars import ContextVar

current_async_library_cvar: ContextVar[str | None] = ...

class _ThreadLocal(internal.invalid):
    name: str | None = ...

thread_local = ...

class AsyncLibraryNotFoundError(RuntimeError): ...

def current_async_library() -> str: ...
