"""This type stub file was generated by pyright.
"""

import sys

"""This module holds the base Harvester class and all its subclassess."""
if sys.version_info[0] < 3:
    ...
SUPPORTS_IPYNB = ...
class Harvester:
    """Base class defining the interface of a Harvester object.

    A Harvester has the following lifecycle:

    1. **Initialization**: `h = Harvester(paths, config)`

    2. **Execution**: `r = h.results`. `results` holds an iterable object.
       The first time `results` is accessed, `h.run()` is called. This method
       should not be subclassed. Instead, the :meth:`gobble` method should be
       implemented.

    3. **Reporting**: the methods *as_json* and *as_xml* return a string
       with the corrisponding format. The method *to_terminal* is a generator
       that yields the lines to be printed in the terminal.

    This class is meant to be subclasses and cannot be used directly, since
    the methods :meth:`gobble`, :meth:`as_xml` and :meth:`to_terminal` are
    not implemented.
    """

    def __init__(self, paths, config) -> None:
        """Initialize the Harvester.

        *paths* is a list of paths to analyze.
        *config* is a :class:`~radon.cli.Config` object holding the
        configuration values specific to the Harvester.
        """
    
    def gobble(self, fobj):
        """Subclasses must implement this method to define behavior.

        This method is called for every file to analyze. *fobj* is the file
        object. This method should return the results from the analysis,
        preferably a dictionary.
        """
    
    def run(self):  # -> Generator[tuple[Any | Literal['-'], Any] | tuple[str, Any] | tuple[Any | Literal['-'], dict[str, str]], Any, None]:
        """Start the analysis. For every file, this method calls the
        :meth:`gobble` method. Results are yielded as tuple:
        ``(filename, analysis_results)``.
        """
    
    @property
    def results(self):  # -> list[Any] | Generator[tuple[Any | Literal['-'], Any] | tuple[str, Any] | tuple[Any | Literal['-'], dict[str, str]], Any, None]:
        """This property holds the results of the analysis.

        The first time it is accessed, an iterator is returned. Its
        elements are cached into a list as it is iterated over. Therefore, if
        `results` is accessed multiple times after the first one, a list will
        be returned.
        """
    
    def as_json(self):  # -> str:
        """Format the results as JSON."""
    
    def as_xml(self):
        """Format the results as XML."""
    
    def as_md(self):
        """Format the results as Markdown."""
    
    def as_codeclimate_issues(self):
        """Format the results as Code Climate issues."""
    
    def to_terminal(self):
        """Yields tuples representing lines to be printed to a terminal.

        The tuples have the following format: ``(line, args, kwargs)``.
        The line is then formatted with `line.format(*args, **kwargs)`.
        """
    
class CCHarvester(Harvester):
    """A class that analyzes Python modules' Cyclomatic Complexity."""

    def gobble(self, fobj):  # -> list[Any]:
        """Analyze the content of the file object."""
    
    def as_json(self):  # -> str:
        """Format the results as JSON."""
    
    def as_xml(self):  # -> str:
        """Format the results as XML. This is meant to be compatible with
        Jenkin's CCM plugin. Therefore not all the fields are kept.
        """
    
    def as_md(self):  # -> str:
        """Format the results as Markdown."""
    
    def as_codeclimate_issues(self):  # -> list[Any]:
        """Format the result as Code Climate issues."""
    
    def to_terminal(self):  # -> Generator[tuple[Any | str, tuple[Any | str], dict[str, bool]] | tuple[Any | str, tuple[()], dict[Any, Any]] | tuple[list[Any], tuple[()], dict[str, int]] | tuple[LiteralString, tuple[int], dict[Any, Any]] | tuple[Literal['Average complexity: {0}{1} ({2}){3}'], tuple[str, str, float | Any, str], dict[Any, Any]], Any, None]:
        """Yield lines to be printed in a terminal."""
    
class RawHarvester(Harvester):
    """A class that analyzes Python modules' raw metrics."""

    headers = ...
    def gobble(self, fobj):  # -> dict[Any, Any]:
        """Analyze the content of the file object."""
    
    def as_xml(self):
        """Placeholder method. Currently not implemented."""
    
    def to_terminal(self):  # -> Generator[tuple[Any | str, tuple[Any | str], dict[str, bool]] | tuple[Any | str, tuple[()], dict[Any, Any]] | tuple[Literal['{0}: {1}'], tuple[str, Any | str], dict[str, int]] | tuple[Literal['- Comment Stats'], tuple[()], dict[str, int]] | tuple[Literal['(C % L): {0:.0%}'], tuple[Any], dict[str, int]] | tuple[Literal['(C % S): {0:.0%}'], tuple[Any], dict[str, int]] | tuple[Literal['(C + M % L): {0:.0%}'], tuple[Any], dict[str, int]] | tuple[Literal['** Total **'], tuple[()], dict[Any, Any]] | tuple[Literal['{0}: {1}'], tuple[str, int], dict[str, int]] | tuple[Literal['(C % L): {0:.0%}'], tuple[float], dict[str, int]] | tuple[Literal['(C % S): {0:.0%}'], tuple[float], dict[str, int]] | tuple[Literal['(C + M % L): {0:.0%}'], tuple[float], dict[str, int]], Any, None]:
        """Yield lines to be printed to a terminal."""
    
class MIHarvester(Harvester):
    """A class that analyzes Python modules' Maintainability Index."""

    def gobble(self, fobj):  # -> dict[str, Any]:
        """Analyze the content of the file object."""
    
    @property
    def filtered_results(self):  # -> Generator[tuple[Any | str, Any | dict[str, str]], Any, None]:
        """Filter results with respect with their rank."""
    
    def as_json(self):  # -> str:
        """Format the results as JSON."""
    
    def as_xml(self):
        """Placeholder method. Currently not implemented."""
    
    def to_terminal(self):  # -> Generator[tuple[Any, tuple[Any], dict[str, bool]] | tuple[Literal['{0} - {1}{2}{3}{4}'], tuple[Any, str, Any, str, str], dict[Any, Any]], Any, None]:
        """Yield lines to be printed to a terminal."""
    
class HCHarvester(Harvester):
    """Computes the Halstead Complexity of Python modules."""

    def __init__(self, paths, config) -> None:
        ...
    
    def gobble(self, fobj):  # -> Halstead:
        """Analyze the content of the file object."""
    
    def as_json(self):  # -> str:
        """Format the results as JSON."""
    
    def to_terminal(self):  # -> Generator[tuple[str, tuple[()], dict[Any, Any]] | tuple[str, tuple[()], dict[str, int]], Any, None]:
        """Yield lines to be printed to the terminal."""
    
def hal_report_to_terminal(report, base_indent=...):  # -> Generator[tuple[str, tuple[()], dict[str, int]], Any, None]:
    """Yield lines from the HalsteadReport to print to the terminal."""
