"""
This type stub file was generated by pyright.
"""

import platform

'''This module contains various utility functions used in the CLI interface.
Attributes:
    _encoding (str): encoding with all files will be opened. Configured by
    environment variable RADONFILESENCODING
'''
SUPPORTS_IPYNB = ...
if platform.python_implementation() == 'PyPy':
    ...
else:
    _encoding = ...
def iter_filenames(paths, exclude=..., ignore=...): # -> Generator[Any | Literal['-'], Any, None]:
    '''A generator that yields all sub-paths of the ones specified in
    `paths`. Optional `exclude` filters can be passed as a comma-separated
    string of regexes, while `ignore` filters are a comma-separated list of
    directory names to ignore. Ignore patterns are can be plain names or glob
    patterns. If paths contains only a single hyphen, stdin is implied,
    returned as is.
    '''
    ...

def explore_directories(start, exclude, ignore): # -> Generator[Any, Any, None]:
    '''Explore files and directories under `start`. `explore` and `ignore`
    arguments are the same as in :func:`iter_filenames`.
    '''
    ...

def filter_out(strings, patterns): # -> Generator[Any, Any, None]:
    '''Filter out any string that matches any of the specified patterns.'''
    ...

def cc_to_dict(obj): # -> dict[str, str]:
    '''Convert an object holding CC results into a dictionary. This is meant
    for JSON dumping.'''
    ...

def raw_to_dict(obj): # -> dict[Any, Any]:
    '''Convert an object holding raw analysis results into a dictionary. This
    is meant for JSON dumping.'''
    ...

def dict_to_xml(results): # -> str:
    '''Convert a dictionary holding CC analysis result into a string containing
    xml.'''
    ...

def dict_to_md(results): # -> str:
    ...

def dict_to_codeclimate_issues(results, threshold=...): # -> list[Any]:
    '''Convert a dictionary holding CC analysis results into Code Climate
     issue json.'''
    ...

def cc_to_terminal(results, show_complexity, min, max, total_average): # -> tuple[list[Any], float | Any, int]:
    '''Transfom Cyclomatic Complexity results into a 3-elements tuple:

        ``(res, total_cc, counted)``

    `res` is a list holding strings that are specifically formatted to be
    printed to a terminal.
    `total_cc` is a number representing the total analyzed cyclomatic
    complexity.
    `counted` holds the number of the analyzed blocks.

    If *show_complexity* is `True`, then the complexity of a block will be
    shown in the terminal line alongside its rank.
    *min* and *max* are used to control which blocks are shown in the resulting
    list. A block is formatted only if its rank is `min <= rank <= max`.
    If *total_average* is `True`, the `total_cc` and `counted` count every
    block, regardless of the fact that they are formatted in `res` or not.
    '''
    ...

def format_cc_issue(path, description, content, category, beginline, endline, remediation_points, fingerprint): # -> str:
    '''Return properly formatted Code Climate issue json.'''
    ...

def get_remediation_points(complexity, grade_threshold): # -> Literal[0]:
    '''Calculate quantity of remediation work needed to reduce complexity to grade
    threshold permitted.'''
    ...

def get_content(): # -> str:
    '''Return explanation string for Code Climate issue document.'''
    ...

def get_fingerprint(path, additional_parts): # -> str:
    '''Return fingerprint string for Code Climate issue document.'''
    ...

def strip_ipython(code): # -> LiteralString:
    ...

