class Shrinker:
    def __init__(
        self, initial, predicate, *, full=..., debug=..., name=..., **kwargs
    ) -> None: ...
    @property
    def calls(self) -> int: ...
    def setup(self, **kwargs):  # -> None:
        ...
    def delegate(self, other_class, convert_to, convert_from, **kwargs):  # -> None:
        ...
    def call_shrinker(self, other_class, initial, predicate, **kwargs): ...
    def debug(self, *args: object) -> None: ...
    @classmethod
    def shrink(cls, initial, predicate, **kwargs): ...
    def run(self):  # -> None:
        ...
    def consider(self, value):  # -> bool:
        ...
    def make_canonical(self, value): ...
    def make_immutable(self, value): ...
    def check_invariants(self, value):  # -> None:
        ...
    def short_circuit(self):  # -> Literal[False]:
        ...
    def left_is_better(self, left, right): ...
    def run_step(self): ...
