import ctypes
from ctypes.wintypes import HANDLE
from dataclasses import dataclass
from typing import TYPE_CHECKING

""":module: watchdog.observers.winapi
:synopsis: Windows API-Python interface (removes dependency on ``pywin32``).
:author: theller@ctypes.org (Thomas Heller)
:author: will@willmcgugan.com (Will McGugan)
:author: ryan@rfk.id.au (Ryan Kelly)
:author: yesudeep@gmail.com (Yesudeep Mangalapilly)
:author: thomas.amland@gmail.com (Thomas Amland)
:author: contact@tiger-222.fr (Mickaël Schoentgen)
:platforms: windows
"""
if TYPE_CHECKING: ...
INVALID_HANDLE_VALUE = ...
FILE_NOTIFY_CHANGE_FILE_NAME = ...
FILE_NOTIFY_CHANGE_DIR_NAME = ...
FILE_NOTIFY_CHANGE_ATTRIBUTES = ...
FILE_NOTIFY_CHANGE_SIZE = ...
FILE_NOTIFY_CHANGE_LAST_WRITE = ...
FILE_NOTIFY_CHANGE_LAST_ACCESS = ...
FILE_NOTIFY_CHANGE_CREATION = ...
FILE_NOTIFY_CHANGE_SECURITY = ...
FILE_FLAG_BACKUP_SEMANTICS = ...
FILE_FLAG_OVERLAPPED = ...
FILE_LIST_DIRECTORY = ...
FILE_SHARE_READ = ...
FILE_SHARE_WRITE = ...
FILE_SHARE_DELETE = ...
OPEN_EXISTING = ...
VOLUME_NAME_NT = ...
FILE_ACTION_CREATED = ...
FILE_ACTION_DELETED = ...
FILE_ACTION_MODIFIED = ...
FILE_ACTION_RENAMED_OLD_NAME = ...
FILE_ACTION_RENAMED_NEW_NAME = ...
FILE_ACTION_DELETED_SELF = ...
FILE_ACTION_OVERFLOW = ...
FILE_ACTION_ADDED = ...
FILE_ACTION_REMOVED = ...
FILE_ACTION_REMOVED_SELF = ...
THREAD_TERMINATE = ...
WAIT_ABANDONED = ...
WAIT_IO_COMPLETION = ...
WAIT_OBJECT_0 = ...
WAIT_TIMEOUT = ...
ERROR_OPERATION_ABORTED = ...

class OVERLAPPED(ctypes.Structure):
    _fields_ = ...

kernel32 = ...
ReadDirectoryChangesW = ...
CreateFileW = ...
CloseHandle = ...
CancelIoEx = ...
CreateEvent = ...
SetEvent = ...
WaitForSingleObjectEx = ...
CreateIoCompletionPort = ...
GetQueuedCompletionStatus = ...
PostQueuedCompletionStatus = ...
GetFinalPathNameByHandleW = ...

class FileNotifyInformation(ctypes.Structure):
    _fields_ = ...

LPFNI = ...
WATCHDOG_FILE_FLAGS = ...
WATCHDOG_FILE_SHARE_FLAGS = ...
WATCHDOG_FILE_NOTIFY_FLAGS = ...
BUFFER_SIZE = ...
PATH_BUFFER_SIZE = ...

def get_directory_handle(path: str) -> HANDLE: ...
def close_directory_handle(handle: HANDLE) -> None: ...
def read_directory_changes(
    handle: HANDLE, path: str, *, recursive: bool
) -> tuple[bytes, int]: ...

@dataclass(unsafe_hash=True)
class WinAPINativeEvent:
    action: int
    src_path: str
    @property
    def is_added(self) -> bool: ...
    @property
    def is_removed(self) -> bool: ...
    @property
    def is_modified(self) -> bool: ...
    @property
    def is_renamed_old(self) -> bool: ...
    @property
    def is_renamed_new(self) -> bool: ...
    @property
    def is_removed_self(self) -> bool: ...

def read_events(
    handle: HANDLE, path: str, *, recursive: bool
) -> list[WinAPINativeEvent]: ...
