"""Type stubs for bandit.core.config module."""

from __future__ import annotations

import logging

LOG: logging.Logger

class BanditConfig:
    config_file: str | None

    def __init__(self, config_file: str | None = ...) -> None: ...
    def get_option(self, option_string: str) -> object: ...
    def get_setting(self, setting_name: str) -> object: ...
    @property
    def config(self) -> dict[str, object]: ...
    def convert_legacy_config(self) -> None: ...
    def convert_names_to_ids(self) -> dict[str, dict[str, set[str]]]: ...
    def convert_legacy_blacklist_data(
        self,
    ) -> tuple[list[dict[str, object]], list[dict[str, object]]]: ...
    @staticmethod
    def convert_legacy_blacklist_tests(
        profiles: dict[str, dict[str, set[str]]],
        bad_imports: list[dict[str, object]],
        bad_calls: list[dict[str, object]],
    ) -> None: ...
    def validate(self, path: str) -> None: ...
