"""
This type stub file was generated by pyright.
"""

import sys

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11):
    ...
else:
    ...
LOG = ...
class BanditConfig:
    def __init__(self, config_file=...) -> None:
        """Attempt to initialize a config dictionary from a yaml file.

        Error out if loading the yaml file fails for any reason.
        :param config_file: The Bandit yaml config file

        :raises bandit.utils.ConfigError: If the config is invalid or
            unreadable.
        """
        ...
    
    def get_option(self, option_string):
        """Returns the option from the config specified by the option_string.

        '.' can be used to denote levels, for example to retrieve the options
        from the 'a' profile you can use 'profiles.a'
        :param option_string: The string specifying the option to retrieve
        :return: The object specified by the option_string, or None if it can't
        be found.
        """
        ...
    
    def get_setting(self, setting_name):
        ...
    
    @property
    def config(self):
        """Property to return the config dictionary

        :return: Config dictionary
        """
        ...
    
    def convert_legacy_config(self):
        ...
    
    def convert_names_to_ids(self):
        """Convert test names to IDs, unknown names are left unchanged."""
        ...
    
    def convert_legacy_blacklist_data(self):
        """Detect legacy blacklist data and convert it to new format."""
        ...
    
    @staticmethod
    def convert_legacy_blacklist_tests(profiles, bad_imports, bad_calls):
        """Detect old blacklist tests, convert to use new builtin."""
        ...
    
    def validate(self, path):
        """Validate the config data."""
        ...
    


