
import ast

class Context:
    def __init__(self, context_object: dict[str, object] | None = ...) -> None: ...
    @property
    def call_args(self) -> list[object]: ...
    @property
    def call_args_count(self) -> int | None: ...
    @property
    def call_function_name(self) -> str | None: ...
    @property
    def call_function_name_qual(self) -> str | None: ...
    @property
    def call_keywords(self) -> dict[str, object] | None: ...
    @property
    def node(self) -> ast.AST | None: ...
    @property
    def string_val(self) -> str | None: ...
    @property
    def bytes_val(self) -> bytes | None: ...
    @property
    def string_val_as_escaped_bytes(self) -> bytes | None: ...
    @property
    def statement(self) -> ast.AST | None: ...
    @property
    def function_def_defaults_qual(self) -> list[str]: ...
    def get_call_arg_value(self, argument_name: str) -> object: ...
    def check_call_arg_value(
        self, argument_name: str, argument_values: object = ...
    ) -> bool | None: ...
    def get_lineno_for_call_arg(self, argument_name: str) -> int | None: ...
    def get_call_arg_at_position(self, position_num: int) -> object: ...
    def is_module_being_imported(self, module: str) -> bool: ...
    def is_module_imported_exact(self, module: str) -> bool: ...
    def is_module_imported_like(self, module: str) -> bool: ...
    @property
    def filename(self) -> str | None: ...
    @property
    def file_data(self) -> object: ...
    @property
    def import_aliases(self) -> dict[str, str] | None: ...
