from __future__ import annotations

class Cwe:
    NOTSET: int
    IMPROPER_INPUT_VALIDATION: int
    PATH_TRAVERSAL: int
    OS_COMMAND_INJECTION: int
    XSS: int
    BASIC_XSS: int
    SQL_INJECTION: int
    CODE_INJECTION: int
    IMPROPER_WILDCARD_NEUTRALIZATION: int
    HARD_CODED_PASSWORD: int
    IMPROPER_ACCESS_CONTROL: int
    IMPROPER_CERT_VALIDATION: int
    CLEARTEXT_TRANSMISSION: int
    INADEQUATE_ENCRYPTION_STRENGTH: int
    BROKEN_CRYPTO: int
    INSUFFICIENT_RANDOM_VALUES: int
    INSECURE_TEMP_FILE: int
    UNCONTROLLED_RESOURCE_CONSUMPTION: int
    DOWNLOAD_OF_CODE_WITHOUT_INTEGRITY_CHECK: int
    DESERIALIZATION_OF_UNTRUSTED_DATA: int
    MULTIPLE_BINDS: int
    IMPROPER_CHECK_OF_EXCEPT_COND: int
    INCORRECT_PERMISSION_ASSIGNMENT: int
    INAPPROPRIATE_ENCODING_FOR_OUTPUT_CONTEXT: int
    MITRE_URL_PATTERN: str

    def __init__(self, id: int = ...) -> None: ...
    def link(self) -> str: ...
    def as_dict(self) -> dict[str, object]: ...
    def as_jsons(self) -> str: ...
    def from_dict(self, data: dict[str, object]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Issue:
    def __init__(
        self,
        severity: str,
        cwe: int = ...,
        confidence: str = ...,
        text: str = ...,
        ident: str | None = ...,
        lineno: int | None = ...,
        test_id: str = ...,
        col_offset: int = ...,
        end_col_offset: int = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def filter(self, severity: str, confidence: str) -> bool: ...
    def get_code(self, max_lines: int = ..., tabbed: bool = ...) -> str: ...
    def as_dict(
        self, with_code: bool = ..., max_lines: int = ...
    ) -> dict[str, object]: ...
    def from_dict(self, data: dict[str, object], with_code: bool = ...) -> None: ...

def cwe_from_dict(data: dict[str, object]) -> Cwe: ...
def issue_from_dict(data: dict[str, object]) -> Issue: ...
