"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
LOG = ...
NOSEC_COMMENT = ...
NOSEC_COMMENT_TESTS = ...
PROGRESS_THRESHOLD = ...
class BanditManager:
    scope = ...
    def __init__(self, config, agg_type, debug=..., verbose=..., quiet=..., profile=..., ignore_nosec=...) -> None:
        """Get logger, config, AST handler, and result store ready

        :param config: config options object
        :type config: bandit.core.BanditConfig
        :param agg_type: aggregation type
        :param debug: Whether to show debug messages or not
        :param verbose: Whether to show verbose output
        :param quiet: Whether to only show output in the case of an error
        :param profile_name: Optional name of profile to use (from cmd line)
        :param ignore_nosec: Whether to ignore #nosec or not
        :return:
        """
        ...
    
    def get_skipped(self):
        ...
    
    def get_issue_list(self, sev_level=..., conf_level=...):
        ...
    
    def populate_baseline(self, data):
        """Populate a baseline set of issues from a JSON report

        This will populate a list of baseline issues discovered from a previous
        run of bandit. Later this baseline can be used to filter out the result
        set, see filter_results.
        """
        ...
    
    def filter_results(self, sev_filter, conf_filter):
        """Returns a list of results filtered by the baseline

        This works by checking the number of results returned from each file we
        process. If the number of results is different to the number reported
        for the same file in the baseline, then we return all results for the
        file. We can't reliably return just the new results, as line numbers
        will likely have changed.

        :param sev_filter: severity level filter to apply
        :param conf_filter: confidence level filter to apply
        """
        ...
    
    def results_count(self, sev_filter=..., conf_filter=...):
        """Return the count of results

        :param sev_filter: Severity level to filter lower
        :param conf_filter: Confidence level to filter
        :return: Number of results in the set
        """
        ...
    
    def output_results(self, lines, sev_level, conf_level, output_file, output_format, template=...):
        """Outputs results from the result store

        :param lines: How many surrounding lines to show per result
        :param sev_level: Which severity levels to show (LOW, MEDIUM, HIGH)
        :param conf_level: Which confidence levels to show (LOW, MEDIUM, HIGH)
        :param output_file: File to store results
        :param output_format: output format plugin name
        :param template: Output template with non-terminal tags <N>
                         (default:  {abspath}:{line}:
                         {test_id}[bandit]: {severity}: {msg})
        :return: -
        """
        ...
    
    def discover_files(self, targets, recursive=..., excluded_paths=...):
        """Add tests directly and from a directory to the test set

        :param targets: The command line list of files and directories
        :param recursive: True/False - whether to add all files from dirs
        :return:
        """
        ...
    
    def run_tests(self):
        """Runs through all files in the scope

        :return: -
        """
        ...
    


