"""This type stub file was generated by pyright."""

"""
This type stub file was generated by pyright.
"""
LOG = ...

class BanditMetaAst:
    nodes = ...
    def __init__(self) -> None: ...
    def add_node(self, node, parent_id, depth):
        """Add a node to the AST node collection

        :param node: The AST node to add
        :param parent_id: The ID of the node's parent
        :param depth: The depth of the node
        :return: -
        """

    def __str__(self) -> str: ...
