
class Metrics:
    
    data: dict[str, dict[str, int]]
    def __init__(self) -> None: ...
    def begin(self, fname: str) -> None:
        ...
    def note_nosec(self, num: int = ...) -> None:
        ...
    def note_skipped_test(self, num: int = ...) -> None:
        ...
    def count_locs(self, lines: list[bytes]) -> None:
        ...
    def count_issues(self, scores: list[dict[str, list[int]]]) -> None: ...
    def aggregate(self) -> None:
        ...
