from __future__ import annotations

import ast
import logging

from bandit.core.meta_ast import BanditMetaAst
from bandit.core.metrics import Metrics
from bandit.core.test_set import BanditTestSet
from bandit.core.tester import BanditTester

LOG: logging.Logger

class BanditNodeVisitor:
    tester: BanditTester

    def __init__(
        self,
        fname: str,
        fdata: object,
        metaast: BanditMetaAst,
        testset: BanditTestSet,
        debug: bool,
        nosec_lines: dict[int, set[str]],
        metrics: Metrics,
    ) -> None: ...
    def visit_ClassDef(self, node: ast.AST) -> None: ...
    def visit_FunctionDef(self, node: ast.AST) -> None: ...
    def visit_Call(self, node: ast.AST) -> None: ...
    def visit_Import(self, node: ast.AST) -> None: ...
    def visit_ImportFrom(self, node: ast.AST) -> None: ...
    def visit_Constant(self, node: ast.AST) -> None: ...
    def visit_Str(self, node: ast.AST) -> None: ...
    def visit_Bytes(self, node: ast.AST) -> None: ...
    def pre_visit(self, node: ast.AST) -> bool: ...
    def visit(self, node: ast.AST) -> None: ...
    def post_visit(self, node: ast.AST) -> None: ...
    def generic_visit(self, node: ast.AST) -> None: ...
    def update_scores(self, scores: dict[str, list[int]]) -> None: ...
    def process(self, data: str) -> dict[str, list[int]]: ...
