"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
LOG = ...
class BanditTester:
    def __init__(self, testset, debug, nosec_lines, metrics) -> None:
        ...
    
    def run_tests(self, raw_context, checktype):
        """Runs all tests for a certain type of check, for example

        Runs all tests for a certain type of check, for example 'functions'
        store results in results.

        :param raw_context: Raw context dictionary
        :param checktype: The type of checks to run
        :return: a score based on the number and type of test results with
                extra metrics about nosec comments
        """
        ...
    
    @staticmethod
    def report_error(test, context, error):
        ...
    


