"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
LOG = ...
class BanditTestSet:
    def __init__(self, config, profile=...) -> None:
        ...
    
    def get_tests(self, checktype):
        """Returns all tests that are of type checktype

        :param checktype: The type of test to filter on
        :return: A list of tests which are of the specified type
        """
        ...
    


