"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
LOG = ...
def get_call_name(node, aliases):
    ...

def get_func_name(node):
    ...

def get_qual_attr(node, aliases):
    ...

def deepgetattr(obj, attr):
    """Recurses through an attribute chain to get the ultimate value."""
    ...

class InvalidModulePath(Exception):
    ...


class ConfigError(Exception):
    """Raised when the config file fails validation."""
    def __init__(self, message, config_file) -> None:
        ...
    


class ProfileNotFound(Exception):
    """Raised when chosen profile cannot be found."""
    def __init__(self, config_file, profile) -> None:
        ...
    


def warnings_formatter(message, category=..., filename=..., lineno=..., line=...):
    """Monkey patch for warnings.warn to suppress cruft output."""
    ...

def get_module_qualname_from_path(path):
    """Get the module's qualified name by analysis of the path.

    Resolve the absolute pathname and eliminate symlinks. This could result in
    an incorrect name if symlinks are used to restructure the python lib
    directory.

    Starting from the right-most directory component look for __init__.py in
    the directory component. If it exists then the directory name is part of
    the module name. Move left to the subsequent directory components until a
    directory is found without __init__.py.

    :param: Path to module file. Relative paths will be resolved relative to
            current working directory.
    :return: fully qualified module name
    """
    ...

def namespace_path_join(base, name):
    """Extend the current namespace path with an additional name

    Take a namespace path (i.e., package.module.class) and extends it
    with an additional name (i.e., package.module.class.subclass).
    This is similar to how os.path.join works.

    :param base: (String) The base namespace path.
    :param name: (String) The new name to append to the base path.
    :returns: (String) A new namespace path resulting from combination of
              base and name.
    """
    ...

def namespace_path_split(path):
    """Split the namespace path into a pair (head, tail).

    Tail will be the last namespace path component and head will
    be everything leading up to that in the path. This is similar to
    os.path.split.

    :param path: (String) A namespace path.
    :returns: (String, String) A tuple where the first component is the base
              path and the second is the last path component.
    """
    ...

def escaped_bytes_representation(b):
    """PY3 bytes need escaping for comparison with other strings.

    In practice it turns control characters into acceptable codepoints then
    encodes them into bytes again to turn unprintable bytes into printable
    escape sequences.

    This is safe to do for the whole range 0..255 and result matches
    unicode_escape on a unicode string.
    """
    ...

def calc_linerange(node):
    """Calculate linerange for subtree"""
    ...

def linerange(node):
    """Get line number range from a node."""
    ...

def concat_string(node, stop=...):
    """Builds a string from a ast.BinOp chain.

    This will build a string from a series of ast.Str nodes wrapped in
    ast.BinOp nodes. Something like "a" + "b" + "c" or "a %s" % val etc.
    The provided node can be any participant in the BinOp chain.

    :param node: (ast.Str or ast.BinOp) The node to process
    :param stop: (ast.Str or ast.BinOp) Optional base node to stop at
    :returns: (Tuple) the root node of the expression, the string value
    """
    ...

def get_called_name(node):
    """Get a function name from an ast.Call node.

    An ast.Call node representing a method call with present differently to one
    wrapping a function call: thing.call() vs call(). This helper will grab the
    unqualified call name correctly in either case.

    :param node: (ast.Call) the call node
    :returns: (String) the function name
    """
    ...

def get_path_for_function(f):
    """Get the path of the file where the function is defined.

    :returns: the path, or None if one could not be found or f is not a real
        function
    """
    ...

def parse_ini_file(f_loc):
    ...

def check_ast_node(name):
    "Check if the given name is that of a valid AST node."
    ...

def get_nosec(nosec_lines, context):
    ...

