
import ast
import configparser
import logging

LOG: logging.Logger

def get_call_name(node: ast.Call, aliases: dict[str, str]) -> str: ...
def get_func_name(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str: ...
def get_qual_attr(node: ast.AST, aliases: dict[str, str]) -> str: ...
def deepgetattr(obj: object, attr: str) -> object: ...

class InvalidModulePath(Exception): ...

class ConfigError(Exception):
    config_file: str
    message: str

    def __init__(self, message: str, config_file: str) -> None: ...

class ProfileNotFound(Exception):
    config_file: str
    profile: str

    def __init__(self, config_file: str, profile: str) -> None: ...

def warnings_formatter(
    message: object,
    category: type[Warning] = ...,
    filename: str = ...,
    lineno: int = ...,
    line: str = ...,
) -> str: ...
def get_module_qualname_from_path(path: str) -> str: ...
def namespace_path_join(base: str, name: str) -> str: ...
def namespace_path_split(path: str) -> tuple[str, str]: ...
def escaped_bytes_representation(b: bytes) -> bytes: ...
def calc_linerange(node: ast.AST) -> list[int]: ...
def linerange(node: ast.AST) -> list[int]: ...
def concat_string(node: ast.AST, stop: ast.AST | None = ...) -> tuple[ast.AST, str]: ...
def get_called_name(node: ast.Call) -> str: ...
def get_path_for_function(f: object) -> str | None: ...
def parse_ini_file(f_loc: str) -> configparser.ConfigParser: ...
def check_ast_node(name: str) -> str: ...
def get_nosec(
    nosec_lines: dict[int, set[str]], context: dict[str, object]
) -> set[str] | None: ...
