from _pytest.nodes import Item

"""Utilities for truncating assertion output.

Current default behaviour is to truncate assertion explanations at
terminal lines, unless running with an assertions verbosity level of at least 2 or running on CI.
"""
DEFAULT_MAX_LINES = ...
DEFAULT_MAX_CHARS = ...
USAGE_MSG = ...

def truncate_if_required(explanation: list[str], item: Item) -> list[str]: ...
