from collections.abc import Callable
from typing import Any

class ThreadLocal:
    def __init__(self, **kwargs: Callable) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
