"""Type stubs for docker.models.containers."""

from typing import Any

from docker.models.resource import Collection

class Container:
    """Docker container model."""

    id: str
    name: str
    status: str
    image: Any
    ports: dict[str, Any]
    attrs: dict[str, Any]

    def start(self) -> None: ...
    def stop(self) -> None: ...
    def remove(self) -> None: ...
    def reload(self) -> None: ...
    def logs(self, *args: Any, **kwargs: Any) -> bytes: ...
    def wait(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

class ContainerCollection(Collection[Container]):
    """Collection of Docker containers."""

    model: type[Container]

    def __init__(self, client: Any = None) -> None: ...
    def get(self, container_id: str) -> Container: ...
    def list(self, *args: Any, **kwargs: Any) -> list[Container]: ...
    def create(self, *args: Any, **kwargs: Any) -> Container: ...
    def run(self, *args: Any, **kwargs: Any) -> Container | bytes: ...
    def prune(self, filters: dict[str, Any] | None = None) -> dict[str, Any]: ...
