"""Type stubs for docker.models.resource.Collection."""

from typing import Any, Generic, TypeVar

T = TypeVar("T")

class Collection(Generic[T]):
    """Base collection class for Docker resources."""

    model: type[T] | None

    def __init__(self, client: Any = None) -> None: ...
    def list(self, *args: Any, **kwargs: Any) -> list[T]: ...
    def get(self, key: str) -> T: ...
    def create(self, attrs: dict[str, Any] | None = None) -> T: ...
    def prepare_model(self, attrs: dict[str, Any]) -> T: ...
