from dns.quic._common import AsyncQuicConnection, AsyncQuicManager, BaseQuicStream

class TrioQuicStream(BaseQuicStream):
    def __init__(self, connection, stream_id) -> None: ...
    async def wait_for(self, amount):  # -> None:
        ...
    async def wait_for_end(self):  # -> None:
        ...
    async def receive(self, timeout=...):  # -> bytes:
        ...
    async def send(self, datagram, is_end=...):  # -> None:
        ...
    async def close(self):  # -> None:
        ...
    async def __aenter__(self):  # -> Self:
        ...
    async def __aexit__(self, exc_type, exc_val, exc_tb):  # -> Literal[False]:
        ...

class TrioQuicConnection(AsyncQuicConnection):
    def __init__(
        self, connection, address, port, source, source_port, manager=...
    ) -> None: ...
    async def write(self, stream, data, is_end=...):  # -> None:
        ...
    async def run(self):  # -> None:
        ...
    async def make_stream(self, timeout=...):  # -> TrioQuicStream:
        ...
    async def close(self):  # -> None:
        ...

class TrioQuicManager(AsyncQuicManager):
    def __init__(
        self, nursery, conf=..., verify_mode=..., server_name=..., h3=...
    ) -> None: ...
    def connect(
        self, address, port=..., source=..., source_port=..., want_session_ticket=...
    ): ...
    async def __aenter__(self):  # -> Self:
        ...
    async def __aexit__(self, exc_type, exc_val, exc_tb):  # -> Literal[False]:
        ...
