from types import NoneType
from typing import (
    Any,
    Final,
    ForwardRef,
    NewType,
    ParamSpec,
    ParamSpecArgs,
    ParamSpecKwargs,
    TypeAliasType,
    TypeIs,
    TypeVar,
    TypeVarTuple,
)
from warnings import deprecated

"""Low-level introspection utilities for [`typing`][] members.

The provided functions in this module check against both the [`typing`][] and [`typing_extensions`][]
variants, if they exists and are different.
"""
__all__ = [
    "DEPRECATED_ALIASES",
    "NoneType",
    "is_annotated",
    "is_any",
    "is_classvar",
    "is_concatenate",
    "is_deprecated",
    "is_final",
    "is_generic",
    "is_literal",
    "is_literalstring",
    "is_namedtuple",
    "is_never",
    "is_newtype",
    "is_nodefault",
    "is_noextraitems",
    "is_noreturn",
    "is_notrequired",
    "is_paramspec",
    "is_paramspecargs",
    "is_paramspeckwargs",
    "is_readonly",
    "is_required",
    "is_self",
    "is_typealias",
    "is_typealiastype",
    "is_typeguard",
    "is_typeis",
    "is_typevar",
    "is_typevartuple",
    "is_union",
    "is_unpack",
]

def is_annotated(obj: Any, /) -> bool: ...
def is_any(obj: Any, /) -> bool: ...
def is_classvar(obj: Any, /) -> bool: ...
def is_concatenate(obj: Any, /) -> bool: ...
def is_final(obj: Any, /) -> bool: ...
def is_forwardref(obj: Any, /) -> TypeIs[ForwardRef]: ...
def is_generic(obj: Any, /) -> bool: ...
def is_literal(obj: Any, /) -> bool: ...
def is_paramspec(obj: Any, /) -> TypeIs[ParamSpec]: ...
def is_typevar(obj: Any, /) -> TypeIs[TypeVar]: ...
def is_typevartuple(obj: Any, /) -> TypeIs[TypeVarTuple]: ...
def is_union(obj: Any, /) -> bool: ...
def is_namedtuple(obj: Any, /) -> bool: ...
def is_literalstring(obj: Any, /) -> bool: ...
def is_never(obj: Any, /) -> bool: ...
def is_newtype(obj: Any, /) -> TypeIs[NewType]: ...
def is_nodefault(obj: Any, /) -> bool: ...
def is_noextraitems(obj: Any, /) -> bool: ...
def is_noreturn(obj: Any, /) -> bool: ...
def is_notrequired(obj: Any, /) -> bool: ...
def is_paramspecargs(obj: Any, /) -> TypeIs[ParamSpecArgs]: ...
def is_paramspeckwargs(obj: Any, /) -> TypeIs[ParamSpecKwargs]: ...
def is_readonly(obj: Any, /) -> bool: ...
def is_required(obj: Any, /) -> bool: ...
def is_self(obj: Any, /) -> bool: ...
def is_typealias(obj: Any, /) -> bool: ...
def is_typeguard(obj: Any, /) -> bool: ...
def is_typeis(obj: Any, /) -> bool: ...
def is_typealiastype(obj: Any, /) -> TypeIs[TypeAliasType]: ...
def is_unpack(obj: Any, /) -> bool: ...
def is_deprecated(obj: Any, /) -> TypeIs[deprecated]: ...

DEPRECATED_ALIASES: Final[dict[Any, type[Any]]]
