class shlex:
    def __init__(
        self, instream=..., infile=..., posix=..., punctuation_chars=...
    ) -> None: ...
    def push_token(self, tok):  # -> None:
        ...
    def push_source(self, newstream, newfile=...):  # -> None:
        ...
    def pop_source(self):  # -> None:
        ...
    def get_token(self):  # -> str | None:
        ...
    def read_token(self):  # -> str | None:
        ...
    def sourcehook(
        self, newfile
    ):  # -> tuple[str | Any, TextIOWrapper[_WrappedBuffer]]:
        ...
    def error_leader(self, infile=..., lineno=...):  # -> str:
        ...
    def __iter__(self):  # -> Self:
        ...
    def __next__(self):  # -> str | None:
        ...

    next = ...
