from collections.abc import Callable
from typing import Any

from ._events import Event, InformationalResponse, Request, Response
from ._headers import Headers
from ._util import Sentinel

__all__ = ["WRITERS"]
type Writer = Callable[[bytes], Any]

def write_headers(headers: Headers, write: Writer) -> None: ...
def write_request(request: Request, write: Writer) -> None: ...
def write_any_response(
    response: InformationalResponse | Response, write: Writer
) -> None: ...

class BodyWriter:
    def __call__(self, event: Event, write: Writer) -> None: ...
    def send_data(self, data: bytes, write: Writer) -> None: ...
    def send_eom(self, headers: Headers, write: Writer) -> None: ...

class ContentLengthWriter(BodyWriter):
    def __init__(self, length: int) -> None: ...
    def send_data(self, data: bytes, write: Writer) -> None: ...
    def send_eom(self, headers: Headers, write: Writer) -> None: ...

class ChunkedWriter(BodyWriter):
    def send_data(self, data: bytes, write: Writer) -> None: ...
    def send_eom(self, headers: Headers, write: Writer) -> None: ...

class FlextWeb10Writer(BodyWriter):
    def send_data(self, data: bytes, write: Writer) -> None: ...
    def send_eom(self, headers: Headers, write: Writer) -> None: ...

type WritersType = dict[
    tuple[type[Sentinel], type[Sentinel]] | type[Sentinel],
    dict[str, type[BodyWriter]]
    | Callable[[InformationalResponse | Response, Writer], None]
    | Callable[[Request, Writer], None],
]
WRITERS: WritersType = ...
