from __future__ import annotations

import importlib.util
import json
import sys
import types
from pathlib import Path


def load_module() -> types.ModuleType:
    module_path = (
        Path(__file__).resolve().parents[4] / "scripts" / "github" / "sync_workflows.py"
    )
    spec = importlib.util.spec_from_file_location("sync_workflows", module_path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_sync_project_creates_ci_from_template(tmp_path: Path) -> None:
    mod = load_module()
    project_root = tmp_path / "flext-core"
    _ = project_root.mkdir(parents=True)

    rendered_template = (
        "# Generated by scripts/github/sync_workflows.py - DO NOT EDIT\nname: CI\n"
    )
    operations = mod._sync_project(
        project_name="flext-core",
        project_root=project_root,
        rendered_template=rendered_template,
        apply=True,
        prune=True,
    )

    ci_file = project_root / ".github" / "workflows" / "ci.yml"
    assert ci_file.exists()
    assert ci_file.read_text(encoding="utf-8") == rendered_template
    assert any(op.action == "create" for op in operations)


def test_sync_project_overwrites_existing_ci(tmp_path: Path) -> None:
    mod = load_module()
    project_root = tmp_path / "flext-api"
    workflows_dir = project_root / ".github" / "workflows"
    _ = workflows_dir.mkdir(parents=True)
    _ = (workflows_dir / "ci.yml").write_text("name: Custom\n", encoding="utf-8")

    operations = mod._sync_project(
        project_name="flext-api",
        project_root=project_root,
        rendered_template="name: Canonical\n",
        apply=True,
        prune=True,
    )

    ci_file = workflows_dir / "ci.yml"
    assert ci_file.read_text(encoding="utf-8") == "name: Canonical\n"
    assert any(
        op.action == "update" and op.reason == "force overwrite ci.yml"
        for op in operations
    )


def test_sync_project_prunes_other_workflows(tmp_path: Path) -> None:
    mod = load_module()
    project_root = tmp_path / "flext-plugin"
    workflows_dir = project_root / ".github" / "workflows"
    _ = workflows_dir.mkdir(parents=True)
    _ = (workflows_dir / "legacy.yml").write_text("name: Legacy\n", encoding="utf-8")
    _ = (workflows_dir / "extra.yaml").write_text("name: Extra\n", encoding="utf-8")

    operations = mod._sync_project(
        project_name="flext-plugin",
        project_root=project_root,
        rendered_template="name: Canonical\n",
        apply=True,
        prune=True,
    )

    assert not (workflows_dir / "legacy.yml").exists()
    assert not (workflows_dir / "extra.yaml").exists()
    assert any(
        op.action == "prune" and op.reason == "remove non-canonical workflow"
        for op in operations
    )


def test_write_report_persists_summary(tmp_path: Path) -> None:
    mod = load_module()
    report_path = tmp_path / "report.json"
    operations = [
        mod.Operation(
            project="flext-core",
            path=".github/workflows/ci.yml",
            action="create",
            reason="missing ci.yml",
        ),
        mod.Operation(
            project="flext-api",
            path=".github/workflows/ci.yml",
            action="update",
            reason="force overwrite ci.yml",
        ),
    ]

    mod._write_report(report_path=report_path, mode="apply", operations=operations)
    payload = json.loads(report_path.read_text(encoding="utf-8"))

    assert payload["mode"] == "apply"
    assert payload["summary"] == {"create": 1, "update": 1}
    assert len(payload["operations"]) == 2


def test_resolve_source_workflow_uses_workspace_ci(tmp_path: Path) -> None:
    mod = load_module()
    source = tmp_path / ".github" / "workflows"
    _ = source.mkdir(parents=True)
    ci_path = source / "ci.yml"
    _ = ci_path.write_text("name: CI\n", encoding="utf-8")

    resolved = mod._resolve_source_workflow(tmp_path, None)

    assert resolved == ci_path.resolve()
