import dns.immutable
import dns.rdata

@dns.immutable.immutable
class TLSABase(dns.rdata.Rdata):
    __slots__ = ...
    def __init__(self, rdclass, rdtype, usage, selector, mtype, cert) -> None: ...
    def to_text(self, origin=..., relativize=..., **kw):  # -> str:
        ...
    @classmethod
    def from_text(
        cls, rdclass, rdtype, tok, origin=..., relativize=..., relativize_to=...
    ):  # -> Self:
        ...
    @classmethod
    def from_wire_parser(cls, rdclass, rdtype, parser, origin=...):  # -> Self:
        ...
