# ═══════════════════════════════════════════════════════════════════════════
# FLEXT MAKEFILE ORCHESTRATOR - MASTER COORDINATION SYSTEM
# ═══════════════════════════════════════════════════════════════════════════
# Version: 1.0.0
# Purpose: Intelligent Makefile distribution and coordination system
# Usage: Included automatically by workspace Makefile
# ═══════════════════════════════════════════════════════════════════════════

# ═══════════════════════════════════════════════════════════════════════════
#  ORCHESTRATOR CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════

TEMPLATES_DIR := $(WORKSPACE_ROOT)/templates/makefiles
ORCHESTRATOR_VERSION := 1.0.0
ORCHESTRATOR_SIGNATURE := "# Generated by FLEXT Orchestrator v$(ORCHESTRATOR_VERSION)"

# Project type detection patterns
CORE_PROJECTS_PATTERN := ^flext-(core|auth|plugin|observability|quality)$$
API_PROJECTS_PATTERN := ^flext-(api|web|grpc)$$
CLI_PROJECTS_PATTERN := ^flext-cli$$
SINGER_PROJECTS_PATTERN := ^flext-(tap|target|dbt)-.*$$
CLIENT_PROJECTS_PATTERN := ^(algar|gruponos)-.*$$
LEGACY_PROJECTS_PATTERN := ^flx-.*$$

# Template inclusion order (dependencies)
BASE_TEMPLATES := base/common.mk
PYTHON_TEMPLATES := python/python.mk
SERVICE_TEMPLATES := service/service.mk
SINGER_TEMPLATES := singer/singer.mk
CLIENT_TEMPLATES := client/client.mk

# ═══════════════════════════════════════════════════════════════════════════
#  PROJECT TYPE DETECTION FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════

# Detect project type based on name and structure
define detect_project_type
$(shell \
	PROJECT_NAME="$(1)"; \
	if echo "$$PROJECT_NAME" | grep -E '$(CORE_PROJECTS_PATTERN)' >/dev/null 2>&1; then \
		echo "core"; \
	elif echo "$$PROJECT_NAME" | grep -E '$(API_PROJECTS_PATTERN)' >/dev/null 2>&1; then \
		echo "service"; \
	elif echo "$$PROJECT_NAME" | grep -E '$(CLI_PROJECTS_PATTERN)' >/dev/null 2>&1; then \
		echo "cli"; \
	elif echo "$$PROJECT_NAME" | grep -E '$(SINGER_PROJECTS_PATTERN)' >/dev/null 2>&1; then \
		echo "singer"; \
	elif echo "$$PROJECT_NAME" | grep -E '$(CLIENT_PROJECTS_PATTERN)' >/dev/null 2>&1; then \
		echo "client"; \
	elif echo "$$PROJECT_NAME" | grep -E '$(LEGACY_PROJECTS_PATTERN)' >/dev/null 2>&1; then \
		echo "legacy"; \
	else \
		echo "python"; \
	fi \
)
endef

# Detect required templates for a project type
define get_project_templates
$(shell \
	TYPE="$(1)"; \
	if [ "$$TYPE" = "core" ]; then \
		echo "$(BASE_TEMPLATES) $(PYTHON_TEMPLATES)"; \
	elif [ "$$TYPE" = "service" ]; then \
		echo "$(BASE_TEMPLATES) $(PYTHON_TEMPLATES) $(SERVICE_TEMPLATES)"; \
	elif [ "$$TYPE" = "cli" ]; then \
		echo "$(BASE_TEMPLATES) $(PYTHON_TEMPLATES)"; \
	elif [ "$$TYPE" = "singer" ]; then \
		echo "$(BASE_TEMPLATES) $(PYTHON_TEMPLATES) $(SINGER_TEMPLATES)"; \
	elif [ "$$TYPE" = "client" ]; then \
		echo "$(BASE_TEMPLATES) $(PYTHON_TEMPLATES)"; \
	elif [ "$$TYPE" = "legacy" ]; then \
		echo "$(BASE_TEMPLATES)"; \
	else \
		echo "$(BASE_TEMPLATES) $(PYTHON_TEMPLATES)"; \
	fi \
)
endef

# Check if project has specific capabilities
define check_project_capabilities
$(shell \
	PROJECT_DIR="$(1)"; \
	CAPABILITIES=""; \
	if [ -f "$$PROJECT_DIR/manage.py" ] || grep -q "Django\|django" "$$PROJECT_DIR"/*.py "$$PROJECT_DIR"/src/*/*.py 2>/dev/null; then \
		CAPABILITIES="$$CAPABILITIES django"; \
	fi; \
	if grep -q "FastAPI\|fastapi" "$$PROJECT_DIR"/*.py "$$PROJECT_DIR"/src/*/*.py 2>/dev/null; then \
		CAPABILITIES="$$CAPABILITIES fastapi"; \
	fi; \
	if grep -q "Flask\|flask" "$$PROJECT_DIR"/*.py "$$PROJECT_DIR"/src/*/*.py 2>/dev/null; then \
		CAPABILITIES="$$CAPABILITIES flask"; \
	fi; \
	if [ -f "$$PROJECT_DIR/Dockerfile" ]; then \
		CAPABILITIES="$$CAPABILITIES docker"; \
	fi; \
	if [ -f "$$PROJECT_DIR/docker-compose.yml" ]; then \
		CAPABILITIES="$$CAPABILITIES compose"; \
	fi; \
	echo "$$CAPABILITIES" \
)
endef

# ═══════════════════════════════════════════════════════════════════════════
#  MAKEFILE GENERATION FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════

# Generate standard Makefile header
define generate_makefile_header
# ═══════════════════════════════════════════════════════════════════════════
# $(shell echo $(1) | tr '[:lower:]' '[:upper:]') MAKEFILE - FLEXT PROJECT
# ═══════════════════════════════════════════════════════════════════════════
$(ORCHESTRATOR_SIGNATURE)
# Project: $(1)
# Type: $(2)
# Templates: $(3)
# Generated: $(shell date '+%Y-%m-%d %H:%M:%S')
# ═══════════════════════════════════════════════════════════════════════════

# Project configuration
PROJECT_TYPE := $(2)

# Template includes (order matters for dependencies)
endef

# Generate template includes
define generate_template_includes
$(foreach template,$(1),include $$(FLEXT_ROOT)/templates/makefiles/$(template)$(newline))
endef

# Generate project-specific configuration
define generate_project_config
$(shell \
	PROJECT_NAME="$(1)"; \
	PROJECT_TYPE="$(2)"; \
	CAPABILITIES="$(3)"; \
	echo ""; \
	echo "# ═══════════════════════════════════════════════════════════════════════════"; \
	echo "#  PROJECT-SPECIFIC CONFIGURATION"; \
	echo "# ═══════════════════════════════════════════════════════════════════════════"; \
	echo ""; \
	if [ "$$PROJECT_TYPE" = "service" ]; then \
		if echo "$$CAPABILITIES" | grep -q "fastapi"; then \
			echo "# FastAPI service configuration"; \
			echo "SERVICE_HOST ?= 0.0.0.0"; \
			echo "SERVICE_PORT ?= 8000"; \
		elif echo "$$CAPABILITIES" | grep -q "django"; then \
			echo "# Django service configuration"; \
			echo "SERVICE_HOST ?= 0.0.0.0"; \
			echo "SERVICE_PORT ?= 8001"; \
		elif echo "$$CAPABILITIES" | grep -q "flask"; then \
			echo "# Flask service configuration"; \
			echo "SERVICE_HOST ?= 0.0.0.0"; \
			echo "SERVICE_PORT ?= 5000"; \
		fi; \
	elif [ "$$PROJECT_TYPE" = "singer" ]; then \
		echo "# Singer project configuration"; \
		if echo "$$PROJECT_NAME" | grep -q "tap-"; then \
			echo "SINGER_TYPE := tap"; \
		elif echo "$$PROJECT_NAME" | grep -q "target-"; then \
			echo "SINGER_TYPE := target"; \
		fi; \
	fi; \
	echo "" \
)
endef

# ═══════════════════════════════════════════════════════════════════════════
#  ORCHESTRATION TARGETS
# ═══════════════════════════════════════════════════════════════════════════

orchestrate-all: ## Generate/update Makefiles for all projects
	$(call log_section,Orchestrating All Project Makefiles)
	@total_projects=0; \
	updated_projects=0; \
	for project in $(ACTIVE_PROJECTS); do \
		if [ -d "$$project" ]; then \
			total_projects=$$((total_projects + 1)); \
			if $(MAKE) orchestrate-project PROJECT=$$project; then \
				updated_projects=$$((updated_projects + 1)); \
			fi; \
		fi; \
	done; \
	for project in $(LEGACY_PROJECTS); do \
		if [ -d "legacy/$$project" ]; then \
			total_projects=$$((total_projects + 1)); \
			if $(MAKE) orchestrate-legacy-project PROJECT=$$project; then \
				updated_projects=$$((updated_projects + 1)); \
			fi; \
		fi; \
	done; \
	$(call log_success,Orchestration complete: $$updated_projects/$$total_projects projects updated)

orchestrate-project: ## Generate/update Makefile for specific project
	@if [ -z "$(PROJECT)" ]; then \
		echo "$(RED)Error: PROJECT variable required$(RESET)"; \
		exit 1; \
	fi
	@echo "$(BOLD)$(CYAN)🎯 Orchestrating project: $(PROJECT)$(RESET)"
	@if [ ! -d "$(PROJECT)" ]; then \
		echo "$(RED)Error: Project directory not found: $(PROJECT)$(RESET)"; \
		exit 1; \
	fi
	@if echo "$(PROJECT)" | grep -E '^flext-(core|auth|plugin|observability|quality)$$' >/dev/null; then \
		project_type="core"; \
	elif echo "$(PROJECT)" | grep -E '^flext-(api|web|grpc)$$' >/dev/null; then \
		project_type="service"; \
	elif echo "$(PROJECT)" | grep -E '^flext-cli$$' >/dev/null; then \
		project_type="cli"; \
	elif echo "$(PROJECT)" | grep -E '^flext-(tap|target|dbt)-.*$$' >/dev/null; then \
		project_type="singer"; \
	elif echo "$(PROJECT)" | grep -E '^(algar|gruponos)-.*$$' >/dev/null; then \
		project_type="client"; \
	elif echo "$(PROJECT)" | grep -E '^flx-.*$$' >/dev/null; then \
		project_type="legacy"; \
	else \
		project_type="python"; \
	fi; \
	if [ "$$project_type" = "core" ]; then \
		templates="base/common.mk python/python.mk"; \
	elif [ "$$project_type" = "service" ]; then \
		templates="base/common.mk python/python.mk service/service.mk"; \
	elif [ "$$project_type" = "cli" ]; then \
		templates="base/common.mk python/python.mk"; \
	elif [ "$$project_type" = "singer" ]; then \
		templates="base/common.mk python/python.mk singer/singer.mk"; \
	elif [ "$$project_type" = "client" ]; then \
		templates="base/common.mk python/python.mk"; \
	elif [ "$$project_type" = "legacy" ]; then \
		templates="base/common.mk"; \
	else \
		templates="base/common.mk python/python.mk"; \
	fi; \
	capabilities=""; \
	if [ -f "$(PROJECT)/manage.py" ]; then capabilities="$$capabilities django"; fi; \
	if grep -q "FastAPI\|fastapi" "$(PROJECT)"/*.py "$(PROJECT)"/src/*/*.py 2>/dev/null; then capabilities="$$capabilities fastapi"; fi; \
	if grep -q "Flask\|flask" "$(PROJECT)"/*.py "$(PROJECT)"/src/*/*.py 2>/dev/null; then capabilities="$$capabilities flask"; fi; \
	if [ -f "$(PROJECT)/Dockerfile" ]; then capabilities="$$capabilities docker"; fi; \
	if [ -f "$(PROJECT)/docker-compose.yml" ]; then capabilities="$$capabilities compose"; fi; \
	echo "  Project type: $$project_type"; \
	echo "  Templates: $$templates"; \
	echo "  Capabilities:$$capabilities"; \
	$(MAKE) _generate_makefile \
		PROJECT_NAME=$(PROJECT) \
		PROJECT_DIR=$(PROJECT) \
		PROJECT_TYPE=$$project_type \
		PROJECT_TEMPLATES="$$templates" \
		PROJECT_CAPABILITIES="$$capabilities"

orchestrate-legacy-project: ## Generate/update Makefile for legacy project
	@if [ -z "$(PROJECT)" ]; then \
		$(call log_error,PROJECT variable required); \
		exit 1; \
	fi
	@$(call log_info,Orchestrating legacy project: $(PROJECT))
	@PROJECT_TYPE="legacy"; \
	PROJECT_TEMPLATES=$$($(call get_project_templates,$$PROJECT_TYPE)); \
	PROJECT_CAPABILITIES=$$($(call check_project_capabilities,legacy/$(PROJECT))); \
	$(MAKE) _generate_makefile \
		PROJECT_NAME=$(PROJECT) \
		PROJECT_DIR=legacy/$(PROJECT) \
		PROJECT_TYPE=$$PROJECT_TYPE \
		PROJECT_TEMPLATES="$$PROJECT_TEMPLATES" \
		PROJECT_CAPABILITIES="$$PROJECT_CAPABILITIES"

_generate_makefile: ## Internal: Generate Makefile for project
	@echo "$(CYAN)📝 Generating Makefile for $(PROJECT_NAME)$(RESET)"
	@MAKEFILE_PATH="$(PROJECT_DIR)/Makefile"; \
	BACKUP_PATH="$(PROJECT_DIR)/Makefile.backup.$$(date +%Y%m%d_%H%M%S)"; \
	if [ -f "$$MAKEFILE_PATH" ] && ! grep -q "Generated by FLEXT Orchestrator" "$$MAKEFILE_PATH" 2>/dev/null; then \
		echo "$(YELLOW)⚠ Backing up existing custom Makefile$(RESET)"; \
		cp "$$MAKEFILE_PATH" "$$BACKUP_PATH"; \
	fi; \
	echo "$(CYAN)📄 Writing new Makefile...$(RESET)"; \
	{ \
		echo "# ═══════════════════════════════════════════════════════════════════════════"; \
		echo "# $$(echo $(PROJECT_NAME) | tr '[:lower:]' '[:upper:]') MAKEFILE - FLEXT PROJECT"; \
		echo "# ═══════════════════════════════════════════════════════════════════════════"; \
		echo "# Generated by FLEXT Orchestrator v$(ORCHESTRATOR_VERSION)"; \
		echo "# Project: $(PROJECT_NAME)"; \
		echo "# Type: $(PROJECT_TYPE)"; \
		echo "# Templates: $(PROJECT_TEMPLATES)"; \
		echo "# Generated: $$(date '+%Y-%m-%d %H:%M:%S')"; \
		echo "# ═══════════════════════════════════════════════════════════════════════════"; \
		echo ""; \
		echo "# Project configuration"; \
		echo "PROJECT_TYPE := $(PROJECT_TYPE)"; \
		echo ""; \
		echo "# Auto-detect FLEXT workspace root"; \
		echo "FLEXT_ROOT ?= \$$(shell if [ -f \"../Makefile\" ] && grep -q \"FLEXT Enhanced Workspace\" \"../Makefile\" 2>/dev/null; then echo \"\$$(CURDIR)/..\"; elif [ -f \"../../Makefile\" ] && grep -q \"FLEXT Enhanced Workspace\" \"../../Makefile\" 2>/dev/null; then echo \"\$$(CURDIR)/../..\"; else echo \"\"; fi)"; \
		echo ""; \
		echo "# Template includes (order matters for dependencies)"; \
		for template in $(PROJECT_TEMPLATES); do \
			echo "include \$$(FLEXT_ROOT)/templates/makefiles/$$template"; \
		done; \
		echo ""; \
		echo "# ═══════════════════════════════════════════════════════════════════════════"; \
		echo "#  PROJECT-SPECIFIC CONFIGURATION"; \
		echo "# ═══════════════════════════════════════════════════════════════════════════"; \
		echo ""; \
		if [ "$(PROJECT_TYPE)" = "service" ]; then \
			if echo "$(PROJECT_CAPABILITIES)" | grep -q "fastapi"; then \
				echo "# FastAPI service configuration"; \
				echo "SERVICE_HOST ?= 0.0.0.0"; \
				echo "SERVICE_PORT ?= 8000"; \
			elif echo "$(PROJECT_CAPABILITIES)" | grep -q "django"; then \
				echo "# Django service configuration"; \
				echo "SERVICE_HOST ?= 0.0.0.0"; \
				echo "SERVICE_PORT ?= 8001"; \
			elif echo "$(PROJECT_CAPABILITIES)" | grep -q "flask"; then \
				echo "# Flask service configuration"; \
				echo "SERVICE_HOST ?= 0.0.0.0"; \
				echo "SERVICE_PORT ?= 5000"; \
			fi; \
		elif [ "$(PROJECT_TYPE)" = "singer" ]; then \
			echo "# Singer project configuration"; \
			if echo "$(PROJECT_NAME)" | grep -q "tap-"; then \
				echo "SINGER_TYPE := tap"; \
			elif echo "$(PROJECT_NAME)" | grep -q "target-"; then \
				echo "SINGER_TYPE := target"; \
			fi; \
		fi; \
		echo ""; \
		echo "# ═══════════════════════════════════════════════════════════════════════════"; \
		echo "#  PROJECT-SPECIFIC TARGETS (Add custom targets below this line)"; \
		echo "# ═══════════════════════════════════════════════════════════════════════════"; \
		echo ""; \
		echo "# Add your project-specific targets here"; \
		echo ""; \
	} > "$$MAKEFILE_PATH"; \
	echo "$(GREEN)✅ Makefile generated: $$MAKEFILE_PATH$(RESET)"

# ═══════════════════════════════════════════════════════════════════════════
#  PROJECT ANALYSIS TARGETS
# ═══════════════════════════════════════════════════════════════════════════

analyze-projects: ## Analyze all projects for orchestration planning
	$(call log_section,Analyzing Projects for Orchestration)
	@echo "$(BOLD)Project Analysis Summary:$(RESET)"
	@echo ""
	@for project in $(ACTIVE_PROJECTS); do \
		if [ -d "$$project" ]; then \
			project_type=$$($(call detect_project_type,$$project)); \
			templates=$$($(call get_project_templates,$$project_type)); \
			capabilities=$$($(call check_project_capabilities,$$project)); \
			has_makefile="No"; \
			makefile_type="None"; \
			if [ -f "$$project/Makefile" ]; then \
				has_makefile="Yes"; \
				if grep -q "Generated by FLEXT Orchestrator" "$$project/Makefile" 2>/dev/null; then \
					makefile_type="Orchestrated"; \
				else \
					makefile_type="Custom"; \
				fi; \
			fi; \
			echo "$(CYAN)$$project$(RESET):"; \
			echo "  Type: $$project_type"; \
			echo "  Templates: $$templates"; \
			echo "  Capabilities: $$capabilities"; \
			echo "  Makefile: $$has_makefile ($$makefile_type)"; \
			echo ""; \
		fi; \
	done

analyze-project: ## Analyze specific project
	@if [ -z "$(PROJECT)" ]; then \
		echo "$(RED)Error: PROJECT variable required$(RESET)"; \
		exit 1; \
	fi
	@echo "$(BOLD)$(CYAN)🔍 Analyzing Project: $(PROJECT)$(RESET)"
	@if [ -d "$(PROJECT)" ]; then \
		echo "Project: $(BOLD)$(PROJECT)$(RESET)"; \
		echo "Directory: $$(pwd)/$(PROJECT)"; \
		echo ""; \
		echo "$(BOLD)Detection Results:$(RESET)"; \
		if echo "$(PROJECT)" | grep -E '^flext-(core|auth|plugin|observability|quality)$$' >/dev/null; then \
			project_type="core"; \
		elif echo "$(PROJECT)" | grep -E '^flext-(api|web|grpc)$$' >/dev/null; then \
			project_type="service"; \
		elif echo "$(PROJECT)" | grep -E '^flext-cli$$' >/dev/null; then \
			project_type="cli"; \
		elif echo "$(PROJECT)" | grep -E '^flext-(tap|target|dbt)-.*$$' >/dev/null; then \
			project_type="singer"; \
		elif echo "$(PROJECT)" | grep -E '^(algar|gruponos)-.*$$' >/dev/null; then \
			project_type="client"; \
		elif echo "$(PROJECT)" | grep -E '^flx-.*$$' >/dev/null; then \
			project_type="legacy"; \
		else \
			project_type="python"; \
		fi; \
		echo "  Type: $$project_type"; \
		if [ "$$project_type" = "core" ]; then \
			templates="base/common.mk python/python.mk"; \
		elif [ "$$project_type" = "service" ]; then \
			templates="base/common.mk python/python.mk service/service.mk"; \
		elif [ "$$project_type" = "cli" ]; then \
			templates="base/common.mk python/python.mk"; \
		elif [ "$$project_type" = "singer" ]; then \
			templates="base/common.mk python/python.mk singer/singer.mk"; \
		elif [ "$$project_type" = "client" ]; then \
			templates="base/common.mk python/python.mk"; \
		elif [ "$$project_type" = "legacy" ]; then \
			templates="base/common.mk"; \
		else \
			templates="base/common.mk python/python.mk"; \
		fi; \
		echo "  Required Templates: $$templates"; \
		capabilities=""; \
		if [ -f "$(PROJECT)/manage.py" ]; then capabilities="$$capabilities django"; fi; \
		if grep -q "FastAPI\|fastapi" "$(PROJECT)"/*.py "$(PROJECT)"/src/*/*.py 2>/dev/null; then capabilities="$$capabilities fastapi"; fi; \
		if grep -q "Flask\|flask" "$(PROJECT)"/*.py "$(PROJECT)"/src/*/*.py 2>/dev/null; then capabilities="$$capabilities flask"; fi; \
		if [ -f "$(PROJECT)/Dockerfile" ]; then capabilities="$$capabilities docker"; fi; \
		if [ -f "$(PROJECT)/docker-compose.yml" ]; then capabilities="$$capabilities compose"; fi; \
		echo "  Detected Capabilities:$$capabilities"; \
		echo ""; \
		echo "$(BOLD)Template Details:$(RESET)"; \
		for template in $$templates; do \
			if [ -f "$(TEMPLATES_DIR)/$$template" ]; then \
				echo "  $(GREEN)✓$(RESET) $$template"; \
			else \
				echo "  $(RED)✗$(RESET) $$template (missing)"; \
			fi; \
		done; \
		echo ""; \
		if [ -f "$(PROJECT)/Makefile" ]; then \
			echo "$(BOLD)Current Makefile:$(RESET)"; \
			if grep -q "Generated by FLEXT Orchestrator" "$(PROJECT)/Makefile" 2>/dev/null; then \
				echo "  $(GREEN)✓$(RESET) Orchestrated (managed)"; \
			else \
				echo "  $(YELLOW)⚠$(RESET) Custom (will be backed up)"; \
			fi; \
		else \
			echo "$(BOLD)Current Makefile:$(RESET)"; \
			echo "  $(RED)✗$(RESET) Missing"; \
		fi; \
	else \
		echo "$(RED)Error: Project directory not found: $(PROJECT)$(RESET)"; \
		exit 1; \
	fi

# ═══════════════════════════════════════════════════════════════════════════
#  TEMPLATE MANAGEMENT TARGETS
# ═══════════════════════════════════════════════════════════════════════════

validate-templates: ## Validate all template files
	$(call log_section,Validating Template Files)
	@template_errors=0; \
	for template in $(BASE_TEMPLATES) $(PYTHON_TEMPLATES) $(SERVICE_TEMPLATES) $(SINGER_TEMPLATES); do \
		template_path="$(TEMPLATES_DIR)/$$template"; \
		if [ -f "$$template_path" ]; then \
			$(call log_info,Validating $$template); \
			if $(MAKE) -f "$$template_path" --dry-run help >/dev/null 2>&1; then \
				echo "  $(GREEN)✓$(RESET) $$template"; \
			else \
				echo "  $(RED)✗$(RESET) $$template (syntax error)"; \
				template_errors=$$((template_errors + 1)); \
			fi; \
		else \
			echo "  $(RED)✗$(RESET) $$template (missing)"; \
			template_errors=$$((template_errors + 1)); \
		fi; \
	done; \
	if [ $$template_errors -eq 0 ]; then \
		$(call log_success,All templates are valid); \
	else \
		$(call log_error,$$template_errors template(s) have issues); \
		exit 1; \
	fi

list-templates: ## List all available templates
	$(call log_section,Available Templates)
	@echo "$(BOLD)Base Templates:$(RESET)"
	@for template in $(BASE_TEMPLATES); do echo "  - $$template"; done
	@echo ""
	@echo "$(BOLD)Python Templates:$(RESET)"
	@for template in $(PYTHON_TEMPLATES); do echo "  - $$template"; done
	@echo ""
	@echo "$(BOLD)Service Templates:$(RESET)"
	@for template in $(SERVICE_TEMPLATES); do echo "  - $$template"; done
	@echo ""
	@echo "$(BOLD)Singer Templates:$(RESET)"
	@for template in $(SINGER_TEMPLATES); do echo "  - $$template"; done

# ═══════════════════════════════════════════════════════════════════════════
#  MAINTENANCE TARGETS
# ═══════════════════════════════════════════════════════════════════════════

update-orchestrated: ## Update all orchestrated Makefiles
	$(call log_section,Updating Orchestrated Makefiles)
	@updated_count=0; \
	for project in $(ACTIVE_PROJECTS); do \
		if [ -f "$$project/Makefile" ] && grep -q "Generated by FLEXT Orchestrator" "$$project/Makefile" 2>/dev/null; then \
			$(call log_info,Updating $$project); \
			if $(MAKE) orchestrate-project PROJECT=$$project; then \
				updated_count=$$((updated_count + 1)); \
			fi; \
		fi; \
	done; \
	$(call log_success,Updated $$updated_count orchestrated Makefiles)

clean-backups: ## Clean old Makefile backups
	$(call log_section,Cleaning Makefile Backups)
	@backup_count=0; \
	find . -name "Makefile.backup.*" -type f | while read backup; do \
		$(call log_info,Removing $$backup); \
		rm -f "$$backup"; \
		backup_count=$$((backup_count + 1)); \
	done; \
	$(call log_success,Removed backup files)

# ═══════════════════════════════════════════════════════════════════════════
#  HELPER FUNCTIONS FOR NEWLINES IN MAKE
# ═══════════════════════════════════════════════════════════════════════════

define newline


endef

# ═══════════════════════════════════════════════════════════════════════════
#  PHONY TARGETS
# ═══════════════════════════════════════════════════════════════════════════

.PHONY: orchestrate-all orchestrate-project orchestrate-legacy-project _generate_makefile
.PHONY: analyze-projects analyze-project
.PHONY: validate-templates list-templates
.PHONY: update-orchestrated clean-backups
