from rope.base.resources import File, Resource
from rope.base.taskhandle import NullJobSet, NullTaskHandle

class Change:
    resource: Resource
    def do(self, job_set: NullJobSet | None = None) -> None: ...
    def undo(self, job_set: NullJobSet | None = None) -> None: ...
    def get_description(self) -> str: ...
    def get_changed_resources(self) -> list[Resource]: ...

class ChangeSet(Change):
    changes: list[Change]
    description: str
    time: float | None
    def __init__(self, description: str, timestamp: float | None = None) -> None: ...
    def do(self, job_set: NullJobSet | None = None) -> None: ...
    def undo(self, job_set: NullJobSet | None = None) -> None: ...
    def add_change(self, change: Change) -> None: ...
    def get_description(self) -> str: ...
    def get_changed_resources(self) -> list[Resource]: ...

class ChangeContents(Change):
    resource: File
    new_contents: str
    old_contents: str | None
    def __init__(
        self, resource: File, new_contents: str, old_contents: str | None = None
    ) -> None: ...

class MoveResource(Change):
    resource: Resource
    new_location: str
    def __init__(self, resource: Resource, new_location: str) -> None: ...

class RemoveResource(Change):
    resource: Resource
    def __init__(self, resource: Resource) -> None: ...
