class RopeError(Exception): ...

class ResourceNotFoundError(RopeError): ...

class RefactoringError(RopeError): ...

class InterruptedTaskError(RopeError): ...

class HistoryError(RopeError): ...

class ModuleNotFoundError(RopeError): ...

class AttributeNotFoundError(RopeError): ...

class NameNotFoundError(RopeError): ...

class BadIdentifierError(RopeError): ...

class ModuleSyntaxError(RopeError):
    filename: str
    lineno: int
    message_: str
    def __init__(self, filename: str, lineno: int, message: str) -> None: ...

class ModuleDecodeError(RopeError):
    filename: str
    message_: str
    def __init__(self, filename: str, message: str) -> None: ...
