
from rope.base.change import ChangeSet
from rope.base.pyobjects import AbstractModule
from rope.base.resources import File, Folder, Resource
from rope.base.taskhandle import NullTaskHandle

class _Project:
    observers: list[object]
    fscommands: object
    def __init__(self, fscommands: object = None) -> None: ...
    def get_resource(self, resource_name: str) -> File | Folder: ...
    def get_module(self, name: str, folder: Folder | None = None) -> AbstractModule: ...
    def get_python_path_folders(self) -> list[Folder]: ...
    def get_source_folders(self) -> list[Folder]: ...
    def validate(self, folder: Folder) -> None: ...
    def add_observer(self, observer: object) -> None: ...
    def remove_observer(self, observer: object) -> None: ...
    def do(
        self,
        changes: ChangeSet,
        task_handle: NullTaskHandle = ...,
    ) -> None: ...
    def get_pymodule(
        self, resource: Resource, force_errors: bool = False
    ) -> AbstractModule: ...
    def get_pycore(self) -> object: ...
    def get_file(self, path: str) -> File: ...
    def get_folder(self, path: str) -> Folder: ...
    def find_module(self, modname: str, folder: Folder | None = None) -> File | None: ...
    def is_ignored(self, resource: Resource) -> bool: ...
    @property
    def root(self) -> Folder: ...
    @property
    def history(self) -> object: ...
    @property
    def pycore(self) -> object: ...

class Project(_Project):
    def __init__(
        self,
        projectroot: str,
        fscommands: object = None,
        ropefolder: str | None = ".ropeproject",
        **prefs: object,
    ) -> None: ...
    @property
    def address(self) -> str: ...
    def get_files(self) -> list[File]: ...
    def get_python_files(self) -> list[File]: ...
    def close(self) -> None: ...
    def sync(self) -> None: ...
