from rope.base.pyobjects import AbstractModule, PyObject

class PyName:
    def get_object(self) -> PyObject: ...
    def get_definition_location(self) -> tuple[AbstractModule | None, int | None]: ...

class DefinedName(PyName):
    pyobject: PyObject
    def __init__(self, pyobject: PyObject) -> None: ...
    def get_object(self) -> PyObject: ...
    def get_definition_location(self) -> tuple[AbstractModule | None, int | None]: ...

class AssignedName(PyName): ...

class UnboundName(PyName):
    def __init__(self, pyobject: PyObject | None = None) -> None: ...

class ImportedName(PyName):
    def __init__(self, pymodule: PyObject, pyname: PyName) -> None: ...
    def get_object(self) -> PyObject: ...
    def get_definition_location(self) -> tuple[AbstractModule | None, int | None]: ...

class ImportedModule(PyName):
    def __init__(
        self,
        pymodule: PyObject,
        *,
        resource: object | None = None,
        module_name: str | None = None,
        level: int = 0,
    ) -> None: ...
