from __future__ import annotations

from collections.abc import Sequence

from rope.base.resources import Resource


class PyModule:
    source_code: str

    def get_attributes(self) -> dict[str, PyName]: ...
    def get_name(self) -> str | None: ...
    def get_resource(self) -> Resource | None: ...


class PyObject:
    def get_module(self) -> PyModule | None: ...
    def get_name(self) -> str | None: ...


class PyFunction(PyObject):
    def get_kind(self) -> str: ...


class AbstractClass(PyObject):
    def get_attributes(self) -> dict[str, PyName]: ...
    def get_bases(self) -> Sequence[AbstractClass]: ...
    def get_superclasses(self) -> Sequence[AbstractClass]: ...


class PyName:
    def get_object(self) -> PyObject: ...
    def get_definition_location(self) -> tuple[PyModule | None, int | None]: ...


class PyCore:
    def resource_to_pyobject(self, resource: Resource) -> PyModule: ...
