from rope.base.pynames import PyName

class PyObject:
    type: PyObject
    def __init__(self, type_: PyObject | None = None) -> None: ...
    def get_attributes(self) -> dict[str, PyName]: ...
    def get_attribute(self, name: str) -> PyName: ...
    def get_module(self) -> AbstractModule | None: ...
    def get_type(self) -> PyObject: ...
    def __getitem__(self, key: str) -> PyName: ...
    def __contains__(self, key: str) -> bool: ...
    def __eq__(self, obj: object) -> bool: ...
    def __ne__(self, obj: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __iter__(self) -> object: ...

class AbstractClass(PyObject):
    def __init__(self) -> None: ...
    def get_name(self) -> str | None: ...
    def get_doc(self) -> str | None: ...
    def get_superclasses(self) -> list[AbstractClass]: ...

class AbstractFunction(PyObject):
    def __init__(self) -> None: ...
    def get_name(self) -> str | None: ...
    def get_doc(self) -> str | None: ...
    def get_param_names(self, special_args: bool = True) -> list[str]: ...
    def get_returned_object(self, args: object = None) -> PyObject: ...

class AbstractModule(PyObject):
    def __init__(self, doc: str | None = None) -> None: ...
    def get_doc(self) -> str | None: ...
    def get_resource(self) -> object | None: ...

class PyDefinedObject:
    pycore: object
    ast_node: object
    parent: object
    def __init__(self, pycore: object, ast_node: object, parent: object) -> None: ...
    def get_name(self) -> str: ...
    def get_module(self) -> AbstractModule: ...
    def get_scope(self) -> object: ...

class PyFunction(AbstractFunction, PyDefinedObject):
    def get_kind(self) -> str: ...

class PyClass(AbstractClass, PyDefinedObject): ...

def get_base_type(name: str) -> PyObject: ...
def get_unknown() -> PyObject: ...
