from rope.base import pyobjects

class PyFunction(pyobjects.PyFunction):
    def get_name(self) -> str: ...
    def get_kind(self) -> str: ...
    def get_param_names(self, special_args: bool = True) -> list[str]: ...

class PyClass(pyobjects.PyClass):
    def get_superclasses(self) -> list[pyobjects.AbstractClass]: ...
    def get_name(self) -> str: ...
