import os
from pathlib import Path

class Resource(os.PathLike[str]):
    project: _Project
    _path: str
    def __init__(self, project: _Project, path: str) -> None: ...
    def __fspath__(self) -> str: ...
    def move(self, new_location: str) -> None: ...
    def remove(self) -> None: ...
    def is_dir(self) -> bool: ...
    def is_folder(self) -> bool: ...
    def create(self) -> None: ...
    def exists(self) -> bool: ...
    @property
    def parent(self) -> Folder: ...
    @property
    def path(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def real_path(self) -> str: ...
    @property
    def pathlib(self) -> Path: ...
    def __eq__(self, obj: object) -> bool: ...
    def __ne__(self, obj: object) -> bool: ...
    def __hash__(self) -> int: ...

class File(Resource):
    newlines: str | None
    def __init__(self, project: _Project, name: str) -> None: ...
    def read(self) -> str: ...
    def read_bytes(self) -> bytes: ...
    def write(self, contents: str) -> None: ...
    def is_folder(self) -> bool: ...
    def create(self) -> None: ...

class Folder(Resource):
    def is_folder(self) -> bool: ...
    def get_children(self) -> list[Resource]: ...
    def create_file(self, file_name: str) -> File: ...
    def create_folder(self, folder_name: str) -> Folder: ...
    def get_child(self, name: str) -> Resource: ...
    def has_child(self, name: str) -> bool: ...
    def get_files(self) -> list[File]: ...
    def get_folders(self) -> list[Folder]: ...
    def contains(self, resource: Resource) -> bool: ...
    def create(self) -> None: ...

class _ResourceMatcher:
    def __init__(self) -> None: ...

# Forward reference workaround
from rope.base.project import _Project as _Project
