from abc import ABC, abstractmethod

class BaseJobSet(ABC):
    name: str
    job_name: str
    @abstractmethod
    def started_job(self, name: str) -> None: ...
    @abstractmethod
    def finished_job(self) -> None: ...
    @abstractmethod
    def check_status(self) -> None: ...
    @abstractmethod
    def get_percent_done(self) -> float | None: ...
    @abstractmethod
    def increment(self) -> None: ...

class NullJobSet(BaseJobSet):
    def started_job(self, name: str) -> None: ...
    def finished_job(self) -> None: ...
    def check_status(self) -> None: ...
    def get_percent_done(self) -> float | None: ...
    def increment(self) -> None: ...

class BaseTaskHandle(ABC):
    @abstractmethod
    def is_stopped(self) -> bool: ...
    @abstractmethod
    def stop(self) -> None: ...
    @abstractmethod
    def create_jobset(self, name: str = "", count: int = 0) -> BaseJobSet: ...
    @abstractmethod
    def get_jobsets(self) -> list[BaseJobSet]: ...

class NullTaskHandle(BaseTaskHandle):
    def is_stopped(self) -> bool: ...
    def stop(self) -> None: ...
    def create_jobset(self, name: str = "", count: int = 0) -> NullJobSet: ...
    def get_jobsets(self) -> list[BaseJobSet]: ...

DEFAULT_TASK_HANDLE: NullTaskHandle
DEFAULT_JOB_SET: NullJobSet
