from abc import ABC, abstractmethod
from collections.abc import Iterator, Mapping
from re import Pattern

_posix_variable: Pattern[str] = ...

class Atom(ABC):
    def __ne__(self, other: object) -> bool: ...
    @abstractmethod
    def resolve(self, env: Mapping[str, str | None]) -> str: ...

class Literal(Atom):
    def __init__(self, value: str) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def resolve(self, env: Mapping[str, str | None]) -> str: ...

class Variable(Atom):
    def __init__(self, name: str, default: str | None) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def resolve(self, env: Mapping[str, str | None]) -> str: ...

def parse_variables(value: str) -> Iterator[Atom]: ...
