from collections import OrderedDict, deque
from dataclasses import dataclass
from types import TracebackType
from typing import NamedTuple, TypeVar

from .._core._testing import TaskInfo
from ..abc import Event, ObjectReceiveStream, ObjectSendStream

T_Item = TypeVar("T_Item")
T_co = TypeVar("T_co", covariant=True)
T_contra = TypeVar("T_contra", contravariant=True)

class MemoryObjectStreamStatistics(NamedTuple):
    current_buffer_used: int
    max_buffer_size: float
    open_send_streams: int
    open_receive_streams: int
    tasks_waiting_send: int
    tasks_waiting_receive: int

@dataclass(eq=False)
class MemoryObjectItemReceiver[T_Item]:
    task_info: TaskInfo = ...
    item: T_Item = ...

@dataclass(eq=False)
class MemoryObjectStreamState[T_Item]:
    max_buffer_size: float = ...
    buffer: deque[T_Item] = ...
    open_send_channels: int = ...
    open_receive_channels: int = ...
    waiting_receivers: OrderedDict[Event, MemoryObjectItemReceiver[T_Item]] = ...
    waiting_senders: OrderedDict[Event, T_Item] = ...
    def statistics(self) -> MemoryObjectStreamStatistics: ...

@dataclass(eq=False)
class MemoryObjectReceiveStream[T_co](ObjectReceiveStream[T_co]):
    _state: MemoryObjectStreamState[T_co]
    _closed: bool = ...
    def __post_init__(self) -> None: ...
    def receive_nowait(self) -> T_co: ...
    async def receive(self) -> T_co: ...
    def clone(self) -> MemoryObjectReceiveStream[T_co]: ...
    def close(self) -> None: ...
    async def aclose(self) -> None: ...
    def statistics(self) -> MemoryObjectStreamStatistics: ...
    def __enter__(self) -> MemoryObjectReceiveStream[T_co]: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def __del__(self) -> None: ...

@dataclass(eq=False)
class MemoryObjectSendStream[T_contra](ObjectSendStream[T_contra]):
    _state: MemoryObjectStreamState[T_contra]
    _closed: bool = ...
    def __post_init__(self) -> None: ...
    def send_nowait(self, item: T_contra) -> None: ...
    async def send(self, item: T_contra) -> None: ...
    def clone(self) -> MemoryObjectSendStream[T_contra]: ...
    def close(self) -> None: ...
    async def aclose(self) -> None: ...
    def statistics(self) -> MemoryObjectStreamStatistics: ...
    def __enter__(self) -> MemoryObjectSendStream[T_contra]: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def __del__(self) -> None: ...
