from collections.abc import Callable
from typing import IO, Any

class _safe_key:
    __slots__ = ...
    def __init__(self, obj) -> None: ...
    def __lt__(self, other) -> bool: ...

class PrettyPrinter:
    def __init__(
        self, indent: int = ..., width: int = ..., depth: int | None = ...
    ) -> None: ...
    def pformat(self, object: Any) -> str: ...

    _dispatch: dict[
        Callable[..., str],
        Callable[[PrettyPrinter, Any, IO[str], int, int, set[int], int], None],
    ] = ...

_builtin_scalars = ...
