from collections.abc import Callable
from multiprocessing import Queue
from typing import TYPE_CHECKING

"""
This is a toolkit for determining which module set the "flush to zero" flag.

For details, see the docstring and comments in `identify_ftz_culprit()`.  This module
is defined outside the main Hypothesis namespace so that we can avoid triggering
import of Hypothesis itself from each subprocess which must import the worker function.
"""
if TYPE_CHECKING: ...
type FTZCulprits = tuple[bool | None, set[str]]
KNOWN_EVER_CULPRITS = ...

def flush_to_zero() -> bool: ...
def run_in_process(fn: Callable[..., FTZCulprits], *args: object) -> FTZCulprits: ...
def target(
    q: Queue[FTZCulprits], fn: Callable[..., FTZCulprits], *args: object
) -> None: ...
def always_imported_modules() -> FTZCulprits: ...
def modules_imported_by(mod: str) -> FTZCulprits: ...

KNOWN_FTZ = ...
CHECKED_CACHE = ...

def identify_ftz_culprits() -> str: ...

if __name__ == "__main__": ...
