"""
Package gopy provides Go bindings for Meltano functionality via gopy

"""
# python wrapper for package github.com/flext-sh/flext/internal/gopy within overall package gopy
# This is what you import to use the package.
# File is generated by gopy. Do not edit.
# gopy build -output=. -vm=python3 ../internal/gopy

# the following is required to enable dlopen to open the _go.so file
import collections
import inspect
import os

try:
	import collections.abc as _collections_abc
except ImportError:
	_collections_abc = collections

cwd = os.getcwd()
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
os.chdir(currentdir)
from . import _gopy, go

os.chdir(cwd)

# to use this code in your end-user python file, import it as follows:
# from gopy import gopy
# and then refer to everything using gopy. prefix
# packages imported by this package listed below:




# ---- Types ---

# Python type for map map[string]interface{}
class Map_string_interface_(go.GoClass):
	""""""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		otherwise parameter is a python list that we copy from
		"""
		self.index = 0
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_gopy.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_gopy.IncRef(self.handle)
		else:
			self.handle = _gopy.Map_string_interface__CTor()
			_gopy.IncRef(self.handle)
			if len(args) > 0:
				if not isinstance(args[0], _collections_abc.Mapping):
					raise TypeError('Map_string_interface_.__init__ takes a mapping as argument')
				for k, v in args[0].items():
					_gopy.Map_string_interface__set(self.handle, k, v)
	def __del__(self):
		_gopy.DecRef(self.handle)
	def __str__(self):
		s = 'gopy.Map_string_interface_ len: ' + str(len(self)) + ' handle: ' + str(self.handle) + ' {'
		if len(self) < 120:
			for k, v in self.items():
				s += str(k) + '=' + str(v) + ', '
		return s + '}'
	def __repr__(self):
		s = 'gopy.Map_string_interface_({'
		for k, v in self.items():
			s += str(k) + '=' + str(v) + ', '
		return s + '})'
	def __len__(self):
		return _gopy.Map_string_interface__len(self.handle)
	def __getitem__(self, key):
		return _gopy.Map_string_interface__elem(self.handle, key)
	def __setitem__(self, key, value):
		_gopy.Map_string_interface__set(self.handle, key, value)
	def __delitem__(self, key):
		return _gopy.Map_string_interface__delete(self.handle, key)
	def keys(self):
		return go.Slice_string(handle=_gopy.Map_string_interface__keys(self.handle))
	def values(self):
		vls = []
		kys = self.keys()
		for k in kys:
			vls.append(self[k])
		return vls
	def items(self):
		vls = []
		kys = self.keys()
		for k in kys:
			vls.append((k, self[k]))
		return vls
	def __iter__(self):
		return iter(self.items())
	def __contains__(self, key):
		return _gopy.Map_string_interface__contains(self.handle, key)


#---- Enums from Go (collections of consts with same type) ---


#---- Constants from Go: Python can only ask that you please don't change these! ---


# ---- Global Variables: can only use functions to access ---


# ---- Interfaces ---


# ---- Structs ---

# Python type for struct gopy.MeltanoAdapter
class MeltanoAdapter(go.GoClass):
	"""MeltanoAdapter provides a gopy-compatible interface to Meltano functionality\n"""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		otherwise parameters can be unnamed in order of field names or named fields
		in which case a new Go object is constructed first
		"""
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_gopy.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_gopy.IncRef(self.handle)
		else:
			self.handle = _gopy.gopy_MeltanoAdapter_CTor()
			_gopy.IncRef(self.handle)
	def __del__(self):
		_gopy.DecRef(self.handle)
	def __str__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'gopy.MeltanoAdapter{'
		first = True
		for v in pr:
			if callable(v[1]):
				continue
			if first:
				first = False
			else:
				sv += ', '
			sv += v[0] + '=' + str(v[1])
		return sv + '}'
	def __repr__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'gopy.MeltanoAdapter ( '
		for v in pr:
			if not callable(v[1]):
				sv += v[0] + '=' + str(v[1]) + ', '
		return sv + ')'
	def IsAvailable(self):
		"""IsAvailable() bool

		IsAvailable checks if Meltano is available in the system
		"""
		return _gopy.gopy_MeltanoAdapter_IsAvailable(self.handle)
	def InitProject(self, name, directory):
		"""InitProject(str name, str directory) str

		InitProject initializes a new Meltano project
		"""
		return _gopy.gopy_MeltanoAdapter_InitProject(self.handle, name, directory)
	def GetProjectInfo(self):
		"""GetProjectInfo() str

		GetProjectInfo retrieves information about the current project
		"""
		return _gopy.gopy_MeltanoAdapter_GetProjectInfo(self.handle)
	def AddPlugin(self, pluginType, name, variant):
		"""AddPlugin(str pluginType, str name, str variant) str

		AddPlugin adds a plugin to the project
		"""
		return _gopy.gopy_MeltanoAdapter_AddPlugin(self.handle, pluginType, name, variant)
	def InstallPlugins(self):
		"""InstallPlugins() str

		InstallPlugins installs all plugins in the project
		"""
		return _gopy.gopy_MeltanoAdapter_InstallPlugins(self.handle)
	def RunPipeline(self, extractor, loader, transformer):
		"""RunPipeline(str extractor, str loader, str transformer) str

		RunPipeline executes a Meltano pipeline
		"""
		return _gopy.gopy_MeltanoAdapter_RunPipeline(self.handle, extractor, loader, transformer)
	def ExecuteCommand(self, command, args):
		"""ExecuteCommand(str command, []str args) str

		ExecuteCommand executes a raw Meltano command
		"""
		return _gopy.gopy_MeltanoAdapter_ExecuteCommand(self.handle, command, args.handle)
	def GetPlugins(self):
		"""GetPlugins() str

		GetPlugins retrieves all plugins in the project
		"""
		return _gopy.gopy_MeltanoAdapter_GetPlugins(self.handle)
	def CreateAdapter(self, adapterType, config):
		"""CreateAdapter(str adapterType, object config) str

		CreateAdapter creates a new Meltano adapter
		"""
		return _gopy.gopy_MeltanoAdapter_CreateAdapter(self.handle, adapterType, config.handle)
	def ListProjects(self, rootDir):
		"""ListProjects(str rootDir) str

		ListProjects lists available Meltano projects
		"""
		return _gopy.gopy_MeltanoAdapter_ListProjects(self.handle, rootDir)
	def GetProcessPoolStats(self):
		"""GetProcessPoolStats() str

		GetProcessPoolStats returns statistics about the process pool
		"""
		return _gopy.gopy_MeltanoAdapter_GetProcessPoolStats(self.handle)
	def GetStateStats(self):
		"""GetStateStats() str

		GetStateStats returns state management statistics
		"""
		return _gopy.gopy_MeltanoAdapter_GetStateStats(self.handle)
	def SavePluginState(self, project, plugin, state):
		"""SavePluginState(str project, str plugin, object state) str

		SavePluginState saves state for a specific plugin
		"""
		return _gopy.gopy_MeltanoAdapter_SavePluginState(self.handle, project, plugin, state.handle)
	def LoadPluginState(self, project, plugin):
		"""LoadPluginState(str project, str plugin) str

		LoadPluginState loads state for a specific plugin
		"""
		return _gopy.gopy_MeltanoAdapter_LoadPluginState(self.handle, project, plugin)
	def DeletePluginState(self, project, plugin):
		"""DeletePluginState(str project, str plugin) str

		DeletePluginState deletes state for a specific plugin
		"""
		return _gopy.gopy_MeltanoAdapter_DeletePluginState(self.handle, project, plugin)
	def GetVersion(self):
		"""GetVersion() str

		GetVersion returns the version information
		"""
		return _gopy.gopy_MeltanoAdapter_GetVersion(self.handle)
	def Close(self):
		"""Close() str

		Close cleans up resources (for compatibility)
		"""
		return _gopy.gopy_MeltanoAdapter_Close(self.handle)

# Python type for struct gopy.ProjectInfo
class ProjectInfo(go.GoClass):
	"""ProjectInfo contains basic project information\n"""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		otherwise parameters can be unnamed in order of field names or named fields
		in which case a new Go object is constructed first
		"""
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_gopy.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_gopy.IncRef(self.handle)
		else:
			self.handle = _gopy.gopy_ProjectInfo_CTor()
			_gopy.IncRef(self.handle)
			if  0 < len(args):
				self.Name = args[0]
			if "Name" in kwargs:
				self.Name = kwargs["Name"]
			if  1 < len(args):
				self.Path = args[1]
			if "Path" in kwargs:
				self.Path = kwargs["Path"]
			if  2 < len(args):
				self.Environment = args[2]
			if "Environment" in kwargs:
				self.Environment = kwargs["Environment"]
	def __del__(self):
		_gopy.DecRef(self.handle)
	def __str__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'gopy.ProjectInfo{'
		first = True
		for v in pr:
			if callable(v[1]):
				continue
			if first:
				first = False
			else:
				sv += ', '
			sv += v[0] + '=' + str(v[1])
		return sv + '}'
	def __repr__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'gopy.ProjectInfo ( '
		for v in pr:
			if not callable(v[1]):
				sv += v[0] + '=' + str(v[1]) + ', '
		return sv + ')'
	@property
	def Name(self):
		return _gopy.gopy_ProjectInfo_Name_Get(self.handle)
	@Name.setter
	def Name(self, value):
		if isinstance(value, go.GoClass):
			_gopy.gopy_ProjectInfo_Name_Set(self.handle, value.handle)
		else:
			_gopy.gopy_ProjectInfo_Name_Set(self.handle, value)
	@property
	def Path(self):
		return _gopy.gopy_ProjectInfo_Path_Get(self.handle)
	@Path.setter
	def Path(self, value):
		if isinstance(value, go.GoClass):
			_gopy.gopy_ProjectInfo_Path_Set(self.handle, value.handle)
		else:
			_gopy.gopy_ProjectInfo_Path_Set(self.handle, value)
	@property
	def Environment(self):
		return _gopy.gopy_ProjectInfo_Environment_Get(self.handle)
	@Environment.setter
	def Environment(self, value):
		if isinstance(value, go.GoClass):
			_gopy.gopy_ProjectInfo_Environment_Set(self.handle, value.handle)
		else:
			_gopy.gopy_ProjectInfo_Environment_Set(self.handle, value)

# Python type for struct gopy.Result
class Result(go.GoClass):
	"""Result represents a standard result format for gopy compatibility\n"""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		otherwise parameters can be unnamed in order of field names or named fields
		in which case a new Go object is constructed first
		"""
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_gopy.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_gopy.IncRef(self.handle)
		else:
			self.handle = _gopy.gopy_Result_CTor()
			_gopy.IncRef(self.handle)
			if  0 < len(args):
				self.Success = args[0]
			if "Success" in kwargs:
				self.Success = kwargs["Success"]
			if  2 < len(args):
				self.Error = args[2]
			if "Error" in kwargs:
				self.Error = kwargs["Error"]
	def __del__(self):
		_gopy.DecRef(self.handle)
	def __str__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'gopy.Result{'
		first = True
		for v in pr:
			if callable(v[1]):
				continue
			if first:
				first = False
			else:
				sv += ', '
			sv += v[0] + '=' + str(v[1])
		return sv + '}'
	def __repr__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'gopy.Result ( '
		for v in pr:
			if not callable(v[1]):
				sv += v[0] + '=' + str(v[1]) + ', '
		return sv + ')'
	@property
	def Success(self):
		return _gopy.gopy_Result_Success_Get(self.handle)
	@Success.setter
	def Success(self, value):
		if isinstance(value, go.GoClass):
			_gopy.gopy_Result_Success_Set(self.handle, value.handle)
		else:
			_gopy.gopy_Result_Success_Set(self.handle, value)
	@property
	def Error(self):
		return _gopy.gopy_Result_Error_Get(self.handle)
	@Error.setter
	def Error(self, value):
		if isinstance(value, go.GoClass):
			_gopy.gopy_Result_Error_Set(self.handle, value.handle)
		else:
			_gopy.gopy_Result_Error_Set(self.handle, value)


# ---- Slices ---


# ---- Maps ---


# ---- Constructors ---
def NewMeltanoAdapter():
	"""NewMeltanoAdapter() object, str

	NewMeltanoAdapter creates a new Meltano adapter instance
	"""
	return MeltanoAdapter(handle=_gopy.gopy_NewMeltanoAdapter())
def QuickInit():
	"""QuickInit() object, str

	QuickInit initializes Meltano with auto-detection
	"""
	return MeltanoAdapter(handle=_gopy.gopy_QuickInit())
def NewMeltanoAdapterWithConfig(pythonPath, projectRoot):
	"""NewMeltanoAdapterWithConfig(str pythonPath, str projectRoot) object, str

	NewMeltanoAdapterWithConfig creates adapter with custom configuration
	"""
	return MeltanoAdapter(handle=_gopy.gopy_NewMeltanoAdapterWithConfig(pythonPath, projectRoot))
def QuickInitWithConfig(pythonPath, projectRoot):
	"""QuickInitWithConfig(str pythonPath, str projectRoot) object, str

	QuickInitWithConfig initializes Meltano with custom paths
	"""
	return MeltanoAdapter(handle=_gopy.gopy_QuickInitWithConfig(pythonPath, projectRoot))


# ---- Functions ---
def QuickCheck():
	"""QuickCheck() bool

	QuickCheck checks if Meltano is available (static function)
	"""
	return _gopy.gopy_QuickCheck()
def AddPluginToProject(pluginType, name, variant):
	"""AddPluginToProject(str pluginType, str name, str variant) str

	AddPluginToProject adds a plugin to an existing project
	"""
	return _gopy.gopy_AddPluginToProject(pluginType, name, variant)
def GetMeltanoVersion():
	"""GetMeltanoVersion() str

	GetMeltanoVersion returns Meltano version information
	"""
	return _gopy.gopy_GetMeltanoVersion()
def RunMeltanoPipeline(extractor, loader, transformer):
	"""RunMeltanoPipeline(str extractor, str loader, str transformer) str

	RunMeltanoPipeline runs a Meltano ELT pipeline
	"""
	return _gopy.gopy_RunMeltanoPipeline(extractor, loader, transformer)
def CheckMeltanoAvailable():
	"""CheckMeltanoAvailable() bool

	CheckMeltanoAvailable checks if Meltano CLI is available
	"""
	return _gopy.gopy_CheckMeltanoAvailable()
def CreateProject(directory, name):
	"""CreateProject(str directory, str name) str

	CreateProject creates a new Meltano project
	"""
	return _gopy.gopy_CreateProject(directory, name)
def ExecuteMeltanoCommand(command, args):
	"""ExecuteMeltanoCommand(str command, []str args) str

	ExecuteMeltanoCommand executes a raw Meltano CLI command
	"""
	return _gopy.gopy_ExecuteMeltanoCommand(command, args.handle)
def GetProjectPlugins():
	"""GetProjectPlugins() str

	GetProjectPlugins lists all plugins in the current project
	"""
	return _gopy.gopy_GetProjectPlugins()


