from pathlib import Path

class OracleE2ETestManager:
    workspace_path: Path

    def __init__(self, workspace_path: Path) -> None: ...
    def run_e2e_tests(self, **kwargs: object) -> dict[str, object]: ...
    def validate_test_environment(self) -> bool: ...
    def cleanup_test_artifacts(self) -> None: ...
