#!/usr/bin/env python3
"""Live Git Commit Rewriter - Process commits one by one with immediate feedback.

Rewrites git commit history to:
- Remove AI references (Claude, Codex, Cursor, etc.)
- Normalize author to Marlon Costa <marlonsc@gmail.com>
- Improve commit messages based on patch analysis

Usage:
    python3 scripts/git_rewrite_live_one_by_one.py --repo /path/to/repo [--limit N]
"""

import argparse
import re
import sys
from pathlib import Path


class LiveGitRewriter:
    """Live git history rewriter with real-time feedback."""

    AUTHOR_NAME = "Marlon Costa"
    AUTHOR_EMAIL = "marlonsc@gmail.com"

    AI_PATTERNS = [
        r"🤖 Generated with \[Claude Code\].*",
        r"Co-Authored-By: Claude.*",
        r"Co-Authored-By: Codex.*",
        r"Co-Authored-By: Cursor.*",
        r"Generated by Claude.*",
        r"Generated by Codex.*",
        r"Generated by Cursor.*",
        r"Claude Code.*",
        r"\[Claude Code\].*",
        r"\[Codex\].*",
        r"\[Cursor\].*",
        r"With assistance from.*",
        r"AI-assisted.*",
        r"noreply@anthropic\.com",
    ]

    def __init__(self, repo_path: Path, limit: int | None = None) -> None:
        """Initialize rewriter."""
        self.repo_path = repo_path.resolve()
        self.limit = limit
        self.processed = 0

    def clean_message(self, message: str) -> str:
        """Remove AI references and clean up message."""
        cleaned = message
        for pattern in self.AI_PATTERNS:
            cleaned = re.sub(pattern, "", cleaned, flags=re.IGNORECASE | re.MULTILINE)

        # Clean up multiple newlines and trailing whitespace
        lines = [line.strip() for line in cleaned.split("\n") if line.strip()]
        return "\n".join(lines).strip()

    def generate_callback_script(self) -> str:
        """Generate the git-filter-repo callback script."""
        patterns_list = ",\n".join([f'        r"{p}"' for p in self.AI_PATTERNS])

        return f'''#!/usr/bin/env python3
import re
import subprocessFlextLDAPModels
import sys

# Global variables for the callback
AUTHOR_NAME = b"{self.AUTHOR_NAME}"
AUTHOR_EMAIL = b"{self.AUTHOR_EMAIL}"

AI_PATTERNS = [
{patterns_list}
]

def clean_ai_refs(msg_bytes):
    """Remove AI references from commit message."""
    try:
        msg = msg_bytes.decode('utf-8', errors='ignore')
        for pattern in AI_PATTERNS:
            msg = re.sub(pattern, "", msg, flags=re.IGNORECASE | re.MULTILINE)
        lines = [line.strip() for line in msg.split('\\n') if line.strip()]
        return '\\n'.join(lines).encode('utf-8')
    except Exception:
        return msg_bytes

def callback(commit, metadata):
    """Main callback function for git-filter-repo."""
    global commit_count

    # Update commit message
    original_msg = commit.message.decode('utf-8', errors='ignore').strip()
    cleaned_msg = clean_ai_refs(original_msg.encode('utf-8')).decode('utf-8', errors='ignore')

    if cleaned_msg != original_msg:
        commit.message = cleaned_msg.encode('utf-8')
        print(f"Cleaned: {{original_msg[:50]}}... -> {{cleaned_msg[:50]}}...")
    else:
        print(f"Kept: {{original_msg[:50]}}...")

    # Normalize author
    commit.author_name = AUTHOR_NAME
    commit.author_email = AUTHOR_EMAIL
    commit.committer_name = AUTHOR_NAME
    commit.committer_email = AUTHOR_EMAIL

    return commit

# Set up global counter for the callback
commit_count = 0

# This is required for git-filter-repo to find the callback function
if __name__ == "__main__":
    # When executed directly by git-filter-repo, this should not run
    pass
'''

    def run(self) -> None:
        """Execute the git history rewrite."""
        print("🔧 REWRITING COMMITS ONE BY ONE")
        print("=" * 50)
        print(f"Repository: {self.repo_path}")
        print(f"Author: {self.AUTHOR_NAME} <{self.AUTHOR_EMAIL}>")
        print()

        # Create temporary callback script file
        callback_script_path = self.repo_path / ".git" / "filter_callback.py"
        callback_script_path.write_text(self.generate_callback_script())
        callback_script_path.chmod(0o755)

        try:
            # Use git-filter-repo with the callback script file
            cmd = [
                "git-filter-repo",
                "--force",
                "--commit-callback",
                str(callback_script_path),
                "--refs",
                "HEAD",
            ]

            if self.limit:
                cmd.extend(["--max-commits", str(self.limit)])

            # Execute the command
            result = subprocess.run(
                cmd, check=False, cwd=self.repo_path, capture_output=True, text=True
            )

            # Clean up the temporary script
            if callback_script_path.exists():
                callback_script_path.unlink()

            if result.returncode != 0:
                print(f"❌ git-filter-repo failed: {result.stderr}")
                sys.exit(1)

            print("✅ Git history rewrite completed successfully!")

        except FileNotFoundError:
            print(
                "❌ git-filter-repo not found. Install it with: pip install git-filter-repo"
            )
            sys.exit(1)
        except Exception as e:
            print(f"❌ Error during rewrite: {e}")
            sys.exit(1)


def main() -> None:
    """Main entry point."""
    parser = argparse.ArgumentParser(description="Rewrite git history live")
    parser.add_argument("--repo", default=".", help="Repository path")
    parser.add_argument("--limit", type=int, help="Limit number of commits to process")

    args = parser.parse_args()

    repo_path = Path(args.repo).resolve()
    if not repo_path.exists():
        print(f"❌ Repository not found: {repo_path}")
        sys.exit(1)

    if not (repo_path / ".git").exists():
        print(f"❌ Not a git repository: {repo_path}")
        sys.exit(1)

    rewriter = LiveGitRewriter(repo_path, args.limit)
    rewriter.run()


if __name__ == "__main__":
    main()
