#!/usr/bin/env python3
"""
FLEXT Git Ultimate Cleanup - THE ONLY SCRIPT YOU NEED

Complete repository cleanup with maximum safety:
- External backup (tar.gz + git mirror)
- Cruft removal from git history
- Commit message rewriting
- Author normalization to Marlon Costa
- AI reference removal
- Remote restoration
- GitHub push/sync
- All safety guards and validation

Usage:
    python3 scripts/git_ultimate_cleanup.py --test                # Test all functions
    python3 scripts/git_ultimate_cleanup.py --detect-cruft        # Detect additional cruft
    python3 scripts/git_ultimate_cleanup.py --dry-run             # Simulate cleanup
    python3 scripts/git_ultimate_cleanup.py                       # Main repo
    python3 scripts/git_ultimate_cleanup.py --all                 # Main + submodules
    python3 scripts/git_ultimate_cleanup.py --push                # Cleanup + push main
    python3 scripts/git_ultimate_cleanup.py --all --push-all      # All + push all
    python3 scripts/git_ultimate_cleanup.py --backup-only         # Just backup
    python3 scripts/git_ultimate_cleanup.py --restore-remotes     # Just restore remotes
"""

import argparse
import re
import shutil
import subprocess
import sys
import tarfile
from datetime import datetime
from pathlib import Path


class GitUltimateCleanup:
    """The ultimate unified git cleanup system."""

    AUTHOR_NAME = "Marlon Costa"
    AUTHOR_EMAIL = "marlonsc@gmail.com"

    # Cruft patterns to remove from git history
    CRUFT_PATTERNS = [
        # Build artifacts
        "*.pyc", "*.pyo", "*.py[cod]", "*$py.class",
        "__pycache__/", "dist/", "build/", "*.egg-info/",
        # Cache directories
        ".ruff_cache/", ".mypy_cache/", ".pytest_cache/", ".serena/cache/", ".serena/",
        # Coverage reports
        ".coverage", "htmlcov/", ".tox/", ".benchmarks/",
        # Log files
        "*.log", ".meltano/logs/",
        # Backup files
        "*.backup", "*.bak", "*.orig", "*~", ".*.swp",
        "*.syntax_backup", "*.broken", "*.tmp.bak",
        "*_backup", "*_backup_*", "temp_backup",
        # Temporary/debug scripts and files
        "temp_*.py", "*_temp.py", "*_temp.md",
        "fix_*.py", "*_fix.py",
        "debug_*.py", "investigate_*.py", "validate_*.py",
        "*_analysis.txt", "*_output.txt", "*_report.txt",
        "temp_test_*", "analysis_temp/", "report_*/", "reports_*/",
        # OS-specific
        ".DS_Store", "Thumbs.db",
        # AI/IDE config and reports
        "CLAUDE*.md", ".cursor/", ".vscode/", ".idea/",
        "*_report.md", "*_analysis.md", "*_summary.md",
        "*_REPORT*.md", "*_ANALYSIS*.md", "*_SUMMARY*.md", "*_FINDINGS*.md",
        "CONFIG_MIGRATION*.md", "DEVELOPMENT_STANDARDS*.md",
        "DUPLICATION_REPORT*.md", "LINT_CORRECTIONS*.md",
        "*.ai.md", "*.ai.txt",
        # Archive directories
        ".archive/", "archive/", "archives/", "backups/",
        # Large data files
        "*.db", "*.sqlite", "*.sqlite3", "output_files/", "data_buffers/",
        "*.tar", "*.tar.gz", "*.zip", "*backup*/", "submodule_cleanup_backup/",
        "sync_control.db",  # Large database file
        # Timestamped documentation (AI-generated)
        "*.md_20250*",
    ]

    AI_PATTERNS = [
        r"🤖 Generated with \[Claude Code\].*",
        r"Co-Authored-By:\s*Claude.*",
        r"Co-Authored-By:\s*Codex.*",
        r"Co-Authored-By:\s*Cursor.*",
        r"Generated by Claude.*",
        r"Generated by Codex.*",
        r"Generated by Cursor.*",
        r"Claude Code.*",
        r"\[Claude Code\].*",
        r"\[Codex\].*",
        r"\[Cursor\].*",
        r"With assistance from.*",
        r"AI-assisted.*",
        r"noreply@anthropic\.com.*",
    ]

    def __init__(self, repo_path: Path, dry_run: bool = False):
        self.repo_path = repo_path.resolve()
        self.timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        self.backup_root = Path.home() / f"flext-ultimate-backup-{self.timestamp}"
        self.dry_run = dry_run

    def validate_repository(self) -> tuple[bool, str]:
        """Comprehensive repository validation."""
        # Check if git repo
        if not (self.repo_path / ".git").exists():
            return False, f"Not a git repository: {self.repo_path}"

        # Check uncommitted changes (skip in dry-run mode)
        if not self.dry_run:
            result = subprocess.run(
                ["git", "-C", str(self.repo_path), "status", "--porcelain"],
                capture_output=True, text=True, check=False
            )
            if result.stdout.strip():
                return False, "Uncommitted changes detected. Commit or stash first."

        # Check git-filter-repo
        result = subprocess.run(["which", "git-filter-repo"], capture_output=True, check=False)
        if result.returncode != 0:
            return False, "git-filter-repo not installed. Run: pip install git-filter-repo"

        # Check not detached HEAD
        result = subprocess.run(
            ["git", "-C", str(self.repo_path), "symbolic-ref", "-q", "HEAD"],
            capture_output=True, check=False
        )
        if result.returncode != 0:
            return False, "Detached HEAD state. Checkout a branch first."

        # Check disk space
        result = subprocess.run(["df", "-h", str(self.repo_path)], capture_output=True, text=True, check=False)
        if result.returncode == 0:
            lines = result.stdout.strip().split('\n')
            if len(lines) > 1:
                avail = lines[1].split()[3]
                print(f"   💾 Available disk space: {avail}")

        return True, "✅ All validation checks passed"

    def create_comprehensive_backup(self) -> Path:
        """Create complete external backup with multiple safety layers."""
        print(f"\n{'='*70}")
        print("📦 CREATING COMPREHENSIVE BACKUP")
        print(f"{'='*70}\n")

        self.backup_root.mkdir(parents=True, exist_ok=True)
        repo_backup = self.backup_root / self.repo_path.name
        repo_backup.mkdir(parents=True, exist_ok=True)

        print(f"Backup location: {self.backup_root}")
        print()

        # 1. Create tar.gz archive
        print("1️⃣  Creating tar.gz archive...")
        tar_file = repo_backup / f"{self.repo_path.name}.tar.gz"

        with tarfile.open(tar_file, "w:gz") as tar:
            tar.add(
                self.repo_path,
                arcname=self.repo_path.name,
                filter=lambda t: None if any([
                    "__pycache__" in t.name, ".pyc" in t.name,
                    ".ruff_cache" in t.name, ".mypy_cache" in t.name,
                    ".pytest_cache" in t.name, "htmlcov" in t.name,
                ]) else t
            )

        size_mb = tar_file.stat().st_size / (1024 * 1024)
        print(f"   ✅ Archive created: {size_mb:.1f}MB")

        # 2. Create git mirror clone
        print("2️⃣  Creating git mirror clone...")
        mirror_path = repo_backup / f"{self.repo_path.name}.git"
        result = subprocess.run(
            ["git", "clone", "--mirror", str(self.repo_path), str(mirror_path)],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            print("   ✅ Mirror clone created")
        else:
            print(f"   ⚠️  Mirror clone failed: {result.stderr}")

        # 3. Export commit history
        print("3️⃣  Exporting commit history...")
        history_file = repo_backup / "commit-history.txt"
        result = subprocess.run(
            ["git", "-C", str(self.repo_path), "log", "--all", "--format=%H|%an|%ae|%ad|%s", "--date=iso"],
            capture_output=True, text=True, check=False
        )
        if result.returncode == 0:
            history_file.write_text(result.stdout)
            lines = len(result.stdout.strip().split('\n'))
            print(f"   ✅ Exported {lines} commits")

        # 4. Export reflog
        print("4️⃣  Exporting reflog...")
        reflog_file = repo_backup / "reflog.txt"
        result = subprocess.run(
            ["git", "-C", str(self.repo_path), "reflog", "--format=%H|%gd|%gs"],
            capture_output=True, text=True, check=False
        )
        if result.returncode == 0:
            reflog_file.write_text(result.stdout)
            print("   ✅ Reflog exported")

        # 5. Export branch info
        print("5️⃣  Exporting branch information...")
        branch_file = repo_backup / "branches.txt"
        result = subprocess.run(
            ["git", "-C", str(self.repo_path), "branch", "-a"],
            capture_output=True, text=True, check=False
        )
        if result.returncode == 0:
            branch_file.write_text(result.stdout)
            print("   ✅ Branch info exported")

        # 6. Export tags
        print("6️⃣  Exporting tags...")
        tags_file = repo_backup / "tags.txt"
        result = subprocess.run(
            ["git", "-C", str(self.repo_path), "tag", "-l"],
            capture_output=True, text=True, check=False
        )
        if result.returncode == 0:
            tags_file.write_text(result.stdout)
            print("   ✅ Tags exported")

        # 7. Create safety tag in repo
        print("7️⃣  Creating safety tag in repository...")
        safety_tag = f"pre-cleanup-{self.timestamp}"
        subprocess.run(
            ["git", "-C", str(self.repo_path), "tag", safety_tag],
            check=False, capture_output=True
        )
        print(f"   ✅ Tag created: {safety_tag}")

        # 8. Create recovery script
        print("8️⃣  Creating recovery script...")
        self._create_recovery_script(repo_backup, safety_tag, tar_file, mirror_path)
        print("   ✅ Recovery script created")

        print(f"\n✅ Comprehensive backup complete!")
        print(f"   Location: {repo_backup}")
        print()

        return self.backup_root

    def _create_recovery_script(self, backup_dir: Path, safety_tag: str, tar_file: Path, mirror_path: Path):
        """Create recovery script."""
        script = backup_dir / "RECOVER.sh"
        script.write_text(f'''#!/bin/bash
# FLEXT Repository Recovery Script
# Created: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
# Source: {self.repo_path}

set -e

echo "==================================================================="
echo "FLEXT Repository Recovery"
echo "==================================================================="
echo ""

# Recovery options
echo "Select recovery method:"
echo "  1) Reset to safety tag (fastest, preserves local changes)"
echo "  2) Restore from tar.gz (complete restore)"
echo "  3) Restore from mirror clone (preserves all git data)"
echo ""
read -p "Enter choice (1-3): " choice

case $choice in
    1)
        echo "Resetting to safety tag: {safety_tag}"
        cd {self.repo_path}
        git reset --hard {safety_tag}
        echo "✅ Repository reset to {safety_tag}"
        ;;
    2)
        echo "Extracting from tar.gz..."
        read -p "Extract to (default: {self.repo_path.parent}): " extract_path
        extract_path=${{extract_path:-{self.repo_path.parent}}}
        tar -xzf {tar_file} -C "$extract_path"
        echo "✅ Extracted to: $extract_path/{self.repo_path.name}"
        ;;
    3)
        echo "Restoring from mirror clone..."
        read -p "Restore to (default: {self.repo_path.parent}/{self.repo_path.name}-restored): " restore_path
        restore_path=${{restore_path:-{self.repo_path.parent}/{self.repo_path.name}-restored}}
        git clone {mirror_path} "$restore_path"
        echo "✅ Restored to: $restore_path"
        ;;
    *)
        echo "Invalid choice"
        exit 1
        ;;
esac

echo ""
echo "Recovery complete!"
''')
        script.chmod(0o755)

        # Create README
        readme = backup_dir / "README.md"
        readme.write_text(f'''# FLEXT Ultimate Backup

## Backup Information
- **Created**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
- **Source**: {self.repo_path}
- **Safety Tag**: {safety_tag}

## Contents
- `{tar_file.name}` - Complete tar.gz archive
- `{mirror_path.name}/` - Git mirror clone
- `commit-history.txt` - All commit history
- `reflog.txt` - Git reflog
- `branches.txt` - Branch information
- `tags.txt` - All tags
- `RECOVER.sh` - Recovery script

## Quick Recovery

### Option 1: Reset to Safety Tag (Fastest)
```bash
cd {self.repo_path}
git reset --hard {safety_tag}
```

### Option 2: Use Recovery Script
```bash
cd {backup_dir}
./RECOVER.sh
```

### Option 3: Manual Restore
```bash
tar -xzf {tar_file} -C /path/to/restore/
```

## Verification
```bash
# Check backup integrity
tar -tzf {tar_file.name} | head -20

# View backup size
du -sh {tar_file.name}

# Check commit count
wc -l commit-history.txt
```

## Important Notes
- This backup is EXTERNAL to git (will survive filter-repo)
- Multiple recovery options available
- Safety tag created in repository: {safety_tag}
- Keep this backup until cleanup is verified!
''')

    def test_principal_functions(self) -> bool:
        """Test all principal functions without modifying anything."""
        print(f"\n{'='*70}")
        print("🧪 DRY RUN TEST - VALIDATING FUNCTIONS")
        print(f"{'='*70}\n")

        tests_passed = 0
        tests_failed = 0

        # Test 1: Repository validation
        print("Test 1: Repository validation...")
        valid, msg = self.validate_repository()
        if valid:
            print(f"  ✅ PASS: {msg}")
            tests_passed += 1
        else:
            print(f"  ❌ FAIL: {msg}")
            tests_failed += 1

        # Test 2: Git directory detection
        print("Test 2: Git directory detection...")
        try:
            git_dir = self._get_git_dir()
            if git_dir.exists():
                print(f"  ✅ PASS: Found git dir at {git_dir}")
                tests_passed += 1
            else:
                print(f"  ❌ FAIL: Git dir not found")
                tests_failed += 1
        except Exception as e:
            print(f"  ❌ FAIL: {e}")
            tests_failed += 1

        # Test 3: Cruft pattern validation
        print("Test 3: Cruft pattern validation...")
        print(f"  ℹ️  {len(self.CRUFT_PATTERNS)} patterns configured")
        print(f"  ✅ PASS: Cruft patterns loaded")
        tests_passed += 1

        # Test 4: AI pattern validation
        print("Test 4: AI pattern validation...")
        print(f"  ℹ️  {len(self.AI_PATTERNS)} AI patterns configured")
        test_msg = "Co-Authored-By: Claude <claude@anthropic.com>"
        cleaned = test_msg
        for pattern in self.AI_PATTERNS:
            cleaned = re.sub(pattern, "", cleaned, flags=re.IGNORECASE | re.MULTILINE)
        if cleaned != test_msg:
            print(f"  ✅ PASS: AI patterns working")
            tests_passed += 1
        else:
            print(f"  ❌ FAIL: AI patterns not working")
            tests_failed += 1

        # Test 5: Submodule detection
        print("Test 5: Submodule detection...")
        submodules = self.get_submodules()
        print(f"  ℹ️  Found {len(submodules)} submodules")
        print(f"  ✅ PASS: Submodule detection working")
        tests_passed += 1

        # Test 6: Remote configuration
        print("Test 6: Remote configuration from .gitmodules...")
        gitmodules = self.repo_path / ".gitmodules"
        if gitmodules.exists():
            print(f"  ✅ PASS: .gitmodules found")
            tests_passed += 1
        else:
            print(f"  ⚠️  WARN: No .gitmodules (might be standalone repo)")
            tests_passed += 1

        # Test 7: Backup directory creation
        print("Test 7: Backup directory access...")
        try:
            test_backup = Path.home() / f"flext-test-{self.timestamp}"
            test_backup.mkdir(parents=True, exist_ok=True)
            test_backup.rmdir()
            print(f"  ✅ PASS: Can create backup directory")
            tests_passed += 1
        except Exception as e:
            print(f"  ❌ FAIL: {e}")
            tests_failed += 1

        # Test 8: Git commands availability
        print("Test 8: Git commands availability...")
        commands = ["git", "git-filter-repo", "tar"]
        all_available = True
        for cmd in commands:
            result = subprocess.run(["which", cmd], capture_output=True)
            if result.returncode != 0:
                print(f"  ❌ FAIL: {cmd} not found")
                all_available = False
        if all_available:
            print(f"  ✅ PASS: All required commands available")
            tests_passed += 1
        else:
            tests_failed += 1

        # Summary
        print(f"\n{'='*70}")
        print(f"Test Results: {tests_passed} passed, {tests_failed} failed")
        print(f"{'='*70}\n")

        if tests_failed > 0:
            print("❌ Some tests failed. Fix issues before running cleanup.")
            return False

        print("✅ All tests passed! Safe to proceed with cleanup.")
        return True

    def cleanup_repository(self) -> bool:
        """Execute complete repository cleanup."""
        print(f"\n{'='*70}")
        print(f"🔧 CLEANING: {self.repo_path.name}")
        print(f"{'='*70}\n")

        if self.dry_run:
            print("🧪 DRY RUN MODE - Simulating operations...")
            print()
            print("Would perform:")
            print(f"  🧹 Remove {len(self.CRUFT_PATTERNS)} cruft patterns from history")
            print(f"  🚫 Clean AI references from all commits")
            print(f"  ✍️  Normalize all authors to: {self.AUTHOR_NAME} <{self.AUTHOR_EMAIL}>")
            print()
            print("✅ Dry run complete (no changes made)")
            return True

        # Create filter script
        callback_script = self._create_filter_script()
        cruft_file = self._create_cruft_file()

        # Build command
        cmd = [
            "git", "filter-repo", "--force",
            "--commit-callback", str(callback_script),
            "--invert-paths", "--paths-from-file", str(cruft_file),
        ]

        # Add mailmap
        mailmap = self.repo_path / ".mailmap"
        if mailmap.exists():
            cmd.extend(["--mailmap", str(mailmap)])

        # Show what we're doing
        print("Operations:")
        print(f"  🧹 Removing {len(self.CRUFT_PATTERNS)} cruft patterns")
        print(f"  🚫 Cleaning AI references")
        print(f"  ✍️  Normalizing author: {self.AUTHOR_NAME} <{self.AUTHOR_EMAIL}>")
        print()

        # Execute
        print("Processing commits...")
        try:
            result = subprocess.run(cmd, cwd=str(self.repo_path))

            if result.returncode != 0:
                print(f"\n❌ Cleanup failed!")
                print(f"   Recover: cd {self.backup_root} && ./RECOVER.sh")
                return False

        except KeyboardInterrupt:
            print(f"\n\n❌ INTERRUPTED!")
            print(f"   Recover: cd {self.backup_root} && ./RECOVER.sh")
            return False

        finally:
            callback_script.unlink(missing_ok=True)
            cruft_file.unlink(missing_ok=True)

        # Verify
        result = subprocess.run(
            ["git", "-C", str(self.repo_path), "log", "-1", "--format=%an %ae"],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            author = result.stdout.strip()
            if self.AUTHOR_NAME not in author:
                print(f"\n⚠️  Author verification failed: {author}")

        # Show statistics
        result = subprocess.run(
            ["git", "-C", str(self.repo_path), "count-objects", "-vH"],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            print(f"\n📊 Repository statistics:")
            for line in result.stdout.strip().split('\n')[:5]:
                print(f"   {line}")

        print(f"\n✅ {self.repo_path.name} cleaned successfully!")
        print()

        return True

    def _create_filter_script(self) -> Path:
        """Create git-filter-repo callback script."""
        patterns_str = ",\n".join([f'        r"{p}"' for p in self.AI_PATTERNS])

        script = f'''#!/usr/bin/env python3
import re

commit_count = 0

AI_PATTERNS = [
{patterns_str}
]

AUTHOR_NAME = b"{self.AUTHOR_NAME}"
AUTHOR_EMAIL = b"{self.AUTHOR_EMAIL}"

def clean_ai_refs(msg_bytes):
    msg = msg_bytes.decode('utf-8', errors='ignore')
    for pattern in AI_PATTERNS:
        msg = re.sub(pattern, "", msg, flags=re.IGNORECASE | re.MULTILINE)
    lines = [line.strip() for line in msg.split('\\n') if line.strip()]
    return '\\n'.join(lines).encode('utf-8')

def callback(commit, metadata):
    global commit_count
    commit_count += 1

    original = commit.message.decode('utf-8', errors='ignore').strip()
    subject = original.split('\\n')[0]

    print(f"[{{commit_count}}] {{commit.original_id.decode()[:8]}}: {{subject[:60]}}", flush=True)

    commit.message = clean_ai_refs(original.encode('utf-8'))
    commit.author_name = AUTHOR_NAME
    commit.author_email = AUTHOR_EMAIL
    commit.committer_name = AUTHOR_NAME
    commit.committer_email = AUTHOR_EMAIL
'''

        git_dir = self._get_git_dir()
        script_path = git_dir / "ultimate-cleanup.py"
        script_path.write_text(script)
        script_path.chmod(0o755)
        return script_path

    def _create_cruft_file(self) -> Path:
        """Create cruft patterns file."""
        git_dir = self._get_git_dir()
        cruft_file = git_dir / "cruft-patterns.txt"
        cruft_file.write_text("\n".join([f"glob:{p}" for p in self.CRUFT_PATTERNS]))
        return cruft_file

    def _get_git_dir(self) -> Path:
        """Get actual .git directory."""
        git_path = self.repo_path / ".git"
        if git_path.is_file():
            gitdir_line = git_path.read_text().strip()
            if gitdir_line.startswith("gitdir: "):
                return (self.repo_path / gitdir_line[8:]).resolve()
        return git_path

    def restore_remotes(self) -> None:
        """Restore git remotes from .gitmodules."""
        print(f"\n{'='*70}")
        print("🔗 RESTORING REMOTES")
        print(f"{'='*70}\n")

        # Main repo
        main_remote = "git@github.com:flext-sh/flext.git"
        subprocess.run(
            ["git", "-C", str(self.repo_path), "remote", "add", "origin", main_remote],
            check=False, capture_output=True
        )
        print(f"✅ Main: {main_remote}")

        # Submodules
        gitmodules = self.repo_path / ".gitmodules"
        if not gitmodules.exists():
            print()
            return

        result = subprocess.run(
            ["git", "config", "-f", str(gitmodules), "--get-regexp", r"\.path$"],
            capture_output=True, text=True
        )

        if result.returncode != 0:
            print()
            return

        for line in result.stdout.strip().split('\n'):
            if not line:
                continue

            key, path = line.split()
            name = key.split('.')[1]

            url_result = subprocess.run(
                ["git", "config", "-f", str(gitmodules), f"submodule.{name}.url"],
                capture_output=True, text=True
            )

            if url_result.returncode != 0:
                continue

            url = url_result.stdout.strip()
            submodule_path = self.repo_path / path

            if submodule_path.exists():
                subprocess.run(
                    ["git", "-C", str(submodule_path), "remote", "add", "origin", url],
                    check=False, capture_output=True
                )
                print(f"✅ {path}")

        print()

    def get_submodules(self) -> list[Path]:
        """Get all submodule paths."""
        gitmodules = self.repo_path / ".gitmodules"
        if not gitmodules.exists():
            return []

        result = subprocess.run(
            ["git", "config", "-f", str(gitmodules), "--get-regexp", r"\.path$"],
            capture_output=True, text=True
        )

        if result.returncode != 0:
            return []

        submodules = []
        for line in result.stdout.strip().split('\n'):
            if not line:
                continue
            path = line.split()[1]
            submodule_path = self.repo_path / path
            if submodule_path.exists():
                submodules.append(submodule_path)

        return submodules

    def push_to_github(self, push_tags: bool = True) -> bool:
        """Push repository to GitHub with force."""
        print(f"\n{'='*70}")
        print(f"🚀 PUSHING TO GITHUB: {self.repo_path.name}")
        print(f"{'='*70}\n")

        if self.dry_run:
            print("🧪 DRY RUN MODE - Would push:")
            print(f"  📤 Force push all branches")
            if push_tags:
                print(f"  🏷️  Force push all tags")
            print()
            return True

        # Check if remote exists
        result = subprocess.run(
            ["git", "-C", str(self.repo_path), "remote", "get-url", "origin"],
            capture_output=True, text=True
        )

        if result.returncode != 0:
            print("❌ No remote 'origin' found. Run --restore-remotes first.")
            return False

        remote_url = result.stdout.strip()
        print(f"Remote: {remote_url}")
        print()

        # Safety confirmation
        print("⚠️  WARNING: This will FORCE PUSH to GitHub!")
        print("   This will overwrite remote history with local changes.")
        response = input("Continue? (yes/NO): ")
        if response.lower() != "yes":
            print("Cancelled.")
            return False

        # Push branches
        print("📤 Pushing all branches...")
        result = subprocess.run(
            ["git", "-C", str(self.repo_path), "push", "origin", "--force", "--all"],
            capture_output=True, text=True
        )

        if result.returncode != 0:
            print(f"❌ Push failed: {result.stderr}")
            return False

        print("   ✅ Branches pushed")

        # Push tags
        if push_tags:
            print("🏷️  Pushing all tags...")
            result = subprocess.run(
                ["git", "-C", str(self.repo_path), "push", "origin", "--force", "--tags"],
                capture_output=True, text=True
            )

            if result.returncode != 0:
                print(f"   ⚠️  Tag push failed: {result.stderr}")
            else:
                print("   ✅ Tags pushed")

        print(f"\n✅ {self.repo_path.name} pushed successfully!")
        print()
        return True

    def push_all_submodules(self) -> bool:
        """Push all submodules to GitHub."""
        submodules = self.get_submodules()

        if not submodules:
            print("ℹ️  No submodules to push")
            return True

        print(f"\n{'='*70}")
        print(f"📦 PUSHING SUBMODULES ({len(submodules)} total)")
        print(f"{'='*70}\n")

        if self.dry_run:
            print("🧪 DRY RUN MODE - Would push:")
            for submodule in submodules:
                print(f"  📤 {submodule.name}")
            print()
            return True

        failed = []
        for submodule in submodules:
            sub_cleanup = GitUltimateCleanup(submodule, dry_run=self.dry_run)
            if not sub_cleanup.push_to_github(push_tags=True):
                failed.append(submodule.name)

        if failed:
            print(f"\n⚠️  Failed to push {len(failed)} submodules:")
            for name in failed:
                print(f"   ❌ {name}")
            return False

        print(f"\n✅ All {len(submodules)} submodules pushed!")
        return True

    def analyze_gitignore(self) -> list[str]:
        """Parse .gitignore and extract patterns that might indicate committed cruft."""
        gitignore_path = self.repo_path / ".gitignore"
        if not gitignore_path.exists():
            return []

        patterns = []
        content = gitignore_path.read_text()

        for line in content.split('\n'):
            line = line.strip()
            # Skip comments and empty lines
            if not line or line.startswith('#'):
                continue
            # Skip negation patterns
            if line.startswith('!'):
                continue
            # Clean up the pattern
            pattern = line.rstrip('/')
            if pattern:
                patterns.append(pattern)

        return patterns

    def analyze_historical_removals(self) -> dict[str, int]:
        """Analyze git history to find frequently deleted files (likely cruft)."""
        result = subprocess.run(
            ["git", "-C", str(self.repo_path), "log", "--all", "--diff-filter=D", "--name-only", "--format="],
            capture_output=True, text=True, check=False
        )

        if result.returncode != 0:
            return {}

        # Count deletion frequency
        deletion_counts = {}
        for line in result.stdout.strip().split('\n'):
            if not line:
                continue
            deletion_counts[line] = deletion_counts.get(line, 0) + 1

        return deletion_counts

    def detect_additional_cruft(self) -> dict[str, list[str]]:
        """Detect additional cruft patterns from git history and .gitignore."""
        print(f"\n{'='*70}")
        print("🔍 DETECTING ADDITIONAL CRUFT PATTERNS")
        print(f"{'='*70}\n")

        detected = {
            'gitignore_patterns': [],
            'historical_removals': [],
            'recommended_patterns': []
        }

        # 1. Analyze .gitignore
        print("1️⃣  Analyzing .gitignore patterns...")
        gitignore_patterns = self.analyze_gitignore()

        # Find patterns in .gitignore that aren't in CRUFT_PATTERNS
        current_patterns_set = set(self.CRUFT_PATTERNS)
        new_from_gitignore = []

        for pattern in gitignore_patterns:
            # Normalize pattern for comparison
            normalized = pattern.rstrip('/')

            # Check if pattern or similar pattern already exists
            is_new = True
            for existing in current_patterns_set:
                if normalized in existing or existing in normalized:
                    is_new = False
                    break

            if is_new:
                new_from_gitignore.append(pattern)

        detected['gitignore_patterns'] = new_from_gitignore
        print(f"   Found {len(gitignore_patterns)} total .gitignore patterns")
        print(f"   Detected {len(new_from_gitignore)} new patterns not in current cruft list")

        # 2. Analyze historical removals
        print("2️⃣  Analyzing git history for frequently removed files...")
        deletion_counts = self.analyze_historical_removals()

        # Find patterns that appear in deletion history
        frequent_deletions = {path: count for path, count in deletion_counts.items() if count >= 3}

        # Extract patterns from frequently deleted files
        pattern_counts = {}
        for path in frequent_deletions.keys():
            # Extract file extension patterns
            if '.' in path:
                ext = '*' + path[path.rfind('.'):]
                pattern_counts[ext] = pattern_counts.get(ext, 0) + 1

            # Extract directory patterns
            if '/' in path:
                parts = path.split('/')
                for part in parts[:-1]:  # Exclude filename
                    if part.startswith('.') or part in ['node_modules', '__pycache__', 'dist', 'build']:
                        dir_pattern = f"{part}/"
                        pattern_counts[dir_pattern] = pattern_counts.get(dir_pattern, 0) + 1

        # Sort by frequency and filter out existing patterns
        new_from_history = []
        for pattern, count in sorted(pattern_counts.items(), key=lambda x: x[1], reverse=True):
            is_new = True
            for existing in current_patterns_set:
                if pattern in existing or existing in pattern:
                    is_new = False
                    break
            if is_new and count >= 3:  # At least 3 occurrences
                new_from_history.append(f"{pattern} (removed {count}x)")

        detected['historical_removals'] = new_from_history
        print(f"   Analyzed {len(deletion_counts)} deleted files")
        print(f"   Detected {len(new_from_history)} frequently removed patterns")

        # 3. Generate recommendations
        print("3️⃣  Generating recommendations...")

        # Combine and deduplicate
        recommended = set()

        # Add high-confidence patterns from .gitignore
        for pattern in new_from_gitignore[:20]:  # Top 20
            # Skip very generic patterns
            if pattern not in ['*', '**', '.', '..']:
                recommended.add(pattern)

        # Add high-confidence patterns from history
        for entry in new_from_history[:10]:  # Top 10
            pattern = entry.split(' (')[0]
            recommended.add(pattern)

        detected['recommended_patterns'] = sorted(list(recommended))

        print(f"   Generated {len(detected['recommended_patterns'])} recommended patterns")

        # 4. Display results
        print(f"\n{'='*70}")
        print("📊 DETECTION RESULTS")
        print(f"{'='*70}\n")

        if detected['recommended_patterns']:
            print("🎯 RECOMMENDED PATTERNS TO ADD:")
            print()
            for i, pattern in enumerate(detected['recommended_patterns'], 1):
                print(f"   {i:2d}. {pattern}")
            print()
            print("To add these patterns, update CRUFT_PATTERNS in the script:")
            print("   CRUFT_PATTERNS = [")
            print("       # ... existing patterns ...")
            for pattern in detected['recommended_patterns']:
                print(f'       "{pattern}",')
            print("   ]")
            print()
        else:
            print("✅ No additional cruft patterns detected!")
            print("   Current CRUFT_PATTERNS list is comprehensive.")
            print()

        # 5. Show detailed breakdown
        if new_from_gitignore:
            print("📄 NEW PATTERNS FROM .GITIGNORE:")
            for pattern in new_from_gitignore[:10]:
                print(f"   • {pattern}")
            if len(new_from_gitignore) > 10:
                print(f"   ... and {len(new_from_gitignore) - 10} more")
            print()

        if new_from_history:
            print("📜 FREQUENTLY REMOVED PATTERNS:")
            for entry in new_from_history[:10]:
                print(f"   • {entry}")
            if len(new_from_history) > 10:
                print(f"   ... and {len(new_from_history) - 10} more")
            print()

        return detected


def main():
    parser = argparse.ArgumentParser(
        description="FLEXT Git Ultimate Cleanup - The Only Script You Need",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--repo", type=Path, default=Path.cwd(), help="Repository path")
    parser.add_argument("--all", action="store_true", help="Process main + all submodules")
    parser.add_argument("--backup-only", action="store_true", help="Only create backup")
    parser.add_argument("--restore-remotes", action="store_true", help="Only restore remotes")
    parser.add_argument("--dry-run", action="store_true", help="Test mode - simulate operations without changes")
    parser.add_argument("--test", action="store_true", help="Run principal function tests and exit")
    parser.add_argument("--push", action="store_true", help="Push to GitHub after cleanup")
    parser.add_argument("--push-all", action="store_true", help="Push main + all submodules to GitHub")
    parser.add_argument("--detect-cruft", action="store_true", help="Detect additional cruft patterns from history and .gitignore")

    args = parser.parse_args()

    if not args.repo.exists():
        print(f"❌ Repository not found: {args.repo}")
        sys.exit(1)

    cleanup = GitUltimateCleanup(args.repo, dry_run=args.dry_run)

    # Just test
    if args.test:
        if cleanup.test_principal_functions():
            sys.exit(0)
        else:
            sys.exit(1)

    # Detect additional cruft
    if args.detect_cruft:
        cleanup.detect_additional_cruft()
        sys.exit(0)

    # Just restore remotes
    if args.restore_remotes:
        cleanup.restore_remotes()
        sys.exit(0)

    # Validate
    print(f"\n{'='*70}")
    print("🔍 VALIDATION")
    print(f"{'='*70}\n")

    valid, message = cleanup.validate_repository()
    if not valid:
        print(f"❌ {message}")
        sys.exit(1)
    print(message)

    # Confirm (skip in dry-run)
    if not args.backup_only and not args.dry_run:
        print(f"\n{'='*70}")
        print("⚠️  WARNING")
        print(f"{'='*70}")
        print("This will PERMANENTLY modify git history!")
        print(f"Repository: {args.repo}")
        print(f"Author: Marlon Costa <marlonsc@gmail.com>")
        print(f"AI references: REMOVED")
        print(f"Cruft: PURGED from history")
        if args.all:
            print("Scope: Main repo + ALL submodules")
        print()
        response = input("Continue? (yes/NO): ")
        if response.lower() != "yes":
            print("Cancelled.")
            sys.exit(0)

    # Create backup (skip in dry-run)
    if not args.dry_run:
        backup_path = cleanup.create_comprehensive_backup()

        if args.backup_only:
            print(f"✅ Backup complete: {backup_path}")
            sys.exit(0)
    else:
        backup_path = None

    # Cleanup main repo
    success = cleanup.cleanup_repository()
    if not success:
        sys.exit(1)

    # Cleanup submodules
    if args.all:
        submodules = cleanup.get_submodules()
        if submodules:
            print(f"\n{'='*70}")
            print(f"📦 SUBMODULES ({len(submodules)} total)")
            print(f"{'='*70}\n")

            for submodule in submodules:
                sub_cleanup = GitUltimateCleanup(submodule, dry_run=args.dry_run)
                sub_cleanup.cleanup_repository()

    # Restore remotes (not in dry-run)
    if not args.dry_run:
        cleanup.restore_remotes()

    # Push to GitHub if requested
    if args.push or args.push_all:
        if not args.dry_run:
            # Push main repo
            push_success = cleanup.push_to_github()
            if not push_success:
                print("⚠️  Main repository push failed")
                sys.exit(1)

            # Push submodules if requested
            if args.push_all:
                push_success = cleanup.push_all_submodules()
                if not push_success:
                    print("⚠️  Some submodule pushes failed")
                    sys.exit(1)
        else:
            print(f"\n{'='*70}")
            print("🧪 DRY RUN - WOULD PUSH TO GITHUB")
            print(f"{'='*70}\n")
            cleanup.push_to_github()
            if args.push_all:
                cleanup.push_all_submodules()

    # Final summary
    print(f"\n{'='*70}")
    if args.dry_run:
        print("🧪 DRY RUN COMPLETE")
    else:
        print("✅ CLEANUP COMPLETE")
    print(f"{'='*70}\n")

    if args.dry_run:
        print("📋 Dry run complete - no changes made")
        print("   Run without --dry-run to execute cleanup")
    else:
        print("📋 Next steps:")
        print("   1. Review: git log --oneline --format='%h %an: %s' | head -20")
        print("   2. Check authors: git log --format='%aN <%aE>' | sort -u")
        print("   3. Check size: git count-objects -vH")
        if not args.push and not args.push_all:
            print("   4. Force push: git push origin --force --all")
            print("   5. Push tags: git push origin --force --tags")
            if args.all:
                print("   6. Submodules: git submodule foreach 'git push origin --force --all'")
        print()
        if backup_path:
            print(f"💾 Backup: {backup_path}")
            print(f"   To recover: cd {backup_path} && ./RECOVER.sh")
    print()


if __name__ == "__main__":
    main()
