bashcode = ...
tcshcode = ...
fishcode = ...
powershell_code = ...
shell_codes = ...

def shellcode(
    executables,
    use_defaults=...,
    shell=...,
    complete_arguments=...,
    argcomplete_script=...,
):  # -> str:
    ...
