import sys
from collections import UserDict
from collections.abc import ItemsView, KeysView, Sequence, ValuesView

"""Sorted Dict
==============

:doc:`Sorted Containers<index>` is an Apache2 licensed Python sorted
collections library, written in pure-Python, and fast as C-extensions. The
:doc:`introduction<introduction>` is the best way to get started.

Sorted dict implementations:

.. currentmodule:: sortedcontainers

* :class:`SortedDict`
* :class:`SortedKeysView`
* :class:`SortedItemsView`
* :class:`SortedValuesView`

"""

class SortedDict(UserDict):
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def key(self):  # -> Callable[..., object] | None:
        ...
    @property
    def iloc(self):  # -> SortedKeysView:
        ...
    def clear(self):  # -> None:
        ...
    def __delitem__(self, key) -> None:  # -> None:
        ...
    def __iter__(self):  # -> chain[Any]:
        ...
    def __reversed__(self):  # -> chain[Any]:
        ...
    def __setitem__(self, key, value) -> None:  # -> None:
        ...

    _setitem = ...
    def __or__(self, other):  # -> _NotImplementedType | Self:
        ...
    def __ror__(self, other):  # -> _NotImplementedType | Self:
        ...
    def __ior__(self, other):  # -> Self:
        ...
    def copy(self):  # -> Self:
        ...

    __copy__ = ...
    @classmethod
    def fromkeys(cls, iterable, value=...):  # -> Self:
        ...
    def keys(self):  # -> SortedKeysView:
        ...
    def items(self):  # -> SortedItemsView:
        ...
    def values(self):  # -> SortedValuesView:
        ...

    if sys.hexversion < 50331648:
        iteritems = ...
        iterkeys = ...
        itervalues = ...
        viewitems = ...
        viewkeys = ...
        viewvalues = ...
    class _NotGiven: ...

    __not_given = ...
    def pop(self, key, default=...):  # -> _NotGiven:
        ...
    def popitem(self, index=...):  # -> tuple[Any, Any]:
        ...
    def peekitem(self, index=...):  # -> tuple[Any | list[Any], Any]:
        ...
    def setdefault(self, key, default=...):  # -> None:
        ...
    def update(self, *args, **kwargs):  # -> None:
        ...

    _update = ...
    def __reduce__(
        self,
    ):  # -> tuple[type[Self], tuple[Any | Callable[..., object] | None, dict[Any, Any]]]:
        ...

class SortedKeysView(KeysView, Sequence):
    __slots__ = ...
    def __getitem__(self, index): ...

    __delitem__ = ...

class SortedItemsView(ItemsView, Sequence):
    __slots__ = ...
    def __getitem__(self, index):  # -> list[tuple[Any, Any]] | tuple[Any, Any]:
        ...

    __delitem__ = ...

class SortedValuesView(ValuesView, Sequence):
    __slots__ = ...
    def __getitem__(self, index):  # -> list[Any]:
        ...

    __delitem__ = ...
