import collections
import io
import pkgutil
import types
import zipfile
import zipimport
from collections.abc import Callable, Iterable, Iterator
from pkgutil import get_importer
from typing import (
    TYPE_CHECKING,
    Any,
    BinaryIO,
    Literal,
    NamedTuple,
    NoReturn,
    Protocol,
    Self,
    TypeVar,
    overload,
)

import packaging.requirements
import packaging.specifiers
import packaging.version
from _typeshed import BytesPath, StrOrBytesPath, StrPath
from _typeshed.importlib import LoaderProtocol
from jaraco.text import yield_lines

"""
Package resource API
--------------------

A resource is a logical file contained within a package, or a logical
subdirectory thereof.  The package resource API expects resource names
to have their path parts separated with ``/``, *not* whatever the local
path separator is.  Do not use os.path operations to manipulate resource
names being passed into the API.

The package resource API is designed to work with normal filesystem packages,
.egg files, and unpacked .egg files.  It can also work in a limited way with
.zip files and with custom PEP 302 loaders that support the ``get_data()``
method.

This module is deprecated. Users are directed to :mod:`importlib.resources`,
:mod:`importlib.metadata` and :pypi:`packaging` instead.
"""
WRITE_SUPPORT = ...
if TYPE_CHECKING: ...
_T = TypeVar("_T")
_DistributionT = TypeVar("_DistributionT", bound=Distribution)
type _NestedStr = str | Iterable[str | Iterable[_NestedStr]]
type _StrictInstallerType = Callable[[Requirement], _DistributionT]
type _InstallerType = Callable[[Requirement], Distribution | None]
type _PkgReqType = str | Requirement
type _EPDistType = Distribution | _PkgReqType
type _t.Ldif.MetadataType = IResourceProvider | None
type _ResolvedEntryPoint = Any
type _ResourceStream = Any
type _ModuleLike = object | types.ModuleType
type _ProviderFactoryType = Callable[[Any], IResourceProvider]
type _DistFinderType[_T] = Callable[[_T, str, bool], Iterable[Distribution]]
type _NSHandlerType[_T] = Callable[[_T, str, str, types.ModuleType], str | None]

class _ZipLoaderModule(Protocol):
    __loader__: zipimport.zipimporter

_PEP440_FALLBACK = ...

class PEP440Warning(RuntimeWarning): ...

parse_version = packaging.version.Version
_state_vars: dict[str, str] = ...

def __getstate__() -> dict[str, Any]: ...
def __setstate__(state: dict[str, Any]) -> dict[str, Any]: ...

_sset_none = ...

def get_supported_platform():  # -> str:
    ...

__all__ = [
    "BINARY_DIST",
    "CHECKOUT_DIST",
    "DEVELOP_DIST",
    "EGG_DIST",
    "SOURCE_DIST",
    "AvailableDistributions",
    "DefaultProvider",
    "Distribution",
    "DistributionNotFound",
    "EggMetadata",
    "EggProvider",
    "EmptyProvider",
    "EntryPoint",
    "Environment",
    "ExtractionError",
    "FileMetadata",
    "IMetadataProvider",
    "IResourceProvider",
    "NullProvider",
    "PEP440Warning",
    "PathMetadata",
    "PkgResourcesDeprecationWarning",
    "Requirement",
    "ResolutionError",
    "ResourceManager",
    "UnknownExtra",
    "VersionConflict",
    "WorkingSet",
    "ZipProvider",
    "add_activation_listener",
    "cleanup_resources",
    "compatible_platforms",
    "declare_namespace",
    "empty_provider",
    "ensure_directory",
    "evaluate_marker",
    "find_distributions",
    "fixup_namespace_packages",
    "get_default_cache",
    "get_distribution",
    "get_entry_info",
    "get_entry_map",
    "get_importer",
    "get_platform",
    "get_provider",
    "invalid_marker",
    "iter_entry_points",
    "load_entry_point",
    "normalize_path",
    "parse_requirements",
    "parse_version",
    "register_finder",
    "register_loader_type",
    "register_namespace_handler",
    "require",
    "resource_exists",
    "resource_filename",
    "resource_isdir",
    "resource_listdir",
    "resource_stream",
    "resource_string",
    "run_main",
    "run_script",
    "safe_extra",
    "safe_name",
    "safe_version",
    "set_extraction_path",
    "split_sections",
    "to_filename",
    "working_set",
    "yield_lines",
]

class ResolutionError(Exception): ...

class VersionConflict(ResolutionError):
    _template = ...
    @property
    def dist(self) -> Distribution: ...
    @property
    def req(self) -> Requirement: ...
    def report(self):  # -> str:
        ...
    def with_context(
        self, required_by: set[Distribution | str]
    ) -> Self | ContextualVersionConflict: ...

class ContextualVersionConflict(VersionConflict):
    _template = ...
    @property
    def required_by(self) -> set[str]: ...

class DistributionNotFound(ResolutionError):
    _template = ...
    @property
    def req(self) -> Requirement: ...
    @property
    def requirers(self) -> set[str] | None: ...
    @property
    def requirers_str(self):  # -> str:
        ...
    def report(self):  # -> str:
        ...

class UnknownExtra(ResolutionError): ...

_provider_factories: dict[type[_ModuleLike], _ProviderFactoryType] = ...
PY_MAJOR = ...
EGG_DIST = ...
BINARY_DIST = ...
SOURCE_DIST = ...
CHECKOUT_DIST = ...
DEVELOP_DIST = ...

def register_loader_type(
    loader_type: type[_ModuleLike], provider_factory: _ProviderFactoryType
) -> None: ...
@overload
def get_provider(moduleOrReq: str) -> IResourceProvider: ...
@overload
def get_provider(moduleOrReq: Requirement) -> Distribution: ...
def get_provider(
    moduleOrReq: str | Requirement,
) -> IResourceProvider | Distribution: ...
def get_build_platform():  # -> str:
    ...

macosVersionString = ...
darwinVersionString = ...
get_platform = ...

def compatible_platforms(provided: str | None, required: str | None) -> bool: ...
@overload
def get_distribution[DistributionT: Distribution](
    dist: _DistributionT,
) -> _DistributionT: ...
@overload
def get_distribution(dist: _PkgReqType) -> Distribution: ...
def get_distribution(dist: Distribution | _PkgReqType) -> Distribution: ...
def load_entry_point(
    dist: _EPDistType, group: str, name: str
) -> _ResolvedEntryPoint: ...
@overload
def get_entry_map(
    dist: _EPDistType, group: None = ...
) -> dict[str, dict[str, EntryPoint]]: ...
@overload
def get_entry_map(dist: _EPDistType, group: str) -> dict[str, EntryPoint]: ...
def get_entry_map(
    dist: _EPDistType, group: str | None = ...
):  # -> dict[str, EntryPoint] | dict[str, dict[str, EntryPoint]]:
    ...
def get_entry_info(dist: _EPDistType, group: str, name: str) -> EntryPoint | None: ...

class IMetadataProvider(Protocol):
    def has_metadata(self, name: str) -> bool: ...
    def get_metadata(self, name: str) -> str: ...
    def get_metadata_lines(self, name: str) -> Iterator[str]: ...
    def metadata_isdir(self, name: str) -> bool: ...
    def metadata_listdir(self, name: str) -> list[str]: ...
    def run_script(self, script_name: str, namespace: dict[str, Any]) -> None: ...

class IResourceProvider(IMetadataProvider, Protocol):
    def get_resource_filename(
        self, manager: ResourceManager, resource_name: str
    ) -> str: ...
    def get_resource_stream(
        self, manager: ResourceManager, resource_name: str
    ) -> _ResourceStream: ...
    def get_resource_string(
        self, manager: ResourceManager, resource_name: str
    ) -> bytes: ...
    def has_resource(self, resource_name: str) -> bool: ...
    def resource_isdir(self, resource_name: str) -> bool: ...
    def resource_listdir(self, resource_name: str) -> list[str]: ...

class WorkingSet:
    def __init__(self, entries: Iterable[str] | None = ...) -> None: ...
    def add_entry(self, entry: str) -> None: ...
    def __contains__(self, dist: Distribution) -> bool: ...
    def find(self, req: Requirement) -> Distribution | None: ...
    def iter_entry_points(
        self, group: str, name: str | None = ...
    ) -> Iterator[EntryPoint]: ...
    def run_script(self, requires: str, script_name: str) -> None: ...
    def __iter__(self) -> Iterator[Distribution]: ...
    def add(
        self,
        dist: Distribution,
        entry: str | None = ...,
        insert: bool = ...,
        replace: bool = ...,
    ) -> None: ...
    @overload
    def resolve(
        self,
        requirements: Iterable[Requirement],
        env: Environment | None,
        installer: _StrictInstallerType[_DistributionT],
        replace_conflicting: bool = ...,
        extras: tuple[str, ...] | None = ...,
    ) -> list[_DistributionT]: ...
    @overload
    def resolve(
        self,
        requirements: Iterable[Requirement],
        env: Environment | None = ...,
        *,
        installer: _StrictInstallerType[_DistributionT],
        replace_conflicting: bool = ...,
        extras: tuple[str, ...] | None = ...,
    ) -> list[_DistributionT]: ...
    @overload
    def resolve(
        self,
        requirements: Iterable[Requirement],
        env: Environment | None = ...,
        installer: _InstallerType | None = ...,
        replace_conflicting: bool = ...,
        extras: tuple[str, ...] | None = ...,
    ) -> list[Distribution]: ...
    def resolve(
        self,
        requirements: Iterable[Requirement],
        env: Environment | None = ...,
        installer: _InstallerType | None | _StrictInstallerType[_DistributionT] = ...,
        replace_conflicting: bool = ...,
        extras: tuple[str, ...] | None = ...,
    ) -> list[Distribution] | list[_DistributionT]: ...
    @overload
    def find_plugins(
        self,
        plugin_env: Environment,
        full_env: Environment | None,
        installer: _StrictInstallerType[_DistributionT],
        fallback: bool = ...,
    ) -> tuple[list[_DistributionT], dict[Distribution, Exception]]: ...
    @overload
    def find_plugins(
        self,
        plugin_env: Environment,
        full_env: Environment | None = ...,
        *,
        installer: _StrictInstallerType[_DistributionT],
        fallback: bool = ...,
    ) -> tuple[list[_DistributionT], dict[Distribution, Exception]]: ...
    @overload
    def find_plugins(
        self,
        plugin_env: Environment,
        full_env: Environment | None = ...,
        installer: _InstallerType | None = ...,
        fallback: bool = ...,
    ) -> tuple[list[Distribution], dict[Distribution, Exception]]: ...
    def find_plugins(
        self,
        plugin_env: Environment,
        full_env: Environment | None = ...,
        installer: _InstallerType | None | _StrictInstallerType[_DistributionT] = ...,
        fallback: bool = ...,
    ) -> tuple[
        list[Distribution] | list[_DistributionT], dict[Distribution, Exception]
    ]: ...
    def require(self, *requirements: _NestedStr) -> list[Distribution]: ...
    def subscribe(
        self, callback: Callable[[Distribution], object], existing: bool = ...
    ) -> None: ...
    def __getstate__(
        self,
    ) -> tuple[
        list[str],
        dict[str | None, list[str]],
        dict[str, Distribution],
        dict[str, str],
        list[Callable[[Distribution], object]],
    ]: ...
    def __setstate__(self, e_k_b_n_c) -> None: ...

class _ReqExtras(collections.UserDict[Requirement, tuple[str, ...]]):
    def markers_pass(
        self, req: Requirement, extras: tuple[str, ...] | None = ...
    ):  # -> bool:
        ...

class Environment:
    def __init__(
        self,
        search_path: Iterable[str] | None = ...,
        platform: str | None = ...,
        python: str | None = ...,
    ) -> None: ...
    def can_add(self, dist: Distribution) -> bool: ...
    def remove(self, dist: Distribution) -> None: ...
    def scan(self, search_path: Iterable[str] | None = ...) -> None: ...
    def __getitem__(self, project_name: str) -> list[Distribution]: ...
    def add(self, dist: Distribution) -> None: ...
    @overload
    def best_match(
        self,
        req: Requirement,
        working_set: WorkingSet,
        installer: _StrictInstallerType[_DistributionT],
        replace_conflicting: bool = ...,
    ) -> _DistributionT: ...
    @overload
    def best_match(
        self,
        req: Requirement,
        working_set: WorkingSet,
        installer: _InstallerType | None = ...,
        replace_conflicting: bool = ...,
    ) -> Distribution | None: ...
    def best_match(
        self,
        req: Requirement,
        working_set: WorkingSet,
        installer: _InstallerType | None | _StrictInstallerType[_DistributionT] = ...,
        replace_conflicting: bool = ...,
    ) -> Distribution | None: ...
    @overload
    def obtain(
        self, requirement: Requirement, installer: _StrictInstallerType[_DistributionT]
    ) -> _DistributionT: ...
    @overload
    def obtain(
        self,
        requirement: Requirement,
        installer: Callable[[Requirement], None] | None = ...,
    ) -> None: ...
    @overload
    def obtain(
        self, requirement: Requirement, installer: _InstallerType | None = ...
    ) -> Distribution | None: ...
    def obtain(
        self,
        requirement: Requirement,
        installer: Callable[[Requirement], None]
        | _InstallerType
        | None
        | _StrictInstallerType[_DistributionT] = ...,
    ) -> Distribution | None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __iadd__(self, other: Distribution | Environment) -> Self: ...
    def __add__(self, other: Distribution | Environment) -> Self: ...

AvailableDistributions = Environment

class ExtractionError(RuntimeError):
    manager: ResourceManager
    cache_path: str
    original_error: BaseException | None

class ResourceManager:
    extraction_path: str | None = ...
    def __init__(self) -> None: ...
    def resource_exists(
        self, package_or_requirement: _PkgReqType, resource_name: str
    ) -> bool: ...
    def resource_isdir(
        self, package_or_requirement: _PkgReqType, resource_name: str
    ) -> bool: ...
    def resource_filename(
        self, package_or_requirement: _PkgReqType, resource_name: str
    ) -> str: ...
    def resource_stream(
        self, package_or_requirement: _PkgReqType, resource_name: str
    ) -> _ResourceStream: ...
    def resource_string(
        self, package_or_requirement: _PkgReqType, resource_name: str
    ) -> bytes: ...
    def resource_listdir(
        self, package_or_requirement: _PkgReqType, resource_name: str
    ) -> list[str]: ...
    def extraction_error(self) -> NoReturn: ...
    def get_cache_path(
        self, archive_name: str, names: Iterable[StrPath] = ...
    ) -> str: ...
    def postprocess(
        self, tempname: StrOrBytesPath, filename: StrOrBytesPath
    ) -> None: ...
    def set_extraction_path(self, path: str) -> None: ...
    def cleanup_resources(self, force: bool = ...) -> list[str]: ...

def get_default_cache() -> str: ...
def safe_name(name: str) -> str: ...
def safe_version(version: str) -> str: ...
def safe_extra(extra: str) -> str: ...
def to_filename(name: str) -> str: ...
def invalid_marker(text: str) -> SyntaxError | Literal[False]: ...
def evaluate_marker(text: str, extra: str | None = ...) -> bool: ...

class NullProvider:
    egg_name: str | None = ...
    egg_info: str | None = ...
    loader: LoaderProtocol | None = ...
    def __init__(self, module: _ModuleLike) -> None: ...
    def get_resource_filename(
        self, manager: ResourceManager, resource_name: str
    ) -> str: ...
    def get_resource_stream(
        self, manager: ResourceManager, resource_name: str
    ) -> BinaryIO: ...
    def get_resource_string(
        self, manager: ResourceManager, resource_name: str
    ) -> bytes: ...
    def has_resource(self, resource_name: str) -> bool: ...
    def has_metadata(self, name: str) -> bool: ...
    def get_metadata(self, name: str) -> str: ...
    def get_metadata_lines(self, name: str) -> Iterator[str]: ...
    def resource_isdir(self, resource_name: str) -> bool: ...
    def metadata_isdir(self, name: str) -> bool: ...
    def resource_listdir(self, resource_name: str) -> list[str]: ...
    def metadata_listdir(self, name: str) -> list[str]: ...
    def run_script(self, script_name: str, namespace: dict[str, Any]) -> None: ...

class EggProvider(NullProvider):
    def __init__(self, module: _ModuleLike) -> None: ...

class DefaultProvider(EggProvider):
    def get_resource_stream(
        self, manager: object, resource_name: str
    ) -> io.BufferedReader: ...

class EmptyProvider(NullProvider):
    module_path: str | None = ...
    _has = ...
    def __init__(self) -> None: ...

empty_provider = ...

class ZipManifests(collections.UserDict[str, MemoizedZipManifests.manifest_mod]):
    @classmethod
    def build(cls, path: str) -> dict[str, zipfile.ZipInfo]: ...

    load = ...

class MemoizedZipManifests(ZipManifests):
    class manifest_mod(NamedTuple):
        manifest: dict[str, zipfile.ZipInfo]
        mtime: float

    def load(self, path: str) -> dict[str, zipfile.ZipInfo]: ...

class ZipProvider(EggProvider):
    eagers: list[str] | None = ...
    _zip_manifests = ...
    loader: zipimport.zipimporter
    def __init__(self, module: _ZipLoaderModule) -> None: ...
    @property
    def zipinfo(self):  # -> dict[str, ZipInfo]:
        ...
    def get_resource_filename(
        self, manager: ResourceManager, resource_name: str
    ) -> str: ...

class FileMetadata(EmptyProvider):
    def __init__(self, path: StrPath) -> None: ...
    def has_metadata(self, name: str) -> bool: ...
    def get_metadata(self, name: str) -> str: ...
    def get_metadata_lines(self, name: str) -> Iterator[str]: ...

class PathMetadata(DefaultProvider):
    def __init__(self, path: str, egg_info: str) -> None: ...

class EggMetadata(ZipProvider):
    def __init__(self, importer: zipimport.zipimporter) -> None: ...

_distribution_finders: dict[type, _DistFinderType[Any]] = ...

def register_finder(
    importer_type: type[_T], distribution_finder: _DistFinderType[_T]
) -> None: ...
def find_distributions(path_item: str, only: bool = ...) -> Iterable[Distribution]: ...
def find_eggs_in_zip(
    importer: zipimport.zipimporter, path_item: str, only: bool = ...
) -> Iterator[Distribution]: ...
def find_nothing(
    importer: object | None, path_item: str | None, only: bool | None = ...
):  # -> tuple[()]:
    ...
def find_on_path(
    importer: object | None, path_item, only=...
):  # -> Generator[Distribution, Any, None]:
    ...
def dist_factory(
    path_item, entry, only
):  # -> Callable[..., Generator[Distribution, Any, None]] | Callable[..., Iterable[Distribution]] | Callable[..., Iterable[Distribution] | tuple[()]] | NoDists:
    ...

class NoDists:
    def __bool__(self) -> Literal[False]: ...
    def __call__(self, fullpath: object):  # -> Iterator[Never]:
        ...

def safe_listdir(path: StrOrBytesPath):  # -> list[str] | list[bytes] | tuple[()]:
    ...
def distributions_from_metadata(path: str):  # -> Generator[Distribution, Any, None]:
    ...
def non_empty_lines(path):  # -> Generator[str, Any, None]:
    ...
def resolve_egg_link(path):  # -> Iterable[Distribution] | tuple[()]:
    ...

if hasattr(pkgutil, "ImpImporter"): ...
_namespace_handlers: dict[type, _NSHandlerType[Any]] = ...
_namespace_packages: dict[str | None, list[str]] = ...

def register_namespace_handler(
    importer_type: type[_T], namespace_handler: _NSHandlerType[_T]
) -> None: ...
def declare_namespace(packageName: str) -> None: ...
def fixup_namespace_packages(path_item: str, parent: str | None = ...) -> None: ...
def file_ns_handler(
    importer: object, path_item: StrPath, packageName: str, module: types.ModuleType
):  # -> str | None:
    ...

if hasattr(pkgutil, "ImpImporter"): ...

def null_ns_handler(
    importer: object,
    path_item: str | None,
    packageName: str | None,
    module: _ModuleLike | None,
) -> None: ...
@overload
def normalize_path(filename: StrPath) -> str: ...
@overload
def normalize_path(filename: BytesPath) -> bytes: ...
def normalize_path(filename: StrOrBytesPath) -> str | bytes: ...

if TYPE_CHECKING: ...
MODULE = ...
EGG_NAME = ...

class EntryPoint:
    def __init__(
        self,
        name: str,
        module_name: str,
        attrs: Iterable[str] = ...,
        extras: Iterable[str] = ...,
        dist: Distribution | None = ...,
    ) -> None: ...
    @overload
    def load(
        self,
        require: Literal[True] = ...,
        env: Environment | None = ...,
        installer: _InstallerType | None = ...,
    ) -> _ResolvedEntryPoint: ...
    @overload
    def load(
        self, require: Literal[False], *args: Any, **kwargs: Any
    ) -> _ResolvedEntryPoint: ...
    def load(
        self,
        require: bool = ...,
        *args: Environment | _InstallerType | None,
        **kwargs: Environment | _InstallerType | None,
    ) -> _ResolvedEntryPoint: ...
    def resolve(self) -> _ResolvedEntryPoint: ...
    def require(
        self, env: Environment | None = ..., installer: _InstallerType | None = ...
    ) -> None: ...

    pattern = ...
    @classmethod
    def parse(cls, src: str, dist: Distribution | None = ...) -> Self: ...
    @classmethod
    def parse_group(
        cls, group: str, lines: _NestedStr, dist: Distribution | None = ...
    ) -> dict[str, Self]: ...
    @classmethod
    def parse_map(
        cls,
        data: str | Iterable[str] | dict[str, str | Iterable[str]],
        dist: Distribution | None = ...,
    ) -> dict[str, dict[str, Self]]: ...

class Distribution:
    PKG_INFO = ...
    def __init__(
        self,
        location: str | None = ...,
        metadata: _t.Ldif.MetadataType = ...,
        project_name: str | None = ...,
        version: str | None = ...,
        py_version: str | None = ...,
        platform: str | None = ...,
        precedence: int = ...,
    ) -> None: ...
    @classmethod
    def from_location(
        cls, location: str, basename: StrPath, metadata: _t.Ldif.MetadataType = ..., **kw: int
    ) -> Distribution: ...
    @property
    def hashcmp(self):  # -> tuple[parse_version, int, str, str | None, str, str]:
        ...
    def __hash__(self) -> int: ...
    def __lt__(self, other: Distribution) -> bool: ...
    def __le__(self, other: Distribution) -> bool: ...
    def __gt__(self, other: Distribution) -> bool: ...
    def __ge__(self, other: Distribution) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def key(self):  # -> str:
        ...
    @property
    def parsed_version(self):  # -> parse_version:
        ...
    @property
    def version(self):  # -> str:
        ...
    def requires(self, extras: Iterable[str] = ...) -> list[Requirement]: ...
    def activate(self, path: list[str] | None = ..., replace: bool = ...) -> None: ...
    def egg_name(self):  # -> str:
        ...
    def __getattr__(self, attr: str):  # -> Any:
        ...
    def __dir__(self):  # -> list[str]:
        ...
    @classmethod
    def from_filename(
        cls, filename: StrPath, metadata: _t.Ldif.MetadataType = ..., **kw: int
    ) -> Distribution: ...
    def as_requirement(self):  # -> Requirement:
        ...
    def load_entry_point(self, group: str, name: str) -> _ResolvedEntryPoint: ...
    @overload
    def get_entry_map(self, group: None = ...) -> dict[str, dict[str, EntryPoint]]: ...
    @overload
    def get_entry_map(self, group: str) -> dict[str, EntryPoint]: ...
    def get_entry_map(
        self, group: str | None = ...
    ):  # -> dict[str, EntryPoint] | dict[str, dict[str, EntryPoint]]:
        ...
    def get_entry_info(self, group: str, name: str) -> EntryPoint | None: ...
    def insert_on(self, path: list[str], loc=..., replace: bool = ...) -> None: ...
    def check_version_conflict(self):  # -> None:
        ...
    def has_version(self) -> bool: ...
    def clone(self, **kw: str | int | IResourceProvider | None) -> Self: ...
    @property
    def extras(self):  # -> list[str]:
        ...

class EggInfoDistribution(Distribution): ...

class DistInfoDistribution(Distribution):
    PKG_INFO = ...
    EQEQ = ...

_distributionImpl = ...

def issue_warning(*args, **kw):  # -> None:
    ...
def parse_requirements(strs: _NestedStr) -> map[Requirement]: ...

class RequirementParseError(packaging.requirements.InvalidRequirement): ...

class Requirement(packaging.requirements.Requirement):
    extras: tuple[str, ...]
    def __init__(self, requirement_string: str) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __contains__(
        self, item: Distribution | packaging.specifiers.UnparsedVersion
    ) -> bool: ...
    def __hash__(self) -> int: ...
    @staticmethod
    def parse(s: str | Iterable[str]) -> Requirement: ...

def ensure_directory(path: StrOrBytesPath) -> None: ...
def split_sections(s: _NestedStr) -> Iterator[tuple[str | None, list[str]]]: ...

class PkgResourcesDeprecationWarning(Warning): ...

_LOCALE_ENCODING = ...
if TYPE_CHECKING:
    __resource_manager = ...
    resource_exists = ...
    resource_isdir = ...
    resource_filename = ...
    resource_stream = ...
    resource_string = ...
    resource_listdir = ...
    set_extraction_path = ...
    cleanup_resources = ...
    working_set = ...
    require = ...
    iter_entry_points = ...
    add_activation_listener = ...
    run_script = ...
    run_main = ...
