from datetime import datetime as DateTime, timedelta as TimeDelta, tzinfo as TZInfo

"""
Time zone utilities.
"""
__all__ = ["UTC", "FixedOffsetTimeZone"]

class FixedOffsetTimeZone(TZInfo):
    def __init__(self, offset: TimeDelta, name: str | None = ...) -> None: ...
    @classmethod
    def fromSignHoursMinutes(
        cls, sign: str, hours: int, minutes: int
    ) -> FixedOffsetTimeZone: ...
    @classmethod
    def fromLocalTimeStamp(cls, timeStamp: float) -> FixedOffsetTimeZone: ...
    def utcoffset(self, dt: DateTime | None) -> TimeDelta: ...
    def dst(self, dt: DateTime | None) -> TimeDelta: ...
    def tzname(self, dt: DateTime | None) -> str: ...

UTC = ...
