__docformat__ = ...
__all__ = [
    "InconsistentResolutionOrderError",
    "InconsistentResolutionOrderWarning",
    "ro",
]
__logger = ...

class InconsistentResolutionOrderWarning(PendingDeprecationWarning): ...

class InconsistentResolutionOrderError(TypeError):
    def __init__(self, c3, base_tree_remaining) -> None: ...

class _NamedBool(int):
    def __new__(cls, val, name):  # -> Self:
        ...

class _ClassBoolFromEnv:
    def __get__(self, inst, klass):  # -> _NamedBool:
        ...

class _StaticMRO:
    had_inconsistency = ...
    def __init__(self, C, mro) -> None: ...
    def mro(self):  # -> list[Any]:
        ...

_INCONSISTENT_RESOLUTION_ORDER = ...

class C3:
    @staticmethod
    def resolver(C, strict, base_mros):  # -> _StrictC3 | _TrackingC3 | C3:
        ...

    __mro = ...
    __legacy_ro = ...
    direct_inconsistency = ...
    def __init__(self, C, memo) -> None: ...
    @property
    def had_inconsistency(self):  # -> InconsistentResolutionOrderError | bool:
        ...
    @property
    def legacy_ro(self):  # -> list[Any]:
        ...

    TRACK_BAD_IRO = ...
    STRICT_IRO = ...
    WARN_BAD_IRO = ...
    LOG_CHANGED_IRO = ...
    USE_LEGACY_IRO = ...
    BAD_IROS = ...
    class _UseLegacyRO(Exception): ...

    def mro(self):  # -> list[Any]:
        ...

class _StrictC3(C3):
    __slots__ = ...

class _TrackingC3(C3):
    __slots__ = ...

class _ROComparison:
    class Item:
        prefix = ...
        def __init__(self, item) -> None: ...

    class Deleted(Item):
        prefix = ...

    class Inserted(Item):
        prefix = ...

    Empty = str
    class ReplacedBy:
        prefix = ...
        suffix = ...
        def __init__(self, chunk, total_count) -> None: ...
        def __iter__(self):  # -> Iterator[str]:
            ...

    class Replacing(ReplacedBy):
        prefix = ...
        suffix = ...

    _c3_report = ...
    _legacy_report = ...
    def __init__(self, c3, c3_ro, legacy_ro) -> None: ...

_ROOT = ...

def ro(
    C, strict=..., base_mros=..., log_changed_ro=..., use_legacy_ro=...
):  # -> list[Any]:
    ...
def is_consistent(C):  # -> bool:
    ...
