---
- name: Test SystemD Configuration
  hosts: oud-srv1.ctbc.local
  become: true
  gather_facts: false

  vars:
    oracle_oud_14_systemd_service_name: "oud@.service"
    oracle_oud_14_systemd_service_path: "/etc/systemd/system/oud@.service"

  tasks:
    - name: Include SystemD tasks
      include_tasks: roles/oracle_oud_14/tasks/systemd.yml
