MAX_EXPONENT = ...
BIAS = ...
MAX_POSITIVE_EXPONENT = ...

def exponent_key(e: int) -> float: ...

ENCODING_TABLE = ...
DECODING_TABLE = ...

def decode_exponent(e: int) -> int: ...
def encode_exponent(e: int) -> int: ...
def reverse_byte(b: int) -> int: ...

REVERSE_BITS_TABLE = ...

def reverse64(v: int) -> int: ...

MANTISSA_MASK = ...

def reverse_bits(x: int, n: int) -> int: ...
def update_mantissa(unbiased_exponent: int, mantissa: int) -> int: ...
def lex_to_float(i: int) -> float: ...
def float_to_lex(f: float) -> int: ...
def base_float_to_lex(f: float) -> int: ...
def is_simple(f: float) -> int: ...
